lbryio/lbry-sdk

INSTALL.md
README.md
RUNNING.md

Still not completely consistent, but should be a start. Much easier to read with the monospace formatting around the commands.

Markdown cleanups

---

lbrynet/lbrynet_daemon/LBRYDaemon.py
lbrynet/lbrynet_daemon/LBRYDownloader.py

Added a 'get' function, which starts a download and returns the resulting file path.

Add 'get' function to daemon

---

lbrynet/core/LBRYcrdWallet.py
lbrynet/lbrynet_console/LBRYConsole.py
lbrynet/lbrynet_gui/LBRYGui.py

Fix paths to use binaries in the app bundle

Fix paths for os x binaries

---

lbrynet/lbrynet_daemon/LBRYDaemonStopper.py
lbrynet/lbrynet_daemon/LBRYURIHandler/LBRYURIHandler.py
setup.py

Add command to stop daemon from the terminal
If lbrynet-daemon isn’t running the uri handler will now redirect to
lbry.io/get

Update daemon and uri handler

---

.gitignore
INSTALL.md
lbrynet/lbrynet_gui/GuiApp.py
setup_win32.py

Tested with windows 10 x64 running python 2.7.11 x86 to create binary builds and msi installers.

Enable building and installing of GUI for windows

---

.gitmodules
.travis.yml
packaging/osx/add-key.sh
packaging/ubuntu/ubuntu_package_setup.sh

- adds a travis.yml config file
- modifies the ubuntu build script to work on travis
- adds start of osx builds
- waiting for certs to be added

Enabling builds on travis-ci

---

.travis.yml

take this out so we can more easily test deployment

comment out version check

---

packaging/osx/lbry-osx-app/setup_app.py
packaging/osx/lbry-osx-app/setup_app.sh

PyObjC parts were missing from the build on travis, this should hopefully be the minimum needed to fix that.

Install pyobjc dependencies

---

.travis.yml

cache dependencies to speed up the build

add caching for travis

---

lbrynet/core/server/BlobRequestHandler.py
packaging/travis/install_dependencies_and_run_tests.sh
tests/lbrynet/core/server/test_BlobRequestHandler.py

Started poking around some of the internals of the daemon and added some tests.

add tests for BlobRequestHandler and run on travis

---

INSTALL.md

Some people dont have git installed so adding it to it solves confusion for people new to linux.

Adding git to linux install command

---

RUNNING.md

First install needed packages then execute the task. Cant run the whole code if git isnt installed :)

Cant use git if its not installed

---

FAQ.md

You cant execute the code that follows after if you havent installed git already.

Need to have git installed

---

lbrynet/lbrynet_daemon/LBRYDaemon.py
lbrynet/lbrynet_daemon/LBRYDaemonControl.py
lbrynet/lbrynet_daemon/LBRYDaemonServer.py
lbrynet/lbrynet_daemon/LBRYDownloader.py
lbrynet/lbrynet_daemon/LBRYPublisher.py

Instead of manually adding datetime.now() use
asctime formatter to do it for us.

use asctime in logging format

---

lbrynet/lbrynet_daemon/LBRYDaemon.py
lbrynet/lbrynet_daemon/LBRYDaemonControl.py
lbrynet/lbrynet_daemon/LBRYDaemonServer.py

This adds a new resource and shouldn't affect anything else

Add support for file uploads (for Publish page)

---

lbrynet/lbrynet_daemon/LBRYDaemon.py

Remove datetime.now() from log statements

---

lbrynet/core/LBRYMetadata.py
lbrynet/core/LBRYWallet.py
lbrynet/lbryfile/LBRYFileMetadataManager.py
lbrynet/lbryfilemanager/LBRYFileDownloader.py
lbrynet/lbryfilemanager/LBRYFileManager.py
lbrynet/lbrynet_daemon/LBRYDaemon.py
lbrynet/lbrynet_daemon/LBRYPublisher.py

-update over existing claim in publish
-add claim_id to lbry files
-include supports in claim total
-add is_mine field to get_claim_info return

claim updates

---

lbrynet/__init__.py
lbrynet/core/log_support.py
lbrynet/dht/node.py
lbrynet/lbrynet_daemon/LBRYDaemonControl.py

Cherry-picked out some log improvements from the reflector branch.

Add debug logging

---

lbrynet/lbrynet_console/LBRYSettings.py

This fixes: https://app.asana.com/0/158602294500137/165137057233590

Save settings

---

lbrynet/core/LBRYWallet.py
lbrynet/core/client/ConnectionManager.py
lbrynet/core/log_support.py
lbrynet/lbrynet_daemon/LBRYExchangeRateManager.py

-fix log line that could raise an exception
-json encode value sent to lbrycrd-cli updateclaim

LBRYcrdWallet update claim fix

---

lbrynet/core/LBRYWallet.py
lbrynet/lbrynet_daemon/LBRYDaemon.py

Checks if an address is associated with the current wallet

Add address_is_mine() API method

---

.appveyor.yml
packaging/windows/init.ps1
packaging/windows/install.ps1
packaging/windows/test.ps1

- move init and build steps into dedicated scripts
- deploy msi artifact on tag

appveyor updates

---

lbrynet/lbrynet_daemon/DaemonServer.py

Currently only supports direct streaming (i.e. no range requests).

More reliable stream producer

---

lbrynet/lbrynet_daemon/Daemon.py

https://github.com/lbryio/lbry/issues/190

make publish fail when given an invalid file

---

lbrynet/core/utils.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/DaemonControl.py
packaging/osx/lbry-osx-app/lbrygui/LBRYApp.py
packaging/windows/lbry-win32-app/LBRYWin32App.py

https://github.com/lbryio/lbry/issues/192

Use lbry.io instead of google to check for internet connection

---

lbrynet/conf.py
lbrynet/core/BlobAvailability.py
lbrynet/core/PaymentRateManager.py
lbrynet/core/PriceModel.py
lbrynet/core/Session.py
lbrynet/core/Strategy.py
lbrynet/core/Wallet.py
lbrynet/core/client/BlobRequester.py
lbrynet/core/server/BlobRequestHandler.py
lbrynet/lbrynet_daemon/Daemon.py
tests/functional/test_misc.py
tests/mocks.py

-also move is_generous_host into a conf setting

fix problems in blobrequester

---

lbrynet/core/log_support.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/DaemonControl.py
lbrynet/lbrynet_daemon/DaemonServer.py

If there is an error encountered during setup, the application will now log the error and shutdown.
Adds a check that the database version is compatible.  This will only occur during development, but still a good check to have.

Shutdown during setup

---

lbrynet/lbrynet_daemon/DaemonControl.py
packaging/osx/lbry-osx-app/lbrygui/LBRYApp.py
packaging/windows/lbry-win32-app/LBRYWin32App.py

Remove duplicate code across the different launch points

make app startup consistent across versions

---

lbrynet/conf.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/DaemonControl.py

These were all dumb mistakes... not sure how they made it passed pylint :/

various fixes

---

packaging/travis/install_dependencies_and_run_tests.sh

Coveralls tracks our test coverage: https://coveralls.io/github/lbryio/lbry/

Add coverage reporting

---

.pylintrc
lbrynet/conf.py
lbrynet/core/utils.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/DaemonControl.py
lbrynet/lbrynet_daemon/DaemonServer.py
packaging/osx/lbry-osx-app/lbrygui/LBRYApp.py
packaging/osx/lbry-osx-app/lbrygui/main.py
packaging/windows/lbry-win32-app/LBRYWin32App.py

Also moves the config loading to BEFORE the log configuration

Read config file in windows and osx

---

.pylintrc
lbrynet/conf.py
lbrynet/core/utils.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/DaemonControl.py
lbrynet/lbrynet_daemon/DaemonServer.py
packaging/osx/lbry-osx-app/lbrygui/LBRYApp.py
packaging/osx/lbry-osx-app/lbrygui/main.py
packaging/windows/lbry-win32-app/LBRYWin32App.py

I accidentally merged my last pull request instead of master.  Merging this into master.

Read config

---

lbrynet/conf.py
lbrynet/lbrynet_daemon/Daemon.py
packaging/osx/lbry-osx-app/lbrygui/LBRYApp.py
packaging/osx/lbry-osx-app/lbrygui/main.py
packaging/osx/lbry-osx-app/setup_app.sh
packaging/windows/lbry-win32-app/LBRYWin32App.py
packaging/windows/test.ps1

This also fixes a trivial bug in the osx release.

lint the osx and windows apps

---

lbrynet/conf.py

This fixes a bug where the daemon tries to read the conf file, whether or not it exists.

fix missing conf file on first run

---

lbrynet/conf.py
lbrynet/core/StreamCreator.py
lbrynet/cryptstream/CryptStreamCreator.py
lbrynet/lbryfilemanager/EncryptedFileCreator.py
tests/mocks.py
tests/unit/lbryfilemanager/test_EncryptedFileCreator.py

Fixes: https://app.asana.com/0/198587529699250/198478644096914

Unicode publish

---

.appveyor.yml
.travis.yml
MANIFEST.in
lbrynet/lbrynet_daemon/UIManager.py
packaging/travis/setup_osx.sh
packaging/windows/init.ps1
packaging/windows/install.ps1
packaging/windows/test.ps1
setup.py

This changes the build process to include the UI code from the development branch in the package for all non-production builds. The UI manager will prefer the bundled UI and also not fetch updates.
The version is also changed, with the commit SHA appended. Otherwise it might be difficult to tell if we are running a production release or a QA one.

Bundle the UI into non-tagged builds.

---

lbrynet/core/Error.py
lbrynet/core/Wallet.py
lbrynet/cryptstream/CryptBlob.py
lbrynet/dht/node.py
lbrynet/dht/protocol.py
lbrynet/dht/routingtable.py
lbrynet/dhttest.py
lbrynet/lbrynet_console/Console.py
lbrynet/lbrynet_daemon/DaemonRequest.py
lbrynet/metadata/Metadata.py
lbrynet/metadata/metadata_schemas.py
lbrynet/reflector/server/server.py
lbrynet/winhelpers/knownpaths.py
packaging/osx/lbry-osx-app/setup_app.sh
packaging/travis/install_dependencies_and_run_tests.sh
packaging/windows/test.ps1

Very straight-forward.  Ran a check in pylint for `bad-whitespace` and fixed up where there were issues.

add bad-whitespace check to pylint

---

lbrynet/lbrynet_daemon/UIManager.py

I forgot to load the ui when it was already bundled.

bug fix: ensure the bundled ui is loaded

---

lbrynet/core/HashBlob.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/reflector/__init__.py
lbrynet/reflector/client/blob.py
lbrynet/reflector/client/client.py
lbrynet/reflector/common.py

Wrote this little script while I was investigating this: https://github.com/lbryio/lbry/issues/261
It generates a random blob of data and sends it to reflector; if there is an error a message can be sent to a webhook in slack.

Remove repeated code for reflector

---

lbrynet/lbrynet_daemon/Daemon.py

lbry.io being down caused lbrynet to die when uploading a log.

Bug fix: continue even if log fails to upload

---

lbrynet/analytics/api.py
lbrynet/analytics/events.py
lbrynet/analytics/manager.py
lbrynet/build_type.py
lbrynet/conf.py
lbrynet/core/Platform.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/DaemonControl.py
lbrynet/lbrynet_daemon/DaemonServer.py
lbrynet/lbrynet_daemon/auth/server.py
packaging/osx/lbry-osx-app/lbrygui/LBRYApp.py
packaging/windows/lbry-win32-app/LBRYWin32App.py

- move analytics creation earlier in the startup process
- add several events to track startup, startup failure, other errors
- abstract platform detection into separate file
- add "build" type to platform so we can differentiate devs vs live users
this is still missing the code that sets "build" in Travis, but im running out of time

Better metrics

---

.travis.yml
packaging/travis/setup_build.sh
packaging/windows/build.ps1

Travis built this successfully, but I don't think that I can test whether it worked or not without getting the finished .deb. Can you please merge this before the nightlys get built? I'll check this first thing tomorrow morning and revert it if anything's broken.

set build type in travis

---

lbrynet/lbrynet_daemon/Daemon.py

auto-connect should be auto_connect

fix spelling mistake for auto connect

---

lbrynet/conf.py
lbrynet/core/Wallet.py
lbrynet/db_migrator/dbmigrator.py
lbrynet/db_migrator/migrate1to2.py
lbrynet/lbryfilemanager/EncryptedFileDownloader.py
lbrynet/lbrynet_console/ControlHandlers.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/Publisher.py
tests/dht/testNode.py

This is the rebased pull request for adding txid + nout into lbrynet.  
Requires lbryum pull request : 
https://github.com/lbryio/lbryum/pull/34

Add txid + nout 

---

lbrynet/lbrynet_daemon/Daemon.py

Reports the same shortened, base58 encoded version included in logs

get_lbry_session_info function to retrieve lbry id, blob, and file count information

---

lbrynet/core/Wallet.py
lbrynet/db_migrator/dbmigrator.py
lbrynet/db_migrator/migrate1to2.py
lbrynet/lbrynet_daemon/Daemon.py
tests/mocks.py

Build is currently failing, this should fix it.

fix pylint errors

---

lbrynet/lbrynet_daemon/Daemon.py

https://app.asana.com/0/198587529699250/220821321387626

don't allow 0 bid in publish

---

lbrynet/core/utils.py
tests/unit/core/test_utils.py

Fixes https://app.asana.com/0/198587529699250/219233372185252

allow for rc in version values

---

lbrynet/core/Wallet.py

Downgrading log.info's that may contain user's personal information to log.debug's in Wallet

Converting some log.info to log.debug in Wallet

---

lbrynet/conf.py
lbrynet/lbrynet_daemon/auth/server.py

Replaces https://github.com/lbryio/lbry/pull/286

allow Access-Control-Allow-Origin to be configurable

---

setup.py

Fix the Build

---

packaging/osx/lbry-osx-app/setup_app.sh

Sadly, not ready yet for pyobjc-3.2.

Pin pyobjc to version 3.1.1

---

lbrynet/lbrynet_daemon/Daemon.py

change error log on resolve-name to info

---

lbrynet/dht/protocol.py

The old code relied on the timing of DelayedCalls
to see what had been called or not, but unfortunately
we don't have a real-time OS so the timing on DelayedCalls
will only be approximate. Changed to explicitly keep
track of which calls had been made.
This simplifies the shutdown logic drastically, and I believe
we can take out the reactor.iterate() now

Better dht shutdown.

---

lbrynet/core/Wallet.py

Redo of https://github.com/lbryio/lbry/pull/308
https://github.com/lbryio/lbry/commit/7d02e7d37065e3f55efcee49353efd08adb0907a changes the order of how the wallet is loaded. Before it would load the network, load the disk wallet, and then catch up on the blockchain (if any steps failed, the subsequent steps would not be performed) . If loading the network failed, the wallet would never be loaded (we can still query the wallet for balance, and transactions even if not connected to the network).
Now we load the disk wallet first, load the network, and than catch up on the blockchain so that the wallet is always loaded regardless of if the network loaded.
https://github.com/lbryio/lbry/commit/dafb8f1cf8db928a81c49f8971bd316608276f8d fixes cmd_runner so that the Commands object would always …

Fix wallet initialization 

---

scripts/download_blob_from_peer.py
scripts/download_blobs_from_reflector.py

@lyoshenka this is what I've been using to test reflector recently.
Something like
`python download_blobs_from_reflector.py 198.199.87.180 --batch=10 --size=50 --timeout=300`
will try to download 50 blobs in 5 batches of 10.

scripts to test reflector

---

lbrynet/core/Wallet.py

Same fix as : 
https://github.com/lbryio/lbryum/pull/65

Fixing get_value_for_name bug

---

lbrynet/lbrynet_daemon/Daemon.py

Was causing it to throw errors

Fix typo in set_settings API method

---

lbrynet/core/client/BlobRequester.py

Ran into a situation where I was receiving an offer response without
something in protocol_offers. I think this was because
get_and_set_rate doesn't always populate that dictionary.
I'm slightly worried that there still might be issues if the connection is
unreliable: if a response comes in twice it will error or
if a second offer is made without a response to the first
there will be an error.

Only store the offer explicitly when its sent

---

lbrynet/analytics/events.py
lbrynet/analytics/manager.py
lbrynet/core/client/ClientProtocol.py
lbrynet/core/client/ConnectionManager.py
lbrynet/core/client/DownloadManager.py
lbrynet/core/log_support.py
lbrynet/core/utils.py
lbrynet/cryptstream/client/CryptStreamDownloader.py
lbrynet/lbryfile/EncryptedFileMetadataManager.py
lbrynet/lbryfilemanager/EncryptedFileDownloader.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/Downloader.py
tests/functional/test_misc.py
tests/unit/analytics/test_events.py

Adds a download_errored and download_finished so that we can better track how well downloads are working.
Also makes a lot of inlineCallback cleanup related changes.

Analytics on get

---

lbrynet/lbrynet_daemon/Daemon.py

Doesn't actually fix them, but at least makes them more informative.

Fix stop errors

---

lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/DaemonControl.py
lbrynet/lbrynet_daemon/DaemonServer.py
lbrynet/lbrynet_daemon/UIManager.py

this opens the ui after UIManager.setup rather than after the whole Daemon.setup chain

open the ui as soon as possible

---

INSTALL.md
README.md

I didn't rewrite the For Developers section of the README yet, but this can still go live.

improvements to readme and install instructions

---

lbrynet/core/HashBlob.py
lbrynet/metadata/Metadata.py
scripts/common.py
scripts/name.py
scripts/pool.py
scripts/query_available_blobs.py
scripts/send_sd_blobs_to_lighthouse.py
scripts/track.py

The output of this script is actually repeatable now.  I was running into locking issues with sqlite so I made a new storage class for the nameclaim metadata.
This is a WIP because I still need to incorporate the wallet changes into the rest of lbrynet.

Query available blobs and Upload to Lighthouse Scripts

---

lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/auth/server.py

A rebased version of https://github.com/lbryio/lbry/pull/394

handle dropped api requests

---

lbrynet/lbrynet_daemon/Daemon.py

Also switch status call to an inlineCallback

Safegaurd against there not being a wallet on status call

---

lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/Resources.py

Related to https://github.com/lbryio/lbry/pull/448

Fixes for named parameter changes on api

---

.travis.yml
CHANGELOG.md
Dangerfile

Add changelog

---

CHANGELOG.md
lbrynet/lbryfilemanager/EncryptedFileManager.py

Fixes https://github.com/lbryio/lbry/issues/470

fix file_delete

---

CHANGELOG.md
lbrynet/core/Wallet.py

https://github.com/lbryio/lbry/issues/473

fix Wallet.claim_name, convert to inlineCallbacks

---

CHANGELOG.md
lbrynet/dht/protocol.py

not sure if good idea or bad idea

silence "[Errno 11] Resource temporarily unavailable" error

---

CHANGELOG.md
lbrynet/lbryfilemanager/EncryptedFileDownloader.py
lbrynet/lbryfilemanager/EncryptedFileManager.py
lbrynet/lbrynet_daemon/Daemon.py

Doesn't fix #478, but will help with diagnosing it.

Add traceback to error in EncryptedFileManager

---

CHANGELOG.md
lbrynet/lbrynet_daemon/Daemon.py

Catch unknown name error

---

CHANGELOG.md
lbrynet/core/BlobManager.py
lbrynet/core/HashBlob.py
lbrynet/core/client/DownloadManager.py
lbrynet/core/client/StandaloneBlobDownloader.py
lbrynet/core/server/BlobRequestHandler.py
lbrynet/cryptstream/client/CryptStreamDownloader.py
lbrynet/lbryfile/client/EncryptedFileDownloader.py
lbrynet/lbryfile/client/EncryptedFileOptions.py
lbrynet/lbryfilemanager/EncryptedFileDownloader.py
lbrynet/lbryfilemanager/EncryptedFileManager.py
lbrynet/lbrylive/client/LiveStreamDownloader.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/Downloader.py
lbrynet/reflector/client/blob.py
lbrynet/reflector/client/client.py
lbrynet/reflector/server/server.py
tests/functional/test_misc.py
tests/functional/test_reflector.py

This is unused and largely polluting the argument list of too many functions.

No more upload_allowed

---

lbrynet/core/HashBlob.py
lbrynet/core/StreamCreator.py
lbrynet/lbryfilemanager/EncryptedFileCreator.py
lbrynet/lbryfilemanager/EncryptedFileManager.py
scripts/decrypt_blob.py
scripts/encrypt_blob.py
scripts/query_available_blobs.py
scripts/reseed_file.py

Opening this so that I remind myself to clean this up and get it merged in

Script to Reseed a File

---

CHANGELOG.md
lbrynet/core/file_utils.py
lbrynet/lbrynet_daemon/Daemon.py

Remove unuseful/unused commands from Daemon API
get_nametrie
log
upload_log
get_mean_availability

Removing unuseful/unused commands from daemon API

---

lbrynet/lbrynet_daemon/Daemon.py

fix docstring for daemon publish command

fix docstring for daemon publish command

---

tests/unit/core/server/test_DHTHashAnnouncer.py
tests/unit/lbryfile/client/test_EncryptedFileDownloader.py
tests/unit/lbryfile/test_EncryptedFileMetadataManager.py
tests/unit/lbryfilemanager/test_EncryptedFileManager.py
tests/util.py

Just some unit tests for file manager related classes. 
Added random_lbry_hash() function to generate random lbry hases in tests.util 
Add tests for EncryptedFileSaver and DBEncryptedFileMetadataManager (aka stream_info_manager).

Filemanager related unit tests

---

lbrynet/core/Wallet.py

remove unused _get_status_of_claim() and get_name_and_validity_for_sd_hash() function in Wallet

remove unused functions in wallet

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/lbrynet_daemon/Daemon.py

This patch integrates changes in lbryum pull request https://github.com/lbryio/lbryum/pulls . 
Since the lbryum pull request changes dictionary key names of lbryum function outputs, we need to make the appropriate change in the Wallet code.

Integrate more consistent dictionary keys from lbryum

---

lbrynet/core/Wallet.py

bid was float and not subtractable by decimal

Fix bug in update

---

docs/index.md
lbrynet/lbrynet_daemon/Daemon.py

Update and fix some deamon api doc strings.
Ran the gen_api_doc.py script to generate new doc file.

Daemon API doc string update

---

lbrynet/lbrynet_daemon/DaemonCLI.py

lbrynet-cli did not format the help message properly when there was an error

format help message properly in case of error in CLI

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/auth/server.py
lbrynet/lbrynet_daemon/auth/util.py
lbrynet/undecorated.py

Catch all errors thrown in jsonrpc, format them nicely.

Jsonrpc fix errors

---

CHANGELOG.md
lbrynet/lbrynet_daemon/Daemon.py

This removes _check_pending_claims() and related logic from the Daemon 
https://github.com/lbryio/lbry/issues/556

Remove pending_claims logic from Daemon

---

CHANGELOG.md
INSTALL.md
lbrynet/analytics/events.py
lbrynet/conf.py
lbrynet/core/Wallet.py
lbrynet/core/utils.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/Downloader.py
lbrynet/lbrynet_daemon/ExchangeRateManager.py
lbrynet/lbrynet_daemon/Publisher.py
lbrynet/metadata/Fee.py
requirements.txt
setup.py
tests/unit/core/test_Wallet.py
tests/unit/lbrynet_daemon/test_Daemon.py
tests/unit/lbrynet_daemon/test_ExchangeRateManager.py

Lbryschema integration 

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/dht/protocol.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/DaemonControl.py
lbrynet/lbrynet_daemon/DaemonServer.py
lbrynet/lbrynet_daemon/ExchangeRateManager.py

-Fix multiple reactor.stop() calls
-Properly shut down lbryum wallet from lbrynet
-Set LBRYumWallet.config upon initialization, fixes attribute error

Shutdown fixes

---

CHANGELOG.md
lbrynet/lbrynet_daemon/Daemon.py

add force option to API command "resolve" to ignore cache, need this for testing

Add force option to resolve

---

CHANGELOG.md
lbrynet/lbrynet_daemon/Publisher.py

Check for file, and that file size is not zero before publishing

add ispath, and file size check before publishing

---

CHANGELOG.md
lbrynet/lbrynet_daemon/Daemon.py

deprecating old fee format in publish, so throw relevant exception for the old format

Add check for old fee format and throw releveant exception

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/lbrynet_daemon/Daemon.py
lbrynet/lbrynet_daemon/Publisher.py
tests/unit/core/test_Wallet.py

Add claim address as an argument to publish API command using lbryum claim_addr parameter.

Add claim address as an option to publish

---

CHANGELOG.md
lbrynet/lbrynet_daemon/Daemon.py

Add message for Insufficient Funds exception. 
before: http://prntscr.com/fhlde1
after http://prntscr.com/fhlcsu
reference issues:  
* https://github.com/lbryio/lbry/issues/673 
* https://github.com/lbryio/lbry-app/issues/27
* https://github.com/lbryio/lbry-app/issues/216

add message for exception so that app can render

---

CHANGELOG.md
lbrynet/core/BlobManager.py

https://github.com/lbryio/lbry/issues/527
https://github.com/lbryio/lbry/issues/675

fix blob manager db race condition

---

CHANGELOG.md
lbrynet/core/Error.py
lbrynet/core/Wallet.py
lbrynet/lbrynet_daemon/Daemon.py
requirements.txt
setup.py
tests/unit/lbrynet_daemon/test_Daemon.py

Goes with https://github.com/lbryio/lbry/pull/652 and https://github.com/lbryio/lbryum/pull/103

Batched uri resolution

---

lbrynet/lbrynet_daemon/Daemon.py

Just removing this unused function add_stream() from Daemon

remove unused add_stream() function from Daemon

---

CHANGELOG.md
lbrynet/lbrynet_daemon/Daemon.py

Typo in docstring
Fixes https://github.com/lbryio/lbry/issues/714

Fix support typo fixes #741

---

CHANGELOG.md
lbrynet/conf.py

The default max_key_fee value is increased to US$ 50.
Fixes #721

Increased max_key_fee

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/core/system_info.py
requirements.txt
setup.py

goes with https://github.com/lbryio/lbryum/pull/110

update lbryum imports

---

CHANGELOG.md
lbrynet/cryptstream/CryptBlob.py
tests/unit/cryptstream/test_cryptblob.py

Added unit tests and docstrings for CryptBlob.py,  the class responsible for encrypting and decrypting blobs.
No functionality changes.

Add docstring and unit test for CryptBlob.py

---

CHANGELOG.md
lbrynet/conf.py
lbrynet/daemon/Downloader.py
lbrynet/daemon/FileStreamer.py
lbrynet/daemon/Resources.py
lbrynet/daemon/daemon_scripts/Autofetcher.py

Revert "Fix default directories (fixes #574)"

---

CHANGELOG.md
lbrynet/core/Error.py
lbrynet/core/Wallet.py
lbrynet/daemon/Daemon.py

Fix https://github.com/lbryio/lbry/issues/765

raise error on negative point reservation

---

CHANGELOG.md
docs/cli.md
docs/index.md
lbrynet/conf.py
lbrynet/daemon/Daemon.py
lbrynet/daemon/Downloader.py
tests/unit/lbrynet_daemon/test_Downloader.py

duplicating https://github.com/lbryio/lbry/pull/761 on a branch to run full tests

Updated max_key_fee_setting

---

CHANGELOG.md
lbrynet/conf.py
lbrynet/core/log_support.py
lbrynet/daemon/Daemon.py
lbrynet/dht/protocol.py

Fixes https://github.com/lbryio/lbry/issues/774

Fix loggly

---

CHANGELOG.md
lbrynet/conf.py
lbrynet/daemon/Downloader.py
lbrynet/daemon/FileStreamer.py
lbrynet/daemon/Resources.py
lbrynet/daemon/daemon_scripts/Autofetcher.py
tests/unit/test_conf.py

#705 had a bug, so @kaykurokawa reverted it.
The functional change of this PR is the same. I've made an attempt at improving the big if-else statement, but imo it's kinda messy and quite a bit longer than the other version. 
Let me know if the other version is better, or if there's another way to structure this.
This also includes the two functions @kaykurokawa requested in the other PR.

Fix default directories

---

CHANGELOG.md
lbrynet/daemon/Daemon.py

remove [stream_info_cache.json](https://github.com/lbryio/lbry/issues/776)

remove stream info cache

---

CHANGELOG.md
lbrynet/daemon/Daemon.py
lbrynet/daemon/DaemonCLI.py
lbrynet/daemon/auth/server.py

Fix https://github.com/lbryio/lbry/issues/760

fix allowed_during_startup

---

CHANGELOG.md
lbrynet/conf.py
lbrynet/core/Error.py
tests/unit/test_conf.py

Opening branch on lbry repo to replace https://github.com/lbryio/lbry/pull/789
Added unit test in test_conf.py
rebased to master
LGTM

Added validation for currencies.

---

CHANGELOG.md
lbrynet/daemon/Daemon.py

Create a blob_announce API command for more granular ways to announce blobs for debugging purposes.

Better blob announce API command

---

CHANGELOG.md
lbrynet/daemon/DaemonCLI.py
tests/unit/lbrynet_daemon/test_DaemonCLI.py

Fix error when resolving an integer

---

docs/index.md

Updating `claim_new_support` documentation to add a bit more clarity to the name field.

Updating documentation for clarity

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/daemon/Daemon.py

Expose include tip info

---

tests/unit/lbryfilemanager/test_EncryptedFileCreator.py

Small fix to unit test,  need to yield for blob_manager.setup() otherwise test could proceed without setting up the blob manager database.

fix bug found in test_EncryptedFileCreator.py,

---

lbrynet/conf.py

Reflector2 points to the new cluster

Change to reflector2 in conf

---

LICENSE

The current LICENSE contains copyright with the year 2016, so I propose to update the year to 2017.

Update the year in the LICENSE

---

CHANGELOG.md
lbrynet/core/utils.py

Modified check_connection() to try bypassing DNS before giving up.

---

CHANGELOG.md
lbrynet/daemon/ExchangeRateManager.py

fixes https://github.com/lbryio/lbry/issues/984

less verbose exchange rate error

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/daemon/Daemon.py

goes with https://github.com/lbryio/lbryum/pull/167

Add channel import and export

---

CHANGELOG.md
build/build.ps1
build/build.sh
build/console.onefile.spec
build/zip_daemon.py
lbrynet/daemon/DaemonConsole.py
setup.py

add lbrynet-console

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/daemon/Daemon.py
lbrynet/daemon/auth/server.py
lbrynet/db_migrator/dbmigrator.py
lbrynet/db_migrator/migrate3to4.py
lbrynet/db_migrator/migrate4to5.py
lbrynet/file_manager/EncryptedFileManager.py
lbrynet/lbry_file/EncryptedFileMetadataManager.py
lbrynet/tests/functional/test_misc.py
lbrynet/tests/functional/test_streamify.py
lbrynet/tests/unit/lbryfile/test_EncryptedFileMetadataManager.py
lbrynet/tests/unit/lbryfilemanager/test_EncryptedFileManager.py

this re-adds `outpoint` to the results for `file_list`

consolidate lbry file db functions, save the outpoint upon download/publish

---

CHANGELOG.md
lbrynet/conf.py
lbrynet/daemon/DaemonControl.py

This PR adds the --conf CLI flag as requested in #1039 
The first commit in this PR also exists in the upnp-restructuring branch. I'll remove it form there if this PR gets merged first.

Add conf file flag

---

CHANGELOG.md
lbrynet/conf.py
lbrynet/core/Wallet.py
lbrynet/core/client/ConnectionManager.py
lbrynet/core/client/StreamProgressManager.py
lbrynet/cryptstream/client/CryptBlobHandler.py
lbrynet/cryptstream/client/CryptStreamDownloader.py
lbrynet/daemon/Daemon.py
lbrynet/daemon/Downloader.py
lbrynet/daemon/Publisher.py
lbrynet/file_manager/EncryptedFileDownloader.py
lbrynet/file_manager/EncryptedFileManager.py
lbrynet/lbry_file/EncryptedFileMetadataManager.py
lbrynet/lbry_file/client/EncryptedFileDownloader.py
lbrynet/reflector/server/server.py
lbrynet/tests/functional/test_streamify.py
lbrynet/tests/unit/lbryfile/client/test_EncryptedFileDownloader.py
lbrynet/tests/unit/lbrynet_daemon/test_Downloader.py

* Fixed the file manager startup being slow when handling thousands of files

Fix slow file manager startup on spee.ch

---

CHANGELOG.md
lbrynet/core/Wallet.py

The paytomany argument has been reworked so some changes are required to the daemon Wallet code https://github.com/lbryio/lbryum/pull/195

Fix to go with https://github.com/lbryio/lbryum/pull/195

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/daemon/Daemon.py

Also fixes documentation for `transaction_list`
Closes #946

Removed `include_tip_info` flag, to go with lbryum#183

---

CHANGELOG.md
lbrynet/daemon/Daemon.py

Related changlelog for the PR lbryio/lbryum#203

---

CHANGELOG.md
docs/cli.md
lbrynet/conf.py
lbrynet/core/Error.py
lbrynet/daemon/Daemon.py

Fixes for #930, see my comments in that issue.

Fix #930 "Improper CLI parsing of settings_set"

---

CHANGELOG.md
lbrynet/daemon/Daemon.py

Jeremy1026 add new exception

---

CHANGELOG.md
lbrynet/core/StreamDescriptor.py
lbrynet/cryptstream/CryptStreamCreator.py
lbrynet/tests/unit/lbryfilemanager/test_EncryptedFileCreator.py

fixes https://github.com/lbryio/lbry/issues/1124

Fix incorrect blob_num of the stream terminator blob for created streams

---

CHANGELOG.md
lbrynet/daemon/Daemon.py

fixes https://github.com/lbryio/lbry/issues/895

Fix blob_list errors and incorrect results

---

CHANGELOG.md
lbrynet/core/Wallet.py
lbrynet/daemon/Daemon.py

Error cleanly when claiming a new channel with exact or higher amount than balance

---

CHANGELOG.md
lbrynet/daemon/Daemon.py
lbrynet/daemon/DaemonCLI.py
lbrynet/daemon/DaemonControl.py
lbrynet/daemon/auth/auth.py
lbrynet/daemon/auth/client.py
lbrynet/daemon/auth/server.py
lbrynet/daemon/auth/util.py

-add explanation of daemon authentication to AuthJSONRPCServer docstring
-remove auth_required decorator, use auth for all api methods if use_authentication is true

fix lbrynet-cli when using authentication

---

CHANGELOG.md
lbrynet/daemon/Daemon.py
lbrynet/database/migrator/dbmigrator.py
lbrynet/database/migrator/migrate8to9.py
lbrynet/database/storage.py
lbrynet/file_manager/EncryptedFileDownloader.py
lbrynet/file_manager/EncryptedFileManager.py
lbrynet/tests/unit/database/test_SQLiteStorage.py

* bypass stream validation when no migration occurred
* add batching to supports and test it
* batch-start the daemon
Feel free to pick changes in or out, I can also split the PR if necessary.

#1193 - bypass validation out of migration and batch start the client

---

CHANGELOG.md
lbrynet/database/storage.py
lbrynet/tests/unit/database/test_SQLiteStorage.py

This should impact creation of large streams as it reduces the queries made while saving each blob. Mostly for big files such as videos, but it's still only a refactor.

refactor: simplify add_completed_blob + changelog

---

CHANGELOG.md
lbrynet/database/storage.py

fixes https://github.com/lbryio/lbry/issues/1129

fix race condition when inserting a blob to the database

---

CHANGELOG.md
lbrynet/daemon/Publisher.py

https://github.com/lbryio/lbry/issues/1165

fix database error when updating a claim that we don't have a file for

---

.appveyor.yml
CHANGELOG.md
lbrynet/core/client/BlobRequester.py
lbrynet/core/client/ClientProtocol.py

fixes https://github.com/lbryio/lbry/issues/950

fix blob client protocol not tearing itself down properly after a failure

---

CHANGELOG.md
lbrynet/core/Wallet.py

fixes https://github.com/lbryio/lbry/issues/1245

fix wallet startup locking up if a lbryumx server is unavailable

---

CHANGELOG.md
lbrynet/daemon/Daemon.py

fixes https://github.com/lbryio/lbry/issues/1172

fix download being stopped if the sd blob downloaded and data did not start within the timeout

---

INSTALL.md
README.md

Started to standardize the README.md file.

---

CHANGELOG.md
lbrynet/daemon/Daemon.py

this allows directly pinging a peer without first doing an iterative find

add address and port arguments to peer_ping

---

CHANGELOG.md
lbrynet/daemon/Daemon.py

Check addresses earlier on publishing

---

CHANGELOG.md
lbrynet/daemon/Components.py
lbrynet/daemon/Daemon.py
lbrynet/dht/node.py
lbrynet/dht/protocol.py
setup.py

fixes https://github.com/lbryio/lbry/issues/1338 and https://github.com/lbryio/lbry/issues/1341

fix upnp port setup

---

.travis.yml
lbrynet/dht/contact.py
lbrynet/dht/iterativefind.py
lbrynet/dht/kbucket.py
lbrynet/dht/node.py
lbrynet/dht/protocol.py
tests/functional/dht/dht_test_environment.py
tests/functional/dht/mock_transport.py
tests/functional/dht/test_bootstrap_network.py
tests/unit/dht/test_contact.py

Functional test suite hangs somehow. Opening this PR so Jack can take a look.
**Don't merge yet**

DHT fixes from review and an attempt at removing hashing and equals

---

lbrynet/daemon/Daemon.py
lbrynet/wallet/ledger.py
lbrynet/wallet/manager.py
lbrynet/wallet/network.py
lbrynet/wallet/resolve.py

- block_show using block hash
- block_show using height
- claim_show from claim_id
- claim_show from outpoint

Fix some commands

---

lbrynet/daemon/Daemon.py

fail graceful when get is called on inexistent URI

---

lbrynet/daemon/Daemon.py

remove file_status flag and fix reference typo

---

lbrynet/daemon/Daemon.py

fixes #1447
Somehow its not always converting from str. There may be a better way to do this, but I'm opening this PR to let it clear that this is the issue behind 1447

explicitly convert page and page_size to int

---

lbrynet/core/system_info.py

supress git version print statement to debug

---

lbrynet/daemon/Daemon.py
lbrynet/wallet/account.py
lbrynet/wallet/database.py
lbrynet/wallet/manager.py
tests/integration/wallet/test_commands.py

New wallet claim abandon command

---

lbrynet/wallet/manager.py
lbrynet/wallet/network.py

adds get_claims_for_name

---

scripts/hook-coincurve.py
scripts/wine_build.sh

add a pyinstaller hook for coincurve

---

docs/api.json
lbrynet/daemon/Daemon.py
scripts/generate_json_api.py

also fixed issues reported by @osilkin98 in https://github.com/lbryio/lbry/pull/1469 and regenerated `api.json`

switched all --account args to --account_id

---

lbrynet/daemon/Daemon.py
lbrynet/wallet/manager.py
tests/unit/core/test_Wallet.py

-add `account_lock`
requires https://github.com/lbryio/torba/pull/10

Fix account_encrypt, account_decrypt, and account_unlock

---

lbrynet/daemon/auth/server.py
tests/integration/cli/test_cli.py
tests/integration/wallet/test_commands.py

send startup event right after setup

---

lbrynet/dht/contact.py
lbrynet/dht/node.py
lbrynet/dht/protocol.py
tests/functional/dht/test_store.py

This should improve #1446 long term and so far is the only thing doable on that issue.

refresh and nullify DHT tokens where appropriate

---

lbrynet/dht/node.py
lbrynet/dht/protocol.py
tests/functional/dht/dht_test_environment.py

closes #1439 
--- this is being tested on a node that crashes often, but you can also try `sys.setrecursionlimit(150)` (default is 1000) and run dht tests.

remove semaphore from ping queue

---

lbrynet/daemon/Components.py
lbrynet/wallet/manager.py

migrate addresses before starting the migrated wallet

---

lbrynet/wallet/account.py
lbrynet/wallet/ledger.py

set wallet max_gap after sync

---

lbrynet/wallet/ledger.py

report balance and summary on startup

---

INSTALL.md

Update macOS naming

---

docs/404.html

added alt text

---

.travis.yml
lbrynet/daemon/ComponentManager.py
lbrynet/daemon/Daemon.py
lbrynet/daemon/Downloader.py
lbrynet/daemon/json_response_encoder.py
lbrynet/database/storage.py
lbrynet/wallet/__init__.py
lbrynet/wallet/account.py
lbrynet/wallet/claim_proofs.py
lbrynet/wallet/database.py
lbrynet/wallet/dewies.py
lbrynet/wallet/header.py
lbrynet/wallet/ledger.py
lbrynet/wallet/manager.py
lbrynet/wallet/network.py
lbrynet/wallet/script.py
lbrynet/wallet/transaction.py
setup.py
tests/integration/wallet/test_commands.py
tests/integration/wallet/test_transactions.py
tests/unit/lbrynet_daemon/test_Daemon.py
tests/unit/wallet/test_account.py
tests/unit/wallet/test_headers.py
tests/unit/wallet/test_ledger.py
tests/unit/wallet/test_transaction.py
tox.ini

channel not a claim bug

---

lbrynet/schema/Makefile

adds a makefile to update proto from types repo

makefile for using types repo

---

lbrynet/extras/wallet/ledger.py

add balance to startup report

---

lbrynet/extras/daemon/Daemon.py
lbrynet/extras/wallet/account.py
lbrynet/extras/wallet/manager.py
lbrynet/extras/wallet/transaction.py
tests/integration/wallet/test_commands.py
tox.ini

tip and supports extended integration tests and related fixes

---

lbrynet/extras/cli.py

Better help message instructions

---

lbrynet/extras/daemon/storage.py

fix query for windows (999 vars limit)

---

lbrynet/extras/wallet/resolve.py

await missing on resolve.py

---

lbrynet/extras/daemon/Components.py

fixed #1616

---

lbrynet/extras/wallet/resolve.py

helper to log and handle #1611

log and handle misformed claims from #1611

---

lbrynet/extras/daemon/Daemon.py

fix mistake code

---

lbrynet/extras/daemon/auth/factory.py
lbrynet/extras/daemon/auth/server.py

fixes https://github.com/lbryio/lbry/issues/1624

don't create ssl/auth keys if both are disabled

---

README.md

User can now more easily find documentation on daemon configuration and ports.

adds daemon config to and updates links in readme

---

lbrynet/extras/daemon/Daemon.py
lbrynet/extras/wallet/dewies.py
lbrynet/extras/wallet/manager.py
tests/integration/wallet/test_commands.py
tests/unit/wallet/test_ledger.py
tox.ini

Claim send to address fixes

---

.travis.yml
lbrynet/extras/daemon/Daemon.py
lbrynet/extras/wallet/account.py
scripts/wine_build.sh
setup.py
tox.ini

+ jsonrpc_account_send

---

.travis.yml

test mac build, do not merge

---

lbrynet/extras/wallet/manager.py
lbrynet/extras/wallet/transaction.py
tests/integration/wallet/test_commands.py
tox.ini

remove fees from value, abandon is positive

---

lbrynet/extras/wallet/manager.py

fixes https://github.com/lbryio/lbry/issues/1573

unlock wallet after encrypting it

---

lbrynet/extras/daemon/storage.py
lbrynet/extras/wallet/dewies.py
lbrynet/extras/wallet/manager.py
lbrynet/extras/wallet/resolve.py
tests/integration/wallet/test_commands.py
tests/unit/database/test_SQLiteStorage.py

fixes https://github.com/lbryio/lbry/compare/fix-1674

fix int too large to convert to integer when updating claim

---

lbrynet/conf.py

Added lbrynet4 and comments on server location.
Adding new DHT seed node
New server in place 
Improvement

added `lbrynet4.lbry.io` to list of default DHT nodes

---

lbrynet/extras/wallet/server/coin.py
scripts/Dockerfile.wallet_server

@nikooo777 is testing it, so I added as reviewer. This change should also provide a way to create docker images for production releases.

add LBRY `testnet` support to wallet SPV server

---

lbrynet/extras/daemon/migrator/migrate5to6.py

fixed database migration (5 to 6) encoding

---

.travis.yml
lbrynet/extras/daemon/Daemon.py
lbrynet/extras/daemon/Publisher.py
lbrynet/extras/reflector/client/blob.py
lbrynet/extras/reflector/reupload.py
lbrynet/p2p/SinglePeerDownloader.py

30 5 fixes

---

lbrynet/conf.py

fix download directory creation

---

scripts/download_blob_from_peer.py

rename lbnyum_wallet_dir to wallet_dir

---

lbrynet/extras/daemon/Daemon.py

There was some confusion about this on Slack.

added note that wallet needs to be unlocked to decrypt

---

lbrynet/blob_exchange/server.py
lbrynet/dht/blob_announcer.py
lbrynet/dht/node.py
lbrynet/dht/protocol/iterative_find.py
lbrynet/dht/protocol/protocol.py
lbrynet/extras/daemon/Daemon.py
lbrynet/extras/daemon/storage.py
lbrynet/stream/assembler.py
lbrynet/stream/managed_stream.py
lbrynet/stream/stream_manager.py

- fix restarting a finished / deleted file
- adds `blobs_remaining` and `blobs_in_stream` arguments and response fields to `file_list`
- update `file_list` doc string

Reassemble when deleted from downloads

---

lbrynet/conf.py
lbrynet/stream/reflector/client.py
lbrynet/stream/stream_manager.py

adds `concurrent_reflector_uploads` setting to config

add re-reflect task to stream manager, add concurrent_reflector_uploads to config

---

lbrynet/extras/daemon/Daemon.py

format error dict on get

---

lbrynet/stream/assembler.py
lbrynet/stream/downloader.py
lbrynet/stream/managed_stream.py
lbrynet/stream/stream_manager.py
tests/integration/test_file_commands.py

- file path not being updated on file list after resuming downloads
- resume if DHT is disabled
- fix bug where resume doesnt complete downloads

Fix resuming downloads bugs on startup

---

lbrynet/stream/assembler.py
lbrynet/stream/stream_manager.py
tests/integration/test_file_commands.py
tests/unit/stream/test_assembler.py

Stop on data blobs timeout, allowing get to retry

---

lbrynet/blob/blob_file.py
lbrynet/blob/blob_manager.py
lbrynet/extras/daemon/storage.py
lbrynet/stream/stream_manager.py
tests/integration/test_file_commands.py

fixes https://github.com/lbryio/lbry/issues/1897

Faster file delete

---

lbrynet/extras/daemon/mime_types.py
tests/unit/lbrynet_daemon/test_mime_types.py

The rest of our extensions don't have a dot. Also, strip off any characters and lowercase it to be safe.

fix application/x-ext mime types

---

lbrynet/extras/daemon/Daemon.py

fixes https://github.com/lbryio/lbry/issues/1930

Fix blob_list for sd_hash including stream terminator

---

tests/unit/lbrynet_daemon/test_Daemon.py

remove invalid reflector_component test config

---

lbrynet/blob_exchange/client.py
lbrynet/blob_exchange/downloader.py
tests/integration/test_file_commands.py

Unban peers if no more peers to try and 10 seconds passed

---

lbrynet/dht/protocol/routing_table.py
tests/unit/dht/routing/test_routing_table.py

fixes range_min and range_max of a KBucket mistakenly bounding the node id of a peer rather than the distance from the local node id to the peer node id

fix KBucket.key_in_range

---

setup.py

pin jsonschema version to 2.6.0

---

lbrynet/extras/cli.py

handle sigint

---

.travis.yml

should only build for master after merge. This makes outside PRs fail

fix travis not to build wallet on PR

---

lbrynet/wallet/server/coin.py

update wallet server public/private hash config

---

scripts/time_to_first_byte.py

time to first byte script

---

INSTALL.md

Didn't need to install any build tools
Also, venv commands are a bit different.

update install for windows

---

.gitignore
lbrynet/extras/daemon/Daemon.py

Fixes typos and prevents `.DS_Store` files from being committed to the repo.
Developer confusion.

Typo fixes and updated gitignore

---

lbrynet/extras/daemon/Daemon.py
lbrynet/extras/daemon/storage.py
lbrynet/wallet/ledger.py
lbrynet/wallet/resolve.py
tests/unit/database/test_SQLiteStorage.py

temporary fix while the wallet server is being reworked on another branch

cache and share txs fetches while validating concurrently on batches

---

lbrynet/wallet/account.py
tests/unit/wallet/test_account.py

fixes https://github.com/lbryio/lbry/issues/2078

fixed bug where lbrynet failed to start with single-key accounts in the wallet

---

lbrynet/schema/mime_types.py

fix incorrect media-type of .cbr archives

---

lbrynet/blob/blob_info.py
lbrynet/blob_exchange/client.py
lbrynet/blob_exchange/downloader.py
lbrynet/dht/peer.py
lbrynet/extras/daemon/Daemon.py
lbrynet/stream/descriptor.py
lbrynet/stream/downloader.py
lbrynet/stream/managed_stream.py
lbrynet/stream/stream_manager.py
lbrynet/testcase.py
tests/integration/test_cli.py
tests/integration/test_streaming.py
tests/integration/test_sync.py
tests/unit/stream/test_managed_stream.py
tests/unit/stream/test_stream_manager.py

https://github.com/lbryio/lbry/issues/2034
* fixes ``` logging for uri being started is missing in stream mode.```
* fixes ``` written bytes shows null right after a file save. Subsequent file list has them correctly.```

Streaming bug fixes

---

lbrynet/conf.py

Address https://github.com/lbryio/lbry/issues/2016 for timeout issues until we can deploy more reflector peers. Would like @jackrobison to review.

Adjust default max_connections_per_download and peer_connect_timeout settings

---

example_daemon_settings.yml
lbrynet/conf.py

* add missing wallet server
* switch to .com domain

Add missing wallet server

---

lbrynet/utils.py
lbrynet/wallet/resolve.py
tests/integration/test_resolve_command.py

fixes part of https://github.com/lbryio/lbry/issues/2137

Fix resolve internals caching and persisting errors

---

INSTALL.md
setup.py

when running `lbrynet` command, it checks the min python version and errors if python is not compatible
version before python 3.7 do not check that the version is too low when you `pip install`

enforce min python version

---

.travis.yml
lbrynet/build_type.py
scripts/set_build.py
scripts/wine_build.sh
setup.py
tox.ini

- adds BUILD_COMMIT to lbrynet.build_type

improve set_build.py, pin torba version

---

lbrynet/schema/mime_types.py

Some YT downloaded videos will be MKV format from the backup downloader. 

add MKV to mime types

---

lbrynet/extras/daemon/Daemon.py
lbrynet/extras/daemon/comment_client.py
tests/integration/test_comment_commands.py
tests/unit/comments/test_comment_signing.py
tests/unit/wallet/test_schema_signing.py

Implements Comment Signing & Validating in the SDK

---

.idea/.gitignore
.idea/lbry-sdk.iml
.travis.yml
lbry/lbry/conf.py
lbry/lbry/wallet/manager.py
lbry/tests/unit/test_conf.py
torba/tests/client_tests/unit/test_coinselection.py
torba/torba/client/baseledger.py
torba/torba/client/coinselection.py

Adds coin selection strategy config value so niko can upload

add coin selection strategy config

---

lbry/lbry/extras/daemon/comment_client.py

Fix certificate errors
Need to test locally still...

use utils.aiohttp for comments

---

lbry/lbry/extras/daemon/Daemon.py

There may be others, but these are the obvious ones.

str > list for a few fields

---

lbry/scripts/release.py

since we're not doing RCs anymore, I simplified the release script. Changes:
- only options for release are `major`, `minor`, or `micro`.
- instead of `--dry-run`, dry running is the default and you have to `--confirm` to actually do the release.
- no more `--test` flag. instead pass `test` as the action (instead of `micro`, for example)

remove RCs from release tool

---

lbry/tests/integration/test_wallet_server_sessions.py
torba/torba/client/basenetwork.py
torba/torba/orchstr8/node.py
torba/torba/server/daemon.py
torba/torba/server/server.py
torba/torba/server/session.py

torba client networking: improve network timeout handling and fix spurious logs on shutdown

---

lbry/lbry/blob/blob_manager.py
lbry/lbry/stream/managed_stream.py
lbry/tests/unit/blob/test_blob_manager.py
lbry/tests/unit/stream/test_managed_stream.py

set file status to completed only when all bytes were written

---

lbry/lbry/extras/daemon/Daemon.py

Quick fixes to `jsonrpc_comment` functions, shouldn't change functionality.

Fixes comment docs & adds wallet component requirement on comment funcs

---

lbry/setup.py

https://github.com/lbryio/aioupnp/pull/15

bump `aioupnp` requirement to 0.0.14, fixes upnp errors blocking startup

---

lbry/lbry/extras/daemon/Components.py
lbry/lbry/extras/daemon/Daemon.py
lbry/lbry/extras/daemon/exchange_rate_manager.py
lbry/lbry/extras/daemon/loggly_handler.py
lbry/lbry/utils.py

-fixes exchange rate manager erroring when offline
-fixes loggly and internet connectivity check erroring when offline
-fixes wallet `status` silently breaking when offline or before a server is connected

Fix misc errors when going offline/online

---

torba/torba/client/basenetwork.py

Those are annoying exceptions and very hard to happen cases. One of them is what could be causing #2445 however its very hard to reproduce and test. (you need to switch into a server about to go down, but the timing is very tight as some requests needs to go through while others doesn't)

bugfixes for wallet client network rare edge case where it switches to a server about to go down

---

INSTALL.md

Added missing punctuation and changed existing to more fitting one.

Punctuation

---

lbry/lbry/connection_manager.py

This fixes the currenty incorrect counting of total bytes sent / received in connection manager.
fixes #2410

Fix incorrect counting of total bytes sent / received

---

lbry/lbry/conf.py
lbry/lbry/extras/cli.py
lbry/lbry/extras/daemon/Components.py
lbry/lbry/extras/daemon/migrator/dbmigrator.py
lbry/lbry/wallet/server/coin.py
lbry/tests/integration/test_cli.py
lbry/tests/unit/test_cli.py
torba/torba/client/cli.py
torba/torba/orchstr8/cli.py

This fixes a bug I caused when logging state was modified during a test, and not restored. Fixed by injecting the logging module into the tested function.

fix logging tests

---

torba/torba/client/wallet.py

fixes https://github.com/lbryio/lbry-sdk/issues/2576

don't error if blank password was set previously

---

lbry/lbry/wallet/server/db/reader.py
lbry/tests/integration/test_resolve_command.py
lbry/tests/unit/wallet/server/test_sqldb.py

fixes https://github.com/lbryio/lbry-sdk/issues/2448

fix bug with resolve and conflicting `claim_id` segments

---

lbry/lbry/wallet/server/db/writer.py
lbry/tests/unit/wallet/server/test_sqldb.py

fix for wallet server bug related to changing the channel of a stream

---

lbry/lbry/extras/daemon/Components.py
lbry/lbry/extras/daemon/Daemon.py
lbry/lbry/extras/daemon/json_response_encoder.py
lbry/lbry/extras/daemon/migrator/dbmigrator.py
lbry/lbry/extras/daemon/migrator/migrate11to12.py
lbry/lbry/extras/daemon/storage.py
lbry/lbry/stream/managed_stream.py
lbry/lbry/stream/stream_manager.py

adds `added_on` field to files

---

lbry/lbry/extras/cli.py
lbry/lbry/extras/daemon/Daemon.py
lbry/lbry/extras/daemon/loggly_handler.py
lbry/lbry/testcase.py
lbry/tests/integration/test_cli.py
lbry/tests/integration/test_resolve_command.py
lbry/tests/unit/test_cli.py
torba/torba/client/baseledger.py
torba/torba/tasks.py

Add a unit test to cover the case where the user performs a keyboard interrupt from the CLI.

added unit test for keyboard interrupt occurring on startup

---

lbry/lbry/extras/daemon/Components.py

Adds 
known_servers: int
available_servers: int 
to wallet status.
Also changes
connected_servers: {...}
to 
servers: {
[
host, port, latency, available
],
}

adds wallet server information to `status` command

---

lbry/lbry/dht/node.py

-add comments
-rename functions to be more descriptive of what they do

Fix UDP ping port in blob peer accumulator

---

lbry/lbry/wallet/account.py
lbry/lbry/wallet/database.py
lbry/lbry/wallet/ledger.py
lbry/tests/integration/test_purchase_command.py

`utxo list` includes purchases of your claims

---

.gitlab-ci.yml
.travis.yml

also disables travis asset uploading
merge when ready
ref #2469

upload assets from gitlab CI to github on a tagged release

---

lbry/lbry/extras/daemon/Daemon.py

adds command call logging for all create/update/abandon commands

---

lbry/lbry/wallet/server/db/writer.py
lbry/tests/unit/wallet/server/test_sqldb.py

fixes #2486
fixes #2343
fixes #2628

fixes for various edge cases where claim (and support) creation, updating and abandoning is occuring in the same block

---

lbry/lbry/wallet/server/db/writer.py

re-sync in progress
will use the PR for sharing things I try for now

enable WAL on wallet server

---

lbry/extras/daemon/components.py
setup.py

fixes https://github.com/lbryio/lbry-sdk/issues/2712

update aioupnp requirement to 0.0.17

---

lbry/wallet/server/db/trending.py
lbry/wallet/server/db/trending/__init__.py
lbry/wallet/server/db/writer.py
tests/unit/wallet/server/test_sqldb.py

Reverts lbryio/lbry-sdk#2750
The server is unable to start up after having been three blocks behind.

Revert "configurable trending algorithms"

---

.gitignore
lbry/extras/daemon/daemon.py
lbry/wallet/server/db/reader.py
lbry/wallet/server/db/writer.py
tests/integration/blockchain/test_claim_commands.py

Tests fail when they should, and work when they should.
The index is a best guess.

add duration to claim search params

---

lbry/wallet/server/db/trending/ar.py

Bugfix to AR trending to allow resync from zero

fixed initialization problem with ar trending algorithm

---

LICENSE

update copyright year in license

---

lbry/blob/blob_file.py
lbry/blob_exchange/server.py
lbry/extras/daemon/daemon.py
lbry/stream/stream_manager.py
tests/unit/blob_exchange/test_transfer_blob.py

-remove unnecessary db call in stream_update (fixes https://github.com/lbryio/lbry-sdk/issues/2368)

cancel reflector uploads upon file delete

---

lbry/file_analysis.py
lbry/wallet/orchstr8/node.py

fix video analysis error

---

lbry/wallet/database.py
lbry/wallet/server/db/common.py
lbry/wallet/server/db/reader.py
lbry/wallet/server/db/writer.py
setup.cfg
tests/integration/blockchain/test_claim_commands.py
tests/unit/wallet/test_database.py

SQL generation fix to handle IN operation for one value lists

---

lbry/wallet/server/block_processor.py

fixes https://github.com/lbryio/lbry-sdk/issues/2746

Fix race condition setting/clearing the claim_search and resolve cache

---

lbry/wallet/ledger.py
tests/integration/blockchain/test_claim_commands.py

fixes https://github.com/lbryio/lbry-sdk/issues/2802

fix claim apis failing with --resolve if no claims are present

---

lbry/conf.py
tests/unit/stream/test_stream_manager.py
tests/unit/test_cli.py

Consistent with privacy stance, defaulting sharing to false.

change default privacy setting

---

lbry/extras/daemon/daemon.py
lbry/file_analysis.py

fixes https://github.com/lbryio/lbry-sdk/issues/2809

add `ffmpeg_find` api to check ffmpeg installation status, don't recheck for ffmpeg in `status`

---

lbry/testcase.py
lbry/wallet/server/db/reader.py
tests/integration/blockchain/test_claim_commands.py
tests/integration/blockchain/test_purchase_command.py
tests/integration/blockchain/test_resolve_command.py
tests/integration/other/test_chris45.py

`claim_search --not_channel_ids` excludes the channel itself and not just claims in the channel

---

lbry/schema/result.py
lbry/testcase.py
lbry/wallet/server/db/reader.py
tests/integration/blockchain/test_claim_commands.py

reposts inherit the tags of the original claim, filtered/blocked claims cause their reposts to also be filtered/blocked

---

lbry/extras/daemon/json_response_encoder.py
lbry/testcase.py
lbry/wallet/database.py
lbry/wallet/ledger.py
lbry/wallet/transaction.py
tests/integration/blockchain/test_claim_commands.py

added `is_spent` attribute to transaction outputs

---

lbry/file_analysis.py

that was introduced in this morning's merge.
Additional reference material: https://stackoverflow.com/questions/33560364/python-windows-parsing-command-lines-with-shlex

fixed issue with shell parsing on Windows

---

lbry/extras/daemon/daemon.py
lbry/wallet/database.py
tests/integration/blockchain/test_claim_commands.py

added `--include_received_tips` to `claim_list` and `txo_list` commands

---

lbry/conf.py

default to 1080P for anything higher than 1080P

---

lbry/testcase.py
lbry/wallet/ledger.py
lbry/wallet/orchstr8/node.py
tests/integration/blockchain/test_resolve_command.py
tests/integration/blockchain/test_sync.py

last PR removed waiting for sync but entirely instead of just for headers.

wait for tx sync to finish but not header sync

---

lbry/wallet/ledger.py
lbry/wallet/rpc/session.py
lbry/wallet/server/prometheus.py
tests/integration/blockchain/test_claim_commands.py

fixes https://github.com/lbryio/lbry-sdk/issues/2907

Fix connection to wallet server breaking upon giant resolve requests

---

.github/workflows/main.yml
lbry/extras/daemon/daemon.py
tests/integration/other/test_comment_commands.py

`comment_hide` now returns lists of `comment_ids` that are both `hidden` and `visible`.
The combined lists contain all the `comment_ids` passed into the parameters

Comment_hide update

---

lbry/extras/daemon/daemon.py
tests/integration/blockchain/test_claim_commands.py

fix for `claim_list` incorrectly handling `--is_spent` flag

---

lbry/extras/daemon/daemon.py
lbry/file/file_manager.py
lbry/stream/managed_stream.py
lbry/stream/stream_manager.py

fix node not being set on the downloader in some cases

---

lbry/extras/daemon/daemon.py
lbry/wallet/account.py

fixed sync'ing issues related to `modified_on` timestamps having varying floating value between OSes

---

lbry/extras/daemon/daemon.py

switch default for include replies to false
Breaking: Apps will need to include the --include_replies flag to continue using it as normal until we switch to the new system.

allow faster comment retrieval

---

lbry/wallet/database.py
lbry/wallet/ledger.py

fixes https://github.com/lbryio/lbry-sdk/issues/3007

release reserved outputs on startup

---

lbry/wallet/wallet.py
tests/unit/wallet/test_wallet.py

recover from state where wallet is set to encrypt but not encrypted and no password given

---

lbry/wallet/database.py

use WAL_CHECKPOINT explicitly on close to ensure there is no write ahead log remaining when shutting down the client database.

Ensure no client .wal files remain on shutdown

---

lbry/db/queries/address.py
lbry/db/query_context.py
tests/unit/wallet/test_account.py

take sqlite variable limit into account and batch key creation under it

---

lbry/extras/daemon/daemon.py
lbry/wallet/database.py
tests/integration/blockchain/test_claim_commands.py

added support for `--not_channel_id` to `txo_list` commands

---

lbry/file/file_manager.py
tests/integration/blockchain/test_purchase_command.py
tests/integration/datanetwork/test_file_commands.py

owner of priced content no longer forced to purchase their own content when calling `get`

---

lbry/wallet/ledger.py
tests/integration/blockchain/test_claim_commands.py

`txo_list --resolve` now works for signed supports by resolving the signing channel

---

lbry/extras/daemon/exchange_rate_manager.py
lbry/testcase.py
lbry/utils.py
tests/integration/other/test_exchange_rate_manager.py
tests/unit/lbrynet_daemon/test_exchange_rate_manager.py

converting from USD or BTC to LBC is now done via several exchange rate providers: Bittrex, Cryptonator, CoinEx, hotbit and UPbit

---

tests/integration/blockchain/test_purchase_command.py

ensures content purchase fails appropriately when exchange rate is not available

---

lbry/extras/daemon/exchange_rate_manager.py
tests/unit/lbrynet_daemon/test_exchange_rate_manager.py

use median exchange rate when several exchange rates are available

---

lbry/extras/daemon/daemon.py
lbry/wallet/server/db/common.py
lbry/wallet/server/db/writer.py
tests/integration/blockchain/test_claim_commands.py

added support to `claim_search` for filtering collections via `--claim_type=collection`

---

lbry/wallet/network.py

fixes stalling client reconnect issue

---

lbry/wallet/server/leveldb.py

partially addresses #3142 
see the test pasted into #3142 which was attempting to reproduce the bug without success
final fix will come in #3205

temporary fix for mempool sync failing during reorg

---

lbry/wallet/server/cli.py
lbry/wallet/server/db/elasticsearch/search.py
lbry/wallet/server/db/elasticsearch/sync.py
lbry/wallet/server/db/writer.py
lbry/wallet/server/env.py

this allows a hub to use a non-localhost elastic server

add ELASTIC_HOST and ELASTIC_PORT settings to hub

---

lbry/extras/daemon/daemon.py
tests/unit/lbrynet_daemon/test_allowed_origin.py

adding `Access-Control-*` headers in SDK HTTP responses and support for OPTIONS HTTP request

---

lbry/extras/daemon/daemon.py
lbry/wallet/account.py
lbry/wallet/database.py
lbry/wallet/ledger.py
tests/integration/blockchain/test_wallet_commands.py

improved performance of calculating the wallet balance

---

lbry/wallet/database.py
tests/integration/blockchain/test_claim_commands.py

pending claims ordered towards top in `claim_list`

---

lbry/wallet/database.py

migration specifically for upgrading from client db v1.5 to v1.6

---

lbry/wallet/server/db/elasticsearch/search.py
lbry/wallet/server/db/elasticsearch/sync.py
lbry/wallet/server/db/writer.py
tests/integration/blockchain/test_claim_commands.py

missing: simplify/unify sync with search on ES backend to remove duplicated code
fixes #3261, #3257

Fix bug for `has_source=True` hiding channel reposts

---

lbry/wallet/server/db/elasticsearch/search.py
lbry/wallet/server/db/elasticsearch/sync.py

-bump ES search index to version 1

add versioning to ES search index and automate resync on version bumps

---

INSTALL.md
Makefile

add Elasticsearch to Makefile and install docs

---

lbry/wallet/server/db/writer.py

this used to hold shared dictionaries for the multiprocessing readers, which are now deprecated. It makes the server spawn another process on startup, taking around 4-8G of RAM.

remove unused multiprocessing.Manager, decreasing hub memory usage significantly

---

lbry/extras/daemon/daemon.py
lbry/schema/README.md
lbry/schema/support.py
lbry/schema/types/v2/support_pb2.py
lbry/wallet/transaction.py
tests/integration/blockchain/test_claim_commands.py

Support with comments

---

scripts/example_update_es.py

add small example script showing how to read and update values to ES as we currently use it

---

docker/Dockerfile.web
docker/webconf.yaml

related to https://github.com/lbryio/lbrytv/issues/344 
as described in https://github.com/lbryio/lbry.tech/pull/354/files

add dockerfile for personal web sdk deployments

---

.gitlab-ci.yml
setup.py

Binary wheels for newer versions of Python, faster, type hints https://ofek.dev/coincurve/history/

Upgrade `coincurve` dependency

---

scripts/find_max_server_load.py
scripts/test_claim_search.py

Nothing special, just fixing the import in two scripts.
scripts/find_max_server_load.py
scripts/test_claim_search.py
```py
from lbry.wallet.network import ClientSession
```

Fix `ClientSession` import in two scripts

---

scripts/troubleshoot_p2p_and_dht_webservice.py

add script with web endpoints that can troubleshoot p2p/dht

---

lbry/extras/daemon/components.py
tests/unit/dht/test_node.py

Propagate external ip change from upnp component to dht protocol

---

lbry/wallet/server/db/elasticsearch/sync.py
lbry/wallet/server/db/writer.py
tests/integration/blockchain/test_claim_commands.py

part of #3377 
a follow-up will include all fields from leveldb branch

make reposts searchable by: stream_type, media_type, duration, fee_amount and fee_currency

---

.github/workflows/main.yml
lbry/blob/disk_space_manager.py
lbry/conf.py
lbry/extras/daemon/components.py
lbry/extras/daemon/daemon.py
lbry/testcase.py
tests/integration/datanetwork/test_file_commands.py
tests/unit/blob/test_disk_space_manager.py
tests/unit/components/test_component_manager.py
tests/unit/test_conf.py

disable the component in server environment: `disk_space`

ability to limit disk spaced used for blobs via `blob_storage_limit` setting (oldest blobs are deleted when disk space limit is reached)

---

lbry/wallet/server/block_processor.py
lbry/wallet/server/db/prefixes.py
lbry/wallet/server/leveldb.py
tests/integration/takeovers/test_resolve_command.py

https://github.com/lbryio/lbry-sdk/issues/3465

Fix duplicate trending score change and incorrect `effective_amount` in resolve/claim_search for non activated claims

---

scripts/dht_node.py

Dht script: export raw data as csv

---

lbry/wallet/manager.py

fee per name env var

---

lbry/wallet/server/leveldb.py
tests/integration/claims/test_claim_commands.py

Fix claims without source appearing on `stream_types` searches

---

lbry/conf.py

changes default coin selection strategy from standard to prefer_confirmed

---

lbry/wallet/database.py

`lbrynet address list --page=2` fails with an index error.

fix pagination with `address_list` command

---

lbry/extras/daemon/daemon.py
lbry/wallet/bip32.py
lbry/wallet/orchstr8/node.py
lbry/wallet/script.py
lbry/wallet/transaction.py
tests/integration/blockchain/test_account_commands.py
tests/unit/wallet/test_script.py
tests/unit/wallet/test_transaction.py

added `account_deposit` command which is able to deposit time locked transaction into wallet

---

lbry/extras/daemon/daemon.py
tests/integration/claims/test_claim_commands.py

reposts can have title, description and tags

---

lbry/extras/daemon/storage.py
tests/integration/datanetwork/test_file_commands.py

Add a check for `status` being `finished`, so we do not count pending/abandoned downloads.
closes #3617

do not consider pending blobs on disk space query

---

lbry/extras/daemon/daemon.py

migrate certificates after importing new account via `sync_apply`

---

lbry/extras/daemon/daemon.py
lbry/wallet/wallet.py
tests/unit/wallet/test_wallet.py

migrate key addresses on changed accounts after sync apply

---

.github/workflows/main.yml
lbry/extras/daemon/components.py
lbry/torrent/session.py
scripts/hook-libtorrent.py
setup.py
tests/integration/datanetwork/test_file_commands.py
tox.ini

linux binary works. mac and windows needs testing.
Testing:
- start SDK
- play or manually download `bigbuckbunny-torrent1`

use official libtorrent, fix tests, make it a normal dependency

---

lbry/testcase.py
lbry/wallet/wallet.py
setup.py
tests/integration/blockchain/test_wallet_commands.py
tests/integration/claims/test_claim_commands.py

Fixes #3660 
Fixes #3658 
Fixes #3662 
Also hub version is bumped to latest which includes a fix for: https://github.com/lbryio/hub/issues/92
Will remove 6a2246c088f8447860be1978c780210a3fcb0828 as it's a temporary change to allow push button testing.

Miscellaneous fixes for intermittent test failures

---

lbry/extras/daemon/json_response_encoder.py
lbry/stream/managed_stream.py
tests/unit/stream/test_managed_stream.py

Fallback name, suggested file name and mime type from claim if missing on sd blob

---

lbry/file/file_manager.py
tests/integration/datanetwork/test_file_commands.py

closes #3690 (the other bug isn't fixable on SDK side so far)

Fix claim fields fallback raising errors before download is saved on database

---

.github/workflows/main.yml
.github/workflows/release.yml

TEMP: Pin workflows to ubuntu-20.04 to work around missing ripemd160 issue.

---

lbry/conf.py

Added tracker and DHT from pigg.es as known DHT and tracker nodes.

Added tracker and dht from pigg.es
