lbryio/lbry-sdk

- lbrynet/__init__.py
- lbrynet/core/LBRYcrdWallet.py
- lbrynet/lbrynet_daemon/LBRYDaemon.py
- lbrynet/lbrynet_daemon/LBRYDaemonControl.py
- packaging/ubuntu/lbry
- packaging/ubuntu/lbry.desktop
- setup.py
-make is_lagging more meaningful - it is set to true after 90 seconds
with no progress, this is to stop slow but steady catchups from
triggering it
-prevent situation where repeated shutdowns before wallet catchup
results in never receiving first run credits
-fix settings to write new defaults that aren’t already in the
configuration file
-report log of startup sequence if upload_log set to true
-redirect /view?name=lbry to the main UI page. This is to make the ui
accessible from a lbry:// link on linux
> fix lagging indicator and improve diagnostics

- lbrynet/__init__.py
- lbrynet/core/LBRYcrdWallet.py
- lbrynet/lbryfilemanager/LBRYFileDownloader.py
- lbrynet/lbrynet_daemon/LBRYDaemon.py
- lbrynet/lbrynet_daemon/LBRYDaemonControl.py
-include lbry uri, claim txid, and claim value in lbry_file
-lbryum 2.6.0.4 returns what’s needed to write claim data to sqlite, fix lbrynet to make sure it doesnt store duplicates
-add waiting_for_credits to loading screen to force user to not try to download something before credits show up, a common source of timeout errors
-fix --wallet=lbrycrd , lbrycrdd should be run separately. added set_miner and get_miner_status commands
> more stream and file fixes

- .travis.yml
- packaging/ubuntu/ubuntu_package_setup.sh
The build on travis was the wrong size because it wasn't being built on 14.04!  I had a typo when specifying the distribution to use and so travis was falling back to 12.04
The file size looks more reasonable now:
```ls -l /home/travis/build/lbryio/lbry/lbrynet_0.2.5_amd64.deb
-rw-r--r-- 1 travis travis 10490736 Jun 10 06:43 /home/travis/build/lbryio/lbry/lbrynet_0.2.5_amd64.deb```
> Fix travis build

- packaging/osx/lbry-osx-app/setup_app.sh
The correct libgmp builds on travis so we don't need to swap it out anymore
> No longer swap libgmp

- .travis.yml
- packaging/osx/certs/.gitignore
- packaging/osx/lbry-osx-app/setup_app.py
- packaging/osx/lbry-osx-app/setup_app.sh
By default, Travis uses an old xcode and osx 10.9.
Also related:
- install framework version of python
- ensure unencrypted keys are never accidently added to repo
> Use a more up-to-date OSX version

- .travis.yml
- packaging/osx/lbry-osx-app/setup_app.sh
- packaging/travis/setup_osx.sh
Use python from python.org.
- py2app won't  included the system default in the app bundle
- brew's version of python links against brew's version of openssl - which doesn't get included in the bundle so it fails on a machine that doesn't have that version of openssl
> Fix OSX build issue with openssl

- packaging/ubuntu/ubuntu_package_setup.sh
Ran into a bug in make-deb that fails when there is utf-8 characters
in the git commit message. https://github.com/nylas/make-deb/issues/13.
I wrote a patch to fix the bug and am installing that version until the
make-deb maintainers incorporate it
> Use patched version of make-deb

- scripts/migrate_lbryum_to_lbrycrd.py
Exports the private keys out of the lbryum wallet, reformats them and imports them into lbrycrd.
Requires the lbrycrdd is already running and that lbrycrd-cli is on the path.
> script to migrate private keys to lbrycrd

- requirements.txt
Updating to protobuf-v3.0.0b3 because it
fixes a bug here https://github.com/google/protobuf/blob/e841bac4fcf47f809e089a70d5f84ac37b3883df/python/google/protobuf/internal/python_message.py#L59
where six.moves is not always available.
In particular, the system python on OSX has an old version of six
which is without six.moves.
> Update protobuf library

- .travis.yml
- packaging/osx/lbry-osx-app/setup_app.sh
pyobj was taking a long time; this change builds wheels and caches them.  Speeding up the build from 15 minutes to 5 minutes.
> Cache pyobjc

- .pylintrc
- lbrynet/lbrynet_daemon/LBRYDaemon.py
Nested functions are the devil, especially ones that
use variables from the outer scope. Refactoring
_download_name to use a helper class helps make
the scoping more explicit and will undoubtably
prevent bugs in the future.
I think this makes _download_name drastically more readable.
Also cleaned up some duplicated code and
made download_directory respect the passed in parameter
instead of being the default.
Fixes two bugs:
* os.dirname should be os.path.dirname
* the download_directory parameter was being ignored in the output
Refactorings:
Move parameter handling into its own function and
better use of the .get() function for dictionaries.
Early return on the failed checks is more readable.
The lambda function in the callback was long and
hard to read so moved it out.
> Refactor _download_name

- .travis.yml
- lbrynet/lbrynet_daemon/LBRYDaemon.py
- tests/lbrynet/lbrynet_daemon/test_LBRYDaemon.py
This commit supports steps 1 and 2 in the new workflow:
1. Change the logic in the daemon to check the github api for the latest release that is not a pre release
2. Change travis to mark all releases as pre release
3. When we are ready to stage a release we push a tag to master. Travis builds the packages and releases them
4. We manually check them
5. Remove the pre release mark when we are happy
> Updates the deployment process and the version check associated with it

- lbrynet/lbrynet_daemon/LBRYDaemonServer.py
This line is responsible for flooding the console with messages like
<_io.BytesIO object at 0x7f9e286e52f0>
> Remove print line

- lbrynet/dht/node.py
- lbrynet/dht/protocol.py
TimeoutError was outputting useless binary blobs.
I'm not sure if these log messages are even useful, but this change at least makes them readable.
> Have TimeoutError hexlify blobs

- lbrynet/core/log_support.py
- lbrynet/lbrynet_daemon/LBRYDaemon.py
- lbrynet/lbrynet_daemon/LBRYDaemonControl.py
- lbrynet/lbrynet_daemon/LBRYDaemonServer.py
- lbrynet/lbrynet_daemon/LBRYDownloader.py
- lbrynet/lbrynet_daemon/LBRYPublisher.py
- lbrynet/lbrynet_daemon/LBRYUIManager.py
Instead, move the responsibility to the main program. Also,
each module had the same, redundant setup.
> Fix: Log configuration should not happen when a module is imported

- lbrynet/lbrynet_daemon/LBRYUIManager.py
Don't merge this until https://github.com/lbryio/lbry-web-ui/pull/20 is merged and the files are properly on S3.
Tested with the current add-travis branch:
```
INFO:lbrynet.lbrynet_daemon.LBRYUIManager:Checking for updates for UI branch: add-travis
INFO:lbrynet.lbrynet_daemon.LBRYUIManager:UI updates available, checking if installation meets requirements
INFO:lbrynet.lbrynet_daemon.LBRYUIManager:Downloaded files for UI commit af553c6ac0e211c1988c8a3dc646c8f924df9c52
INFO:lbrynet.lbrynet_daemon.LBRYUIManager:Local version of lbrynet meets ui requirement
INFO:lbrynet.lbrynet_daemon.LBRYUIManager:Loaded UI update
INFO:lbrynet.lbrynet_daemon.LBRYDaemon:Platform: {"ip": "174.73.19.15", "python_version: ": "2.7.11", "os_system": "Darwin", "lbrynet_version: ": "0.3.6", "os_release": "15.5.0", …
```
> web-ui files are on S3 now

- lbrynet/conf.py
- lbrynet/core/log_support.py
- lbrynet/core/server/ServerRequestHandler.py
- lbrynet/lbrynet_daemon/LBRYDaemon.py
- lbrynet/lbrynet_daemon/LBRYDaemonControl.py
- requirements.txt
Adds a handler that streams log statements right to loggly.  Use a json formatter allows loggly to parse it much easier.  Tracebacks also show better.  Streaming the logs also means that its no longer all or nothing with the log depending on whether the shutdown sequence is able push the log.
The file logs still go to S3.
There are a couple other code clean-up commits mixed in here.  Sorry about that.
> Log to loggly

- lbrynet/lbrynet_daemon/LBRYDaemon.py
We need the output of `_wait_on_lbry_file`, so `deferedLater` is more appropriate then `callLater`
> replace callLater with deferLater

- lbrynet/lbrynet_daemon/LBRYDaemon.py
- lbrynet/lbrynet_daemon/LBRYDownloader.py
when GetStream timesout, it causes an error later on.  This instead raises an error.
Should actually do something when a timeout happens, but I'm not sure what.  This is at least better then it was.
> raise Exception on GetStream timeout

- lbrynet/core/LBRYWallet.py
This uses the exclude_claimtrietx option in lbryum pull request https://github.com/lbryio/lbryum/pull/30
Thus the balance should now be displayed as the available amount of credits, not used for any claim trie transactions (claim,support,update). 
This also fixes an incorrect use of the field 'unmatured' which would have resulted in some strange behaviors if you held some new coins (probably someone had to patch this in during the early stage of testing where they were testing with unmatured coins ).  
This patches to show the fully confirmed balance only, but if we want to show the unconfirmed and insecure balance (with the confirmed balance) it should be result['confirmed'] + result['unconfirmed'] + result['unmatured'] , we could potentially  add another function to show the unconfirmed …
> Use new exclude_claimtrietx option in lbryum getbalance command, fix maturity use

- lbrynet/lbrynet_daemon/LBRYDaemonCLI.py
- tests/unit/lbrynet_daemon/test_LBRYDaemonCLI.py
Make lbrynet-cli easier to use on windows by converting keyword args to json. Windows doesn't want to decode arguments given as json from powershell, this provides an alternative.
cli now accepts commands like:
`lbrynet-cli resolve_name name=one`
as well as json:
`lbrynet-cli resolve_name '{"name": "one"}'`
> fix windows cli

- lbrynet/core/LBRYWallet.py
- lbrynet/lbrynet_daemon/LBRYDaemon.py
This changes the return for `get_claim_info` to not include `is_mine` as a field, and instead adds a `get_my_claim` function to look for a users claims.
> add get_my_claim, remove is_mine from get_claim_info response

- lbrynet/analytics/events.py
- lbrynet/lbrynet_daemon/LBRYDaemon.py
Adds a new event `Download Started` which is triggered when `_download_name` is called.  This will enable a better "active user" metric.
The resulting event looks like:
```
{
"context": {
"is_dev": false,
"os": {
"version": "15.6.0",
"name": "Darwin"
},
"app": {
"ui_version": "fdc6329c2fa35353db1a6c0f9a697216e78e1848",
"version": "0.5.0",
"name": "lbrynet",
"wallet": {
"version": null,
"name": "lbrycrd"
},
"python_version": "2.7.11"
},
"library": {
"version": "1.0.0",
"name": "lbrynet-analytics"
}
},
"event": "Download Started",
"properties": {
"stream_info": null,
"lbry_id": "4vox16oB69xoy742F9nTfKVn8KGhLaLiCNPEwX7QfqEyWgDgcJWWJtCEcKAvf7ADZc",
"name": "francine",
"session_id": "t92dkf4hs82831JiwNwiEaM7oeUKyUht4mGf7sD3BkPTPLcn9rRRoNarigDvGPfyv"
},
"receivedAt": "2016-09-28T16:04:54.423Z", …
```
> Start stream event

- INSTALL.md
Edits installation instructions to 
* discourage installation from source
* suggest using a virtual environment when installing from source (as is standard practice).
* remove the instructions to run the osx installation script
> encourage use of virtualenv

- tests/functional/test_misc.py
osx doesn't have epoll so needed a way to skip these two tests.
> Tests requiring epoll should only run on linux

- lbrynet/lbrynet_daemon/Daemon.py
Logs were reporting:
```
Failure instance: Traceback: <type 'exceptions.AttributeError'>: StrictVersion instance has no attribute 'version'
/Volumes/LBRY/LBRY.app/Contents/Resources/lib/python2.7/lbrynet/lbrynet_daemon/DaemonServer.py:121:requestReceived
twisted/web/server.pyc:183:process
twisted/web/server.pyc:234:render
/Volumes/LBRY/LBRY.app/Contents/Resources/lib/python2.7/lbrynet/lbrynet_daemon/Daemon.py:450:render
--- <exception caught here> ---
twisted/internet/defer.pyc:150:maybeDeferred
/Volumes/LBRY/LBRY.app/Contents/Resources/lib/python2.7/lbrynet/lbrynet_daemon/Daemon.py:1561:jsonrpc_version
/Volumes/LBRY/LBRY.app/Contents/Resources/lib/python2.7/lbrynet/core/utils.py:39:version_is_greater_than
distutils/version.pyc:140:__cmp__
```
> Fix error when version is None

- packaging/windows/test.ps1
According to
https://www.appveyor.com/docs/build-configuration/#script-blocks-in-build-configuration
a build only fails if an exception is thrown. This is causing builds to pass even if
the tests fail. That same link suggests adding the code that is in this commit.
I tested that this works by intentionally failing a test: https://ci.appveyor.com/project/LBRY/lbry/build/1.0.170
> Appveyor build needs to fail when tests fail

- lbrynet/core/Wallet.py
- lbrynet/lbryfilemanager/EncryptedFileDownloader.py
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Publisher.py
Further work on jack's branch add-nout to integrate nout : https://github.com/lbryio/lbry/pull/186 . 
This pull request also integrates unmerged new lbryum claim transaction commands https://github.com/lbryio/lbryum/pull/34 
This patch changes the daemon json rpc commands support_claim, abandon_claim, and publish . As such some changes to lbry-web-ui is probably required. 
This patch will also break lbrycrd support if merged, as it does not have txid + nout support for claim transactions. 
I was able to test the publishing successfully through the web ui and the abandon_claim / support_claim through the cli. But further testing is needed as this is a major change.
> work on jack's add-nout branch

- tests/functional/test_misc.py
- tests/functional/test_reflector.py
- tests/functional/test_streamify.py
- tests/mocks.py
- tests/unit/core/server/test_BlobRequestHandler.py
- tests/unit/core/test_Strategy.py
No functionality was changed, just made some simple refactorings.
- delete redundant Fake objects
- Move Streamify tests into their own module
- Refactor start_lbry_uploader to be a class instead of a function with a bunch of inner functions 
- I like this pattern much much better as it makes it significnately more clear what state is being shared
> Start to cleanup functional tests to improve readability

- lbrynet/core/log_support.py
- lbrynet/lbrynet_daemon/Daemon.py
Apply json.dumps at the end of the formatting process instead of the
middle.  This allows for proper escaping of quotes and allows for
actual json to be emitted.
Tracebacks in loggly aren't being parsed because of this mistake.  This should allow for more robust filtering.
> Use better json formatting

- lbrynet/conf.py
- lbrynet/core/log_support.py
- lbrynet/core/utils.py
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/DaemonControl.py
- lbrynet/lbrynet_daemon/DaemonServer.py
- lbrynet/lbrynet_daemon/Downloader.py
- lbrynet/lbrynet_daemon/Publisher.py
- lbrynet/lbrynet_daemon/UIManager.py
- packaging/osx/lbry-osx-app/lbrygui/main.py
- packaging/windows/lbry-win32-app/LBRYWin32App.py
- Make the logging across the OSX app, the windows app and the CLI consistent.
- Remove the repeated code for setting up the log file
- Moved logic for log file upload into its own class
- change the logic for the `--verbose` flag:
- if no arguments are specified after `--verbose`, set all `lbrynet` loggers to debug
- if arguments are specified after `--verbose` only set those loggers to debug
The idea with the --verbose flag is that we will be able set the modules that we're working on to be at the debug level.
> Cleanup logging

- lbrynet/core/log_support.py
lbryum is very chatty at the info level. As a rough estimate a bit
over half of our logs in loggly are a result of lbryum.
The better, long-term, solution would be to modify lbryum to move more
logs to the debug level.
> set lbryum to log at warning level

- lbrynet/lbrynet_daemon/DaemonControl.py
Hopefully, by waiting to launch the browser until after listenTCP has happened, we should see less people complaining about localhost refusing to connect.
> Start listening before launching browser

- lbrynet/core/Wallet.py
This patch removed is_mine and broke the name_claim function in Wallet.py in cases when we were updating : https://github.com/lbryio/lbry/pull/165/files because there was no longer a 'is_mine" field in claims.
We can now use get_my_claim to determine if we have made claim over a name, which is the correct behaviour over using get_claim_info . ( since we could have made a non winning claim)
> Fix updates in name_claim function 

- lbrynet/core/Error.py
- lbrynet/core/Wallet.py
- lbrynet/lbrynet_console/ControlHandlers.py
- lbrynet/metadata/Metadata.py
_get_stream_info_from_value and _get_claim_info function in Wallet could fail with uninformative exceptions in the case where the value of a claim is not a json dictionary, or is not a json string. 
Have Metadata class detect when it is fed an non dictionary item as metadata and throw a TyepError exception.  
Catch  TypeError exceptions from Metadata and ValueError exceptions from failed json.loads('...') calls. 
Change InvalidStreamInfoError to contain the stream info.
> Better error detection in Wallet for invalid streams

- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/DaemonControl.py
Was getting a "cannot stop a reactor that isn't running error"
when playing around with error handling on startup.
Following the suggestion from http://stackoverflow.com/a/36738480
it seems to work better
> More robustly stop the reactor

- lbrynet/core/Error.py
Missing self in Exception initialization
> fixing UnknownNameError exception initialization

- lbrynet/lbrynet_daemon/UIManager.py
In UIManager, pass self._load_ui into deferred as function object instead of calling immediately
> Fix deferred for loading user-specified UIs

- .bumpversion.cfg
The release process now looks like:
starting version: 0.7.5
bumpversion patch -> 0.7.6-rc0
bumpversion candidate -> 0.7.6-rc1
bumpversion release -> 0.7.6
> Add release candidates to bumpversion

- lbrynet/dht/protocol.py
This reverts the change made in 693fef1964e281eaf7b39f9bd9f5728406942a14
Not sure why this is needed, but taking this out sometimes causes
`exceptions.AttributeError: 'Port' object has no attribute 'socket'`
to happen on shutdown.
> Restore reactor.iterate in dht shutdown

- .bumpversion.cfg
- lbrynet/__init__.py
- packaging/ubuntu/lbry.desktop
setuptools will force a version to be 'normalized'
which means that it removes the dash.
This will probably cause some weirdness on the version
numbers in the windows build; might have to re-work
my patches on cx_freeze: https://bitbucket.org/jobevers/cx_freeze/commits/all
> Normalize python version

- lbrynet/core/Wallet.py
get_my_claim command will not work if you attempt to look for a name immediately after making a claim. Thus attempting to update right after making a claim will not work. 
This is because after obtaining claimed names from lbryum wallet, get_my_claim() attempts to format it using the command get_claim() which triggers a call for lbryum to query lbrycrdd (the blockchain) for claims.  A claim that exists in the wallet, will not necessarily exist in the blockchain yet. 
This will be an interface change for the lbrynet-cli command get_my_claim() , (it seems that no other lbry component is currently using this command).
In the future, we need to further reconsider this function as someone could make multiple claims for a single name, and get_my_claim() only returns the first claim it sees that …
> Update right after making claim will fail due to get_my_claim()

- lbrynet/lbrynet_daemon/UIManager.py
Currently, certain options passed in through the API, like `check_requirements: true`, will sometimes be overridden by settings. This PR fixes that.
> Give priority to arguments over settings in UIManager.setup()

- lbrynet/conf.py
- lbrynet/lbrynet_daemon/auth/server.py
- tests/unit/lbrynet_daemon/auth/test_server.py
For a host to be able to access the daemon running inside a docker
container the damon needs to be listening to 0.0.0.0
> Allow 0.0.0.0 for api interface

- lbrynet/core/Wallet.py
Fixing the missing return of a defer.fail when claim fails
> Missing the return of a defer.fail when claim fails

- lbrynet/analytics/api.py
We've started seeing a lot of:
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Hopefully this fixes the problem. Its hard to test, so I'll
have to check the logs after releasing.
> Attempt to fix analytics badstatusline error

- lbrynet/conf.py
- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
- tests/unit/test_conf.py
Restores the functionality needed for the Settings page to work. Mainly:
- Adds the method `conf.get_adjustable_settings_dict()` which gives us back the ability to get a list of just the configurable settings
- Loads all configurable settings into props on Conf at init time so they can be updated as needed
- The API now saves settings to disk immediately on changes (pretty sure this was the old behavior)
Resolves this item: https://app.asana.com/0/search/223123819728339/220821321387630
> Fixes to get_settings() and set_settings()

- lbrynet/core/Wallet.py
Code to not include supports in get_my_claim is deprecated, entries for supports look like below, use key 'category' to identify supports. 
"address": "bGKZv95UCGA6Wuw9rjwU1ueFLEw4i9pbpv", 
"amount": 0.0001, 
"blocks to expiration": 261288, 
"category": "support", 
"claim_id": "467513d3a6eed0114964d751cd85ed49c8e3af4e", 
"confirmations": 1686, 
"expiration height": 350378, 
"expired": false, 
"height": 87404, 
"is spent": false, 
"nOut": 0, 
"name": "warandpeace", 
"txid": "9b647d61326752abd2efba31b6cf9413ef961eb43673ae8e9f331804aa196c64"
> Fix bug to exclude support in get_my_claim

- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
This patch fixes wallet concurrency issue happening due to the fact that lbryum is not designed  to be thread safe, but lbrynet was making asynchronous threaded calls to lbryum by using threads.deferToThread() .
This patch requires https://github.com/lbryio/lbryum/pull/59 from lbryum. 
https://github.com/lbryio/lbry/commit/84daa6b4885a99df5b09aae1e8753b986f98d77d
First we remove unused get_transaction function from both Daemon and Wallet. This function was not being used anywhere (not used in lbry-web-ui either), has concurrency issues, and was not even decoding the transaction in a useful manner so I just decided to remove it instead of  fixing it. 
https://github.com/lbryio/lbry/commit/9125adbba9c1160bab6cacbb61beb723ed4467b5
Use defer.succeed( ) instead of threads.deferToThread() when …
> Fix wallet concurrency issue 

- lbrynet/lbrynet_daemon/Daemon.py
I had an old version of lbryum installed and so no
names were coming back. But the daemon was failing
silently. This at least logs the error.
> Log failure when attempting to get_lbry_files

- lbrynet/lbrynet_daemon/Publisher.py
Publishing is failing right now, due to bug in Publisher. 
Since this  https://github.com/lbryio/lbry/pull/320 was merged in with "All the PR pull request" https://github.com/lbryio/lbry/pull/339
, claim_out no longer returns success and Exceptions are thrown in the Wallet code below instead
https://github.com/lbryio/lbry/blob/master/lbrynet/core/Wallet.py#L466
> Fixing bug in publisher

- requirements.txt
- setup.py
From https://github.com/lbryio/lbry/pull/340, but only address the issue with six on arch.
> allow more recent versions of six

- lbrynet/core/server/ServerProtocol.py
- tests/functional/test_misc.py
This patch 
https://github.com/lbryio/lbry/commit/09846413bdf0aa5c647e8ca4e8198d748b4e6ff8 introduced a problem where BlobRequestHandler would never be loaded by ServerProtocol , because self.factory.query_handler_factories loaded by the Daemon ( see _add_query_handler() )was changed to be a dictionary of {query_id: query_handler_factory,} where before it was {query_handler_factory:enabled,}. This will cause the download to fail. 
This patch changes ServerProtocol but I'm not sure if you want to change ServerProtocol or the Daemon function _add_query_handler() .
> Fix bug in server protocol

- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/DaemonControl.py
- lbrynet/lbrynet_daemon/DaemonServer.py
In some of my scripts to test reflector it was useful to have a different storage backend to cache metadata for the wallet.
This separates the metadata caching logic from the wallet and creates an new in-memory storage backend.
> Wallet storage

- lbrynet/core/Session.py
In general, unless we have a way to actually handle an error, its better to shutdown then to leave the app in a weird state.
> Stop eating wallet connection error

- lbrynet/lbrynet_daemon/auth/server.py
- packaging/windows/init.ps1
- requirements.txt
- setup.py
The older version we were running didn't support jsonrpc v2 for
error codes, which both the command line client and ui client
were expecting.
Notably, this fixes this error:
```
File "/home/jobevers/.virtualenvs/lbry/lib/python2.7/site-packages/jsonrpc/common.py", line 185, in get_result
code = self.error['code']
KeyError: 'code'
```
> upgrade txJson-RCP to 0.5

- lbrynet/lbrynet_daemon/Daemon.py
I created a tagged lbryum release on github, so now we can get version from there https://github.com/lbryio/lbryum/releases like we do with lbrynet instead of pulling it from the source code pages. 
Obtaining a response using requests can also hang the startup process indefinitely if the github server is slow to respond, or access to github is blocked, so add a conservative timeout.
Further improvement would be to use an asynchronous call to make requests.
> Fix obtaining version from github

- .gitignore
- FAQ.md
- README.md
- lbrynet/core/Error.py
- lbrynet/core/Wallet.py
- lbrynet/create_network.py
- lbrynet/dht_scripts.py
- lbrynet/dhttest.py
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/DaemonCLI.py
- lbrynet/lbrynet_daemon/DaemonControl.py
- lbrynet/lbrynet_daemon/Downloader.py
- lbrynet/lbrynet_daemon/auth/client.py
- lbrynet/lbrynet_daemon/auth/server.py
- packaging/osx/lbry-osx-app/lbry_uri_handler/LBRYURIHandler.py
- packaging/ubuntu/lbry
- packaging/uri_handler/LBRYURIHandler.py
- tests/functional/test_misc.py
Several things happened here:
- Renamed many API endpoints. The goal is to use noun_verb style as much as possible (e.g. file_seed, claim_new, etc). 
- Old API endpoints still work, but are deprecated and ready for removal.
- CLI interaction is more pleasant. Error messages are nicer, help text is nicer, commands list is nicer.
- CLI no longer knows/cares whether or not api authentication is being used (its all handled in client)
- Subhandler functionality has been removed from AuthJsonRpc. We don't use it.
- Removed trailing ellipses from a bunch of messages.
@jackrobison the daemon ignores `use_auth_http` in daemon_settings.yml. this can cause the daemon and the CLI to be out of sync regarding when to use authenticated requests.
> The Great API Renaming

- .travis.yml
We have a dedicated OSX machine now, let's build on there instead. Its not CI, but waiting two hours for a build isn't CI either.
> Remove osx from travis build matrix

- lbrynet/core/log_support.py
Twisted does its own thing with logging, and without hooking into it we are left with the very useful "Unhandled error in deferred" message.
By hooking the twisted logging into the python logger, we'll actually get some useful error messages.
Twisted also logs when protocols start / stop, etc.  Which might be useful, might be noisy - can adjust the log level if its too noisy
> Logging Improvements

- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Publisher.py
The Daemon RPC command "publish" did not return the claim ID of the claim and fee when going through Publisher class (Publisher class only returned txid and nout).  
It was also returning the claim Id in a dictionary with the key "claimid" which was inconsistent with other claim functions which were using the key "claim_id". This requires lbryum patch : https://github.com/lbryio/lbryum/pull/70
Added comments on what the claim_name() function does in Wallet.py
> Fix Daemon RPC command publish output

- .travis.yml
Reverts lbryio/lbry#405
oops; we aren't ready to build osx on our own.
> Revert "Remove osx from travis build matrix"

- lbrynet/core/Wallet.py
claim_out['fee'] was not returned as float, so this log message would throw exception. Make sure we do the conversion here.
> fix log message in publisher

- lbrynet/core/log_support.py
- lbrynet/lbrynet_daemon/auth/server.py
When a command would error, the `_render_error` function was failing to call because the id_ parameter was missing. Additionally, twisted was silencing the error.
> Add back id

- lbrynet/core/BlobManager.py
- lbrynet/core/HashBlob.py
- lbrynet/lbrynet_daemon/Daemon.py
Move the blob verification to the actual Blob object; remove the check on verification time.
I'm not sure what checking verification time against ctime gets us, except some protection against an accidental modification of the blob.
I think a better approach, for future development, would be an occasional task that goes through and checks some subset of the blobs comparing the hash of their contents to their name and purging ones that don't match.
> Blob verification fixes

- lbrynet/core/Wallet.py
Use an unused address (address that has no balance on it) when calling get_new_address() if possible. 
This is a temporary fix to the fact that lbrynet generates a new address every time a download request is made by a peer, and making the lbryum wallet very large after the node runs for some time. 
This will break download fee (fees paid to download from a dht node) calculations, since two different download requests can get the same payment address. But since download fees should be set to zero for most nodes now, it shouldn't cause any problems. A better fix would involve creating payment requests that expire after a certain time, but is a bit involved. 
This will also prevent the refresh button on the "My Wallet" UI in lbry web ui from creating a new address (since it just returns an …
> Prevent excessive generation of new addresses

- lbrynet/core/file_utils.py
- lbrynet/lbrynet_daemon/Daemon.py
- Factors out the core logic for both of these into methods on a new module called lbry.core.file_utils
- Both methods now take an SD hash instead of a path (more logical and improves security)
- reveal() now works on Windows
- No longer spins off new threads for the OS calls since they're non-blocking (thanks to @jackrobison for pointing out this wasn't necessary)
Todo before this is ready:
- Tests
- The SD hash is not really the right identifier for this, as you can have multiple files downloaded with the same SD hash. Very soon Jack is planning to create a new unique ID for entries in the file manager, so we should probably wait until that change is in and then switch this to use the new ID.
Fixes this issue: https://app.asana.com/0/search/246741549780800/161594953616366
> Add open() API method and refactor/update reveal() API method (WIP)

- lbrynet/core/Wallet.py
Warn users if they have too many addresses in their wallet, due to https://github.com/lbryio/lbry/issues/415
Provide them with instructions at https://github.com/lbryio/lbry/issues/437 , not sure if that's a good location but can be changed.
> Add warning for large wallet sizes

- lbrynet/core/HashBlob.py
When creating a CryptStream, the last blob is always empty. Previously, this
blob wouldn't be deleted and would instead just stick around in the blobfiles
directory.
> Bug fix: delete empty blobs

- lbrynet/core/client/ClientProtocol.py
- lbrynet/core/client/ConnectionManager.py
Add better logging ( log.debug's) for ConnectionManager and ClientProtocol (used by ConnectionManager to manage individual connections). 
In general be more verbose, and state what a specific instance of that class if for (what peer its connected to, or what its downloading)
> Better Connection manager and Client Protocol logging

- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Downloader.py
- tests/unit/core/test_Wallet.py
https://github.com/lbryio/lbry/commit/9230fb24dd0eaae379273e152a1d78a3f714702d just removes an unused get_transaction function from Wallet 
https://github.com/lbryio/lbry/commit/39d3947e88cece94209d049c21b3bf31ba6c436a fixes the Wallet interface for obtaining the balance, which was previously confusing and has lead to some bugs. 
Previously,  external classes used class member wallet_balance to fetch the balance of the wallet. However there is a method named get_balance()  which was used by the wallet to periodically pull the balance from lbryum, but should not be used by external classes to obtain the balance. We rename the previous get_balance() function as update_balance()  to avoid confusion , and change the function slightly to have it actually set class member wallet_balance. …
> Fix wallet balance interfaces

- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Downloader.py
Had instances where I was unable to download a name the first try, but when making a second attempt it worked. The underlying cause could probably be dealt with my improving the connection manager and general blob downloading framework, but this bandaid is a decent solution for now.
> Retry the get call three times before failing

- lbrynet/lbrynet_daemon/DaemonControl.py
- packaging/ubuntu/lbry
By default the daemon now doesn't launch the UI and outputs logs to the console
Removes `--no-launch`, UI can be launched with `--launch-ui` 
Removes `--log-to-console`, logging can be turned off with `--quiet`
> Change default behavior with daemon cmdline args

- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
What was happening was the wallet claimed to be caught up before it
actually was and so the wallet’s local_height was still the value from
when lbry was last run, frequently more than 20 or 50 blocks
behind. _get_value_for_name uses the block at local_height as the
basis for the proof.  If _get_value_for_name is called during that
time between when the wallet claims to be caught up and it actually
is, the “Block too deep error” happens.  And since the discover page
of the UI does name resolution right away, the error basically happens
anytime somebody starts the app after not using it for a few hours.
This changes the startup behaviour of the wallet to
- use the `updated` callback provided by lbryum
- check that local_height and network_height match before declaring
that the wallet has …
> Fix #449: Block to deep error

- setup.py
We'll, of course, forget to update this when we change lbryum, but its progress towards making sure that a new enough version of lbryum is installed.
> require minimum version for lbryum

- lbrynet/lbrynet_daemon/Daemon.py
this fixes a bug where if github is down the app will fail to start.
-check for new version every 30 min instead of every 12 hours
-check connection problems every 30 seconds instead of every second
> non-blocking version check

- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/reflector/__init__.py
- lbrynet/reflector/client/blob.py
- lbrynet/reflector/client/client.py
- lbrynet/reflector/common.py
- lbrynet/reflector/reupload.py
- lbrynet/reflector/server/server.py
- tests/functional/test_reflector.py
add {‘sd_blob_hash’: …, ‘sd_blob_size ‘: …} query type with
{‘send_sd_blob’: True/False, ‘needed_blobs’: []} response
this allows the reflector client to know how much of a stream reflector
already has covered, as to minimize the number of subsequent requests
and prevent streams from being partially reflected
> Reflector v2

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Publisher.py
- lbrynet/reflector/client/client.py
- lbrynet/reflector/reupload.py
- tests/functional/test_reflector.py
-fix recursion depth bug upon failed blob upload
-stopProducing file_sender when set_not_uploading is called
-include stream uri in reflector logs to de-obfuscate them
> Fix reflector bugs

- CHANGELOG.md
- lbrynet/core/Error.py
- lbrynet/lbryfilemanager/EncryptedFileManager.py
This migrates any streams tracked by stream_info_manager but not lbry_file_manager to also be included by the file manager
This commit should prevent new streams from having this problem: https://github.com/lbryio/lbry/commit/2126f69c930a4a4d22169cff3533362fe6e0bcaf
> fix streams in stream_info_manager not being loaded by lbry_file_manager

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
It was trying to access this setting as an attribute, which doesn't work anymore. (Not sure if this is an API change in conf.settings or just a bug.)
> Fix how the bug report code accesses Slack API key setting

- CHANGELOG.md
- lbrynet/core/Peer.py
- lbrynet/core/client/ClientProtocol.py
- lbrynet/core/client/ConnectionManager.py
- tests/unit/core/client/test_ConnectionManager.py
Add trial tests for Connection Manager, this required some changes to Connection Manager to make it work but overall functionality is unchanged. Below are the list of changes.
The test caught a case where Connection Manager would not report a peer that was returning an unexpected response as being down, and thus it would attempt to reconnect to it later. This has been fixed in this patch. 
**Peer changes-** 
Add a report_success() function to the Peer class so we can figure out how many successful connections we've made to the peer.  Useful in unit testing. Also just added some comments to clarify how the class should be used. 
**ConnectionManager changes -** 
start() function is seperated into _start() and start(). _start() does the initialization and
start() handles the reactor …
> Connection Manager tests 

- CHANGELOG.md
- lbrynet/core/BlobManager.py
- lbrynet/core/server/DHTHashAnnouncer.py
- tests/mocks.py
- tests/unit/core/server/test_DHTHashAnnouncer.py
- tests/unit/lbryfilemanager/test_EncryptedFileCreator.py
This patch fixes https://github.com/lbryio/lbry/issues/432
It was discovered that after running a reflector node with 16000 hashes, the hash queue (hashes waiting to be announced) was growing at a very fast rate. After 18 hours of running, the hash queue had about 160,000 hashes (see below debug lines from reflector4). 
2017-02-08 00:04:00,459 DEBUG    lbrynet.core.server.DHTHashAnnouncer:67: There are now 14 hashes remaining to be announced
2017-02-08 18:41:07,384 DEBUG    lbrynet.core.server.DHTHashAnnouncer:67: There are now 164043 hashes remaining to be announced
Since each hash takes about half a second to announce, this means it would take 80,000 seconds (or about 22 hours) for any new hash that got put into the queue to be announced , and the condition would obviously worsen after …
> Adjust hash reannounce based on queue size , test for DHTHashAnnouncer

- CHANGELOG.md
- lbrynet/core/Error.py
- lbrynet/core/utils.py
- lbrynet/lbryfilemanager/EncryptedFileDownloader.py
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Publisher.py
- tests/functional/test_streamify.py
- tests/mocks.py
This fixes publish not redirecting to the published files page after publish() returns
-if a lbry file from the winning claim is in the file manager, return it. otherwise return a lbry file from a pending claim if one exists.
-update lbry_file.start to match lbry_file.restore
-add lbry_file.load_attributes
> file_get by name for file with pending claim

- lbrynet/lbrynet_daemon/auth/server.py
- tests/unit/lbrynet_daemon/auth/test_server.py
Also @jackrobison can you explain what check_headers does that `access-control-allow-origin` doesn't protect against.
> Allow requests that match allowed-origin

- CHANGELOG.md
- lbrynet/analytics/events.py
- lbrynet/analytics/logging_handler.py
In investigating #480, turns out log_record.message doesn't have traceback info - so adding another field to record it
> record traceback in error event

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
The ui needs the result for missing files to be `False`, instead `None` was being returned.
> fix missing download button

- lbrynet/core/HashAnnouncer.py
DummyHashAnnouncer requires hash_queue_size() function, if to be used in conjunction with DHTHashSupplier (or BlobManager which inherits from DHTHashSupplier) because of this patch https://github.com/lbryio/lbry/pull/465
This fixes scripts download_blob_from_peer.py  and reseed_file.py
> dummy hash announcer requires hash_queue_size() function

- CHANGELOG.md
- lbrynet/core/HashAnnouncer.py
- lbrynet/core/client/ConnectionManager.py
- lbrynet/core/server/DHTHashAnnouncer.py
- lbrynet/core/utils.py
- tests/unit/core/client/test_ConnectionManager.py
- tests/unit/core/server/test_DHTHashAnnouncer.py
Add reactor.callLater https://twistedmatrix.com/documents/16.4.0/api/twisted.internet.interfaces.IReactorTime.callLater.html as a utils function call_later() , so that trial tests can replace it with clock.callLater or some other non reactor function. Will be used in https://github.com/lbryio/lbry/pull/465 and https://github.com/lbryio/lbry/pull/458 , also need to replace instances of reactor.callLater in other parts of the code.
> Adding reactor.callLater as a utils function

- CHANGELOG.md
- lbrynet/core/client/ClientProtocol.py
- tests/unit/core/client/test_ConnectionManager.py
Add a timeout to ClientProtocol using TimeoutMixIn:  http://twistedmatrix.com/documents/9.0.0/api/twisted.protocols.policies.TimeoutMixin.html  . 
If a peer does not send anything within 30 seconds, close the connection and mark peer as down.  Also add a unit test for the timeout.
> Adding timeout to ClientProtocol

- CHANGELOG.md
- lbrynet/core/Wallet.py
lbryum.network.get_local_height() could be -1 in case the blockchain_headers file is empty (can happen on fresh installs See: https://github.com/lbryio/lbryum/blob/master/lib/blockchain.py#L171 ) , in this case subsequent calls can fail since there is no header at height -1. 
Add checks for these cases where get_local_height() is used.
This patch is required to fix lbry in a box integration testing
> Add check in case local height is less than zero

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Downloader.py
When running command "get" on name "0ne-osx-desktop" (starts with numerical zero), it was discovered that if you are unable to download the sd_blob, the download never times out, thus the "get" command stalls forever. 
If you look at Downloader class, start() is yielding to download() which means that it waits for sd_blob_download() to finish. sd_blob_download() does not have a timeout so it never finishes. You have to call download() and than yield to data_downloading_deferred() to get the proper behavior. 
We really need a proper timeout mechanism in the correct base classes as I stated here https://github.com/lbryio/lbry/issues/504 to prevent these issues from happening, and to avoid writing timeout codes all over the place.
> Fix downloading not timing out properly when unable to download sd blob

- lbrynet/lbrynet_daemon/Daemon.py
claim_list() API command took txid as an argument to call get_claims_from_tx() 
Do not expose it for now as we don't have consistent way to return claims  between get_claims_from_tx() and get_claims_for_name()
> Do not expose get_claims_from_tx() from the API

- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Publisher.py
There was a bug in publisher  which made it not accept Fee dict structure without addresses in them ( i think just someone forgot to delete a line) such as {'LBC':{'amount':0.01}}
Also clarified publish docstring what fee dict would look like.
> Fix fee validation in publisher and clarify publish docstring

- docs/index.md
- lbrynet/lbrynet_daemon/Daemon.py
standardize the format of api docstrings into below format
Args:
'name'(optional):(type) description
Returns:
(type) description
> Make api docstrings consistent

- CHANGELOG.md
- docs/index.md
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Publisher.py
Changes partially taken from db refactor branch
https://github.com/lbryio/lbry/pull/505/commits/491fba5b36abe394e1437ca7f74ad7481c27fe2a
jsonrpc_publish can now take metadata fields as arguments 
Change and make docstring more informative 
Move add_fee_to_metadata() function from Publisher class to jsonrpc_publish() so that its consistent with how other metdata fields are handled.
> Change publish to take metadata fields as arguments, docstring change

- CHANGELOG.md
- docs/index.md
- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
fix spelling error getpubkyes
argument 'wallet' changed to 'address' to be less confusing
clarify that the command returns a list in the doc string 
return the deferred 
update api docs
> fix wallet_public_key API command

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
https://github.com/lbryio/lbry/pull/469 This pull request broke descriptor_get API command. The command would always return null because _download_sd_blob() function had a crucial deferred that was setup in line 762 of Daemon.py but was never part of any callback chain.
d = download_sd_blob(self.session, sd_blob_hash, rate_manager)
I fixed it so that it uses jsonrpc_blob_get with encoding json (code reuse is nice). It doesn't save the sd blob to the stream_info_manager but I don't really see a great reason why it should do so.  Since _download_sd_blob() is not used anywhere else, it can be deleted.
> Fix broken descriptor_get command

- CHANGELOG.md
- lbrynet/lbrynet_daemon/DaemonControl.py
- lbrynet/lbrynet_daemon/DaemonServer.py
Fix for https://github.com/lbryio/lbry/issues/549
Create a stop() function in DaemonServer, which closes the listening port and shuts down the Daemon. 
This allows a DaemonControl to restart the DaemonServer in case something goes wrong while starting up the Daemon ( you can't restart if the port is already binded, and if you don't shut down the Daemon before restarting, you'll have two Daemon's running at the same time)
> Fix restart procedure in DaemonControl

- CHANGELOG.md
- docs/index.md
- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
Previously the wallet/API used get_new_address()/ wallet_new_address() which returned an unused address (address containing no balance, generate new one if none). We rename this function to get_unused_address()/wallet_unused_address(), and create a function that always generate a brand new address get_new_address()/wallet_new_address(). 
Internally, get_unused_address is used when generating recieve address for data fees ( to prevent reflector from generating large amount of addresses). get_new_address is used when generating key fee recieve address for publishing.
> get_unused_address / get_new_address

- docs/index.md
- lbrynet/lbrynet_daemon/Daemon.py
just a clarification on the docstring for jsonrpc_pulish() that publish will update over existing name
> clarify publish API command docstring

- CHANGELOG.md
- lbrynet/core/Wallet.py
During updates, publishing was silently using metadata fields in the old claim and placing it in the new claim. This would cause a problem for example if you specified a key fee in the old claim , but did not in the new claim (indicating free content). 
Treat metadata specified in the update as the de-facto metadata.
Am i missing something here?
> Remove update_metadata() function

- CHANGELOG.md
- lbrynet/dht/routingtable.py
- tests/unit/dht/test_routingtable.py
Fixes #436.
Here's how this happens:
Each DHT node starts with 1 bucket for all of its contacts. When the bucket is full and a new contact should be added, one of two things happens.
- If the bucket contains the node's id, it is split into two buckets which together cover the same range. 
- If the bucket does not contain the node's id, we store the contact in that bucket's replacement cache. When a contact is removed from a bucket, contacts from the replacement cache are filled into the bucket.
In the latter case, the replacement cache for a given bucket may also fill up, in which case the oldest contact in the replacement cache is dropped before adding the new contact. The bug occurs when dropping the old contact. The code on lines 412-413 says 
```
elif len(self._replacementCache) >= …
```
> fix KeyError bug in dht

- .gitignore
- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
- tests/mocks.py
Better to let the client decide whether to display the short or long version
> Return full LBRY ID and installation ID in jsonrpc_status()

- requirements.txt
having trouble installing when I have most recent appdirs installed and lbrynet requirements.txt forces a downgrade into 1.4.0 https://github.com/ActiveState/appdirs/issues/89
appdirs changelog https://github.com/ActiveState/appdirs/blob/master/CHANGES.rst
> use appdirs 1.4.3 in requirements.txt

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
stream_cost_estimate will throw exception when claim value is non decodeable instead of returning None. 
Have it return None, and clarify this in the docstring.
> Fix stream_cost_estimate

- CHANGELOG.md
- lbrynet/core/Wallet.py
fixes lbryum requests timing out because there were too many address subscriptions ahead of them after startup
> wait for address subscriptions before announcing the wallet has started

- CHANGELOG.md
- lbrynet/core/Wallet.py
- lbrynet/db_migrator/dbmigrator.py
- lbrynet/db_migrator/migrate2to3.py
- lbrynet/lbryfile/EncryptedFileMetadataManager.py
- lbrynet/lbryfilemanager/EncryptedFileDownloader.py
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Publisher.py
- lbrynet/lbrynet_daemon/auth/server.py
When issuing several `publish` calls concurrently, a race condition in lbryum causes double spends (and thus rejected transactions). This fixes the race condition by queueing the api calls that result in transactions being broadcast to be run sequentially rather than concurrently.
> Fix publish race conditions

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
User should be able to use claim_show without specifying name
> allow claim_show to be specified without name

- CHANGELOG.md
- lbrynet/core/Wallet.py
- lbrynet/lbrynet_daemon/Daemon.py
- requirements.txt
- setup.py
Not good practice to catch base Exception in API command resolve . Catch UnknownNameError instead .
In Wallet, catch lbryum error 'claim not found' as UnknownNameError
Requires : https://github.com/lbryio/lbryum/pull/107
> catch UnknownNamError instead of base Exception for resolve command

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/auth/server.py
Removed deprecated commands:
`get_best_blockhash`
`is_running`
`daemon_status`
`is_first_run`
`get_lbry_session_info`
`get_time_behind_blockchain`
`get_settings`
`set_settings`
`get_balance`
`stop`
`get_claim_info`
`stop_lbry_file`
`start_lbry_file`
`get_est_cost`
`abandon_claim`
`support_claim`
`get_my_claim`
`get_name_claims`
`get_claims_for_tx`
`get_transaction_history`
`get_transaction`
`address_is_mine`
`get_public_key_from_wallet`
`get_new_address`    
`get_block`
`descriptor_get`
`download_descriptor`
`get_peers_for_hash`
`announce_all_blobs_to_dht`
`get_blob_hashes`
`reflect_all_blobs`
`get_start_notice`
> Remove deprecated commands

- CHANGELOG.md
- lbrynet/lbrynet_daemon/DaemonCLI.py
This changes lbrynet-cli to show the results of the function lbrynet-daemon uses to reply to `version` requests instead of making the api call. This lets `lbrynet-cli --version` work when lbrynet-daemon isn’t necessarily running.
> fix cli version and --version arguments

- lbrynet/lbrynet_daemon/DaemonControl.py
DaemonControl is using deprecated is_running API command to check if there is already a daemon running. Use status API command instead.
> DaemonControl is using deprecated is_running API command

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
- lbrynet/lbrynet_daemon/Downloader.py
- tests/unit/lbrynet_daemon/test_Downloader.py
18fec8e
deferToThread was used for check_fee_and_convert() but is unnecessary, I think before this call made network calls to check the exchange rate but is now no longer the case. 
a004e92
finished_deferred was being initialized as a Deferred that was never used, and was over written with a different Deferred at the end of download() function. If a user used finished_deferred before download() function was called, this would be erronenous. Initialize finish_deferred to None , so that a user cannot accidentally use this deferred before it is ready. 
This is the reason why the download success metric in metabase is always 0. 
f7bbf81
Exceptions throw in download() function would be swallowed since we yield to data_downloading_deferred in the start() function and do not yield on download(). …
> Fix GetStream class

- CHANGELOG.md
- lbrynet/lbrynet_daemon/Daemon.py
- tests/integration/test_integration.py
Fixed various issues in API command file_delete
file_delete should have been preventing deletion of multiple files by default but it was not doing so. Fix this, and make sure that if delete_all flag is True, it allows deletion of multiple files.
delete_target_file was not accurately describing what it was doing, it was described as "delete only from downloads, do not delete blobs". However, the flag will cause the file to be delete from downloads, and blobs are always deleted. delete_target_file should be by default False, since presumably the user will most likely just want to delete the blobs so he can stop seeding them but will want to keep the actual file. 
Added longer flag options, --delete_all  and --delete_target_file (can be used instead of -a and -f) 
Added tests to make sure …
> Fix file delete

- CHANGELOG.md
- lbrynet/lbryfilemanager/EncryptedFileDownloader.py
- lbrynet/lbrynet_daemon/Daemon.py
0b50518
EncryptedFileDownloader could be stopped before self.sd_hash is filled in by load_file_attributes() function. In this case , utils.short_hash() function will throw an exception since self.sd_hash is None . Use stream_hash instead.
114f6ef
This is a complete mystery to me but if a file_name is unicode, ( was checking lbry://casually-successful )
log.info("Deleted %s (%s)", file_name, utils.short_hash(stream_hash))
will throw UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)
But log.info("Deleted file: %s", file_name) will not. There's nothing wrong or unusual about utils.short_hash(stream_hash)...
> Fix log exceptions

- CHANGELOG.md
- lbrynet/core/Session.py
Session shutdown() was not closing blob_tracker properly
> fix typo which may not shut down blob_tracker

- CHANGELOG.md
- lbrynet/core/BlobManager.py
- tests/functional/test_misc.py
- tests/unit/core/test_BlobManager.py
44e7a04
BlobManager has a manage() function that is scheduled to run every second. The only thing it does is delete blobs marked for deletion by the delete_blobs() function. There is no really good reason why we can't just delete the blobs right away. Remove the manage() function and simplify blob deletion function by using inline callbacks.
1fed5f9
Added unit tests for BlobManager. 
4400d51
In test_misc.test_double_download() function test, check_lbry_file() was being called after delete_lbry_file(). 
Since we now delete blobs right away instead of scheduling them, this test was failing. Call check_lbry_file() after delete_lbry_file().
Fixes https://github.com/lbryio/lbry/issues/693
> Fix blobmanager manage

- .appveyor.yml
- CHANGELOG.md
- lbrynet/lbry_file/EncryptedFileMetadataManager.py
- tests/functional/test_misc.py
- tests/unit/core/test_BlobManager.py
- tests/unit/lbryfile/test_EncryptedFileMetadataManager.py
This fixes and enables twisted trial test on appveyor which does the Windows build. (tests/functional and tests/unit) 
I wasn't able to get integration testing (tests/integration) working on Windows though, so that will be a separate todo.
> Fix windows tests

- CHANGELOG.md
- lbrynet/conf.py
- tests/unit/test_conf.py
Likely fix for 
https://github.com/lbryio/lbry/issues/692 
https://github.com/lbryio/lbry/issues/661
data directories in windows were being returned as unicode type, which will result in problems when using os.path.join with filenames that are of string type. 
Added unit tests in test_conf.py to make sure the data directories are in string not unicode. 
relevant discussion where I got the solution from :
https://github.com/pypa/pip/issues/3463
the resulting pr where I got the solution from:
https://github.com/pypa/pip/pull/4000
> Make sure window paths of directories are in string not unicode

- CHANGELOG.md
- lbrynet/core/Error.py
- lbrynet/core/StreamDescriptor.py
- lbrynet/core/client/DownloadManager.py
- lbrynet/core/client/StandaloneBlobDownloader.py
- lbrynet/core/utils.py
- lbrynet/daemon/Daemon.py
- lbrynet/daemon/Downloader.py
- tests/unit/lbrynet_daemon/test_Downloader.py
Fixes https://github.com/lbryio/lbry/issues/716 and https://github.com/lbryio/lbry/issues/504 by adding a timeout argument to function download_sd_blob(). The timeout detects if the blob has been downloaded within a specified time, and if not, it throws DownloadTimeoutError and cleans everything up. 
As a side effect, the timeout behaviour when calling API command get is a bit different now.
Now it will wait 180 seconds (or whatever the timeout is set to) for the sd blob to download, and if it does , waits another 180 seconds for the first blob to download. Before it waited 180 seconds for both the sd blob and first blob. 
f1845c1
In SingleProgressManager, which we will add the timeout mechanism, use twisted's LoopingCall mechanism instead of reactor.callLater to do looping calls as it is …
> Add timeout to download_sd_blob

- CHANGELOG.md
- lbrynet/core/Wallet.py
fix for https://github.com/lbryio/lbry/issues/750
It was found that malformed support and amount data was entering the claim cache due to improper formatting that was fixed in https://github.com/lbryio/lbryum/pull/135. 
This was causing problems when trying to retrieve it through file_list. Since file_list gets the claim from cache regardless of whether it expired or not, this the malformed support would throw exception when processing the effective amount here  https://github.com/lbryio/lbry/blob/master/lbrynet/core/Wallet.py#L78
File "site-packages\lbrynet\core\Wallet.py", line 134, in get_cached_claim
File "site-packages\lbrynet\core\Wallet.py", line 78, in __init__
TypeError: list indices must be integers, not str
and cause the file_list command to fail. Resolving claims through the …
> Fix file_list failing due to malformed supports in the cache

- lbrynet/core/Wallet.py
When resolving @certificatename/some_claim , resolve output will be something like {"certificate":{} , "claim":{} } 
Thus the if statement in handle_claim_result would only cache the certificate and not claim. 
Since file downloading relies on the Wallet cache (we really need to remove this reliance) having the claim, downloading would encounter exception here: https://github.com/lbryio/lbry/blob/master/lbrynet/file_manager/EncryptedFileDownloader.py#L111
> Fix if statement causing claim with certificate to not get cached, and cause downloading to fail

- CHANGELOG.md
- lbrynet/conf.py
- lbrynet/file_manager/EncryptedFileManager.py
- tests/unit/lbryfilemanager/test_EncryptedFileManager.py
File manager will attempt to automatically re-reflect files on startup and every hour. 
Make this configurable through config file. "auto_re_reflect" will turn this feature on/off , "auto_re_reflect_interval" will control how often it attempts to re-reflect. Auto re-reflect is by default on, and interval is every hour (same as before)
Should solve some issues for speech https://github.com/lbryio/lbry/issues/817 by turning auto_re_reflect off.
> Add ability to control re-reflects through config

- CHANGELOG.md
- lbrynet/core/BlobManager.py
-don't block `BlobManager.blob_completed` on the blob being announced  (this considerably slows down the rate at which reflector server can receive blobs)
> Faster reflector server

- CHANGELOG.md
- lbrynet/core/Wallet.py
- lbrynet/daemon/Daemon.py
- tests/unit/core/test_Wallet.py
Enable abandoning by txid/nout (feature already available in lbryum) , necessary for abandoning when you make supports for your own claim , since they share the same claim_id. Fixes https://github.com/lbryio/lbry/issues/795
Removed some unnecessary error handling for abandon in the Daemon. Exceptions are thrown in Wallet and will be propagated so the catching is unnecessary.
> Expose abandon by txid/nout in Daemon

- CHANGELOG.md
- lbrynet/conf.py
- lbrynet/core/BlobManager.py
- lbrynet/core/HashBlob.py
- lbrynet/core/StreamDescriptor.py
- lbrynet/core/client/BlobRequester.py
- lbrynet/core/client/DownloadManager.py
- lbrynet/cryptstream/CryptStreamCreator.py
- lbrynet/daemon/Daemon.py
- lbrynet/db_migrator/dbmigrator.py
- lbrynet/db_migrator/migrate3to4.py
- tests/unit/core/test_BlobManager.py
- tests/unit/lbryfilemanager/test_EncryptedFileCreator.py
This PR adds the option to announce by head blob only. Head blob is the first blob in a stream. 
We create two new columns in the blob manager database: should_announce, and last_announce_time. should_announce is for marking some sd hashes and head blobs (first blob in a stream) as True so they can be distinguished from blobs that shouldn't be announced. last_announce_time is for marking a blob's last announce time so they can be troubleshooted better, this column's usage has not been implemented and is left as null  for future work however. 
Anything that creates blobs will be responsible for marking them as should_announce = True / False depending on if its a head blob, or sd blob (this is partially why commit bdccc35 removes the responsibility of HashBlobCreator to know about …
> Add option for seeders to announce head blob only

- CHANGELOG.md
- lbrynet/conf.py
- lbrynet/core/client/BlobRequester.py
- lbrynet/core/client/ConnectionManager.py
- tests/unit/core/client/test_ConnectionManager.py
This adds an option in conf for clients to download by prioritizing the seeking of the "head blob" (the very first blob in the stream) before they seek the next unavailable blob. 
It is turned off by default in this PR so will not change how downloading works unless configured to be turned on manually.  Should be turned on when reflector switch to announcing head blob only.
> Add option for clients to seek head blob first when downloading 

- CHANGELOG.md
- lbrynet/conf.py
This turns on "head blob seek" for clients downloading from the lbry network. 
Since "head blob announce" is not enabled for reflector, or any other seeders, this should not affect clients since they can fallback to downloading by blobs.
> Turn on head blob seek for clients

- CHANGELOG.md
- lbrynet/core/Wallet.py
Fixed inefficient batch queries in lbryum responsible for making transaction and tip histories slow
goes with https://github.com/lbryio/lbryum/pull/156
> Update tip history for change in lbryum

- CHANGELOG.md
- lbrynet/conf.py
- lbrynet/core/BlobManager.py
- lbrynet/daemon/Daemon.py
- lbrynet/reflector/server/server.py
- tests/functional/test_reflector.py
When running lbrynet as a reflector cluster, it previously did not use the stream info manager at all when receiving streams from clients. Thus a reflector cluster had no knowledge of streams and would  not be able to use head blob announce. 
This adds stream info manager to the reflector server, and uses this to mark blobs as "should_announce" or not. test_reflectory.py has been modified to check if the stream info is handled properly and blobs are marked as "should_announce" if appropriate.
> Reflector rework (for head blob announce)

- CHANGELOG.md
- lbrynet/blob/blob_file.py
- lbrynet/blob/reader.py
- lbrynet/core/StreamDescriptor.py
- lbrynet/core/server/BlobRequestHandler.py
- lbrynet/daemon/Daemon.py
- lbrynet/reflector/client/blob.py
- lbrynet/reflector/client/client.py
- tests/unit/core/test_HashBlob.py
Fix for https://github.com/lbryio/lbry/issues/923 and also some continuing work to improve the blob classes (https://github.com/lbryio/lbry/pull/898)
Blob file opened for reading ( BlobFile.open_for_reading() ) was not being closed after file transfer , thus during client reflection, too many blob files would be opened. Commit a4ea49c fixes this. 
This kind of mistake could be easily made since blob files opened for reading had to be closed by calling BlobFile.close_read_handle(handle) . We can now just call handle.close() to close the blob files.
> Fix blob reader closing

- CHANGELOG.md
- lbrynet/file_manager/EncryptedFileManager.py
- lbrynet/reflector/client/client.py
If you have a lot of files, EncryptedFileManager tries to reflect all the files at once, which will likely cause you to hit your open file limit (default on ubuntu is 1024, so if you have 1000 files, you will likely hit the limit), and will also open up a lot of connections to the reflector server.  This uses DeferredSemaphore, see: https://patrickmn.com/software/using-twisteds-deferred-semaphore/ so that only 5 files are reflected at a time. 
Also it was found the reflector client would not always close an open read handle when connection was closed. Also resulting in a lot of open files. Make sure to do this.
> Fix to not reflect all the files at once

- CHANGELOG.md
- lbrynet/reflector/client/client.py
Fix inconsistency in how EncryptedFileReflectorClient.blob_hashes_to_send is used, preventing proper reflecting.
Some functions put blob hashes in EncryptedFileReflectorClient.blob_hahes_to_send , others put BlobFile's in them. EncryptedFileReflectorClient.open_blob_for_reading() expected BlobFiles so if it received blob hashes, it errored out. 
I fixed it so that EncryptedFileReflectorClient.blob_hashes_to_send always contains blob hashes. And EncryptedFileReflectorClient.open_blob_for_reading() would always be fed BlobFiles.
This looks like a bug that's been here forever.. It looks like it should have prevented any partial reflects from working out properly.
> Reflector client bug 

- CHANGELOG.md
- lbrynet/blob/blob_file.py
- lbrynet/tests/unit/core/test_HashBlob.py
Blob improvements PR https://github.com/lbryio/lbry/pull/898 introduced a deadlock : 
In case , you have two writers, first writer finishes and enters _save_verified_blob, acquires threading.Lock() , yields to FileBodyProducer.start_producer(). This means the second writer can then enter _save_verified_blob and than it attempts to obtain threading.Lock() which will block forever. 
Should never ever use threading.Lock() in twisted as once its blocked, no other tasks can be run in the reactor. Use twisted's DeferredLock() instead. (Before the blob improvements PR it did not deadlock because lock was always acquired and released in a single Deferred which is not interruptible. Also means that there was no point to having the lock before). 
2115919 is a test that recreates the blocking, you …
> Fix deadlock in blob_file

- CHANGELOG.md
- lbrynet/core/BlobManager.py
- lbrynet/daemon/Daemon.py
- lbrynet/tests/unit/core/test_BlobManager.py
When calling jsonrpc_status() with session (-s) flag, add some additional information about blob announcements.
'announce_queue_size' shows the number of blobs currently queued to be announced
'should_announce_blobs" shows the number of blobs that are marked as should_announce (used in head blob announce)
This will be useful for quickly debugging nodes with a large amount of blobs on it (whether it has some backlog in announcement or not) 
Also added unit tests for should_announce function in blob manager
> Add more session info related to blob announcement

- CHANGELOG.md
- lbrynet/cryptstream/CryptStreamCreator.py
- lbrynet/tests/unit/lbryfilemanager/test_EncryptedFileCreator.py
Found bug where if you were creating a stream, the last blob in a stream would not get saved to the blob manager (It was still being created, reflected, and everything else however). See the added test 574660c for the failure case. 
This means that if you created a stream ,  you would never announce the last blob in the stream because the announcement blobs were obtained from the blob manager. (However, this bug would not prevent reflection, or reflector from announcing the blob). 
Might be a potential fix for https://github.com/lbryio/lbry/issues/905
> Fix bug where last blob would not get saved in blob manager

- CHANGELOG.md
- requirements.txt
latest jsonschema version is 2.6.0 https://pypi.python.org/pypi/jsonschema, 
Chanelog: https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst
Also for lbryschema and lbryum: 
https://github.com/lbryio/lbryschema/pull/30
https://github.com/lbryio/lbryum/pull/163
Note: the travis integration test here fails because it tries to start up the daemon but can't because lbryschema and lbryum has set requirements to tagged jsonschema version 2.5.1 , once above two is merged, test should pass
> Bump jsonschema version to 2.6.0

- CHANGELOG.md
- lbrynet/dht/routingtable.py
When a k-bucket does not contain enough close nodes, the
DHT will look into neighbouring k-buckets in order to entend
the list of returned nodes.
However, the list should not be extended beyond its maximum size.
Signed-off-by: Antonio Quartulli <antonio@mandelbit.com>
> Extend close nodes list by right amount

- CHANGELOG.md
- lbrynet/daemon/ExchangeRateManager.py
- lbrynet/tests/unit/lbrynet_daemon/test_ExchangeRateManager.py
Reviewed and made some changes on top of https://github.com/lbryio/lbry/pull/915 by mirgee , which adds ExchangeRateManager capability to have fail over feeds so if one feed fails it can use another. Cryptonator was added as a back up feed.
I added also BittrexFeed as a back up feed, and re-added the unit test for it which was removed some patches ago. 
I also adjusted the detection of if a feed is detected to be online or not. mirgee set this variable in the _make_request function when requests.get() returned a response with status code that is not a success. However this doesn't handle the case when requests.get() throws an exception due to the end point not being available, or if parsing of the requests fail because they changed the API. We now set a feed to be offline in the errback …
> Added redundant market feed (continued)

- CHANGELOG.md
- lbrynet/blob/blob_file.py
- lbrynet/blob/reader.py
- lbrynet/blob/writer.py
- lbrynet/conf.py
- lbrynet/core/client/ClientRequest.py
- lbrynet/cryptstream/CryptBlob.py
- lbrynet/tests/unit/cryptstream/test_cryptblob.py
8e70c0e
for HashBlobReader and HashBobWriter, add destructors that closes read/write handles if not closed already. Since this should not happen if the class is used properly,  log a Warn if destructor is called without handles being closed ( Hopefully we catch any missing close() calls this way)
eb40ffa
Have HashBlobReader take read handle instead of a file path as argument. If open() throws an exception, we don't need to worry about HashBlobReader being ever created ( thus no need to handle cases of HashBlobReader.close() without a read handle)   
4327f9d
906e8b0
10c4551
Removed StreamBlobDecryptor's way of reading from BlobFile by using consumer/producer pattern. Now we have StreamBlobDecryptor just utilize BlobFile.open_for_reading() to get a read handle, and use a deferToThread for …
> Fixes to Blob (unify way to read from BlobFile, move conf.py BLOB_SIZE  )

- CHANGELOG.md
- lbrynet/tests/unit/core/client/test_ConnectionManager.py
Addresses #511. Previously, the test yielded to obtain the result of `connection_was_made`, but the assertions were made in sequential order. Sometimes the result of both connections would be returned before resuming the test, failing the assertions. Instead, this adds a callback to verify the result of each connection, then yields to get both Deferred results.
> Fix failing ConnectionManager unit test

- CHANGELOG.md
- lbrynet/daemon/auth/server.py
`publish` and `channel_new` will both create a claim transaction - this can result in a race condition where the lbryum coin chooser selects the same utxo to spend for both claims, and only the first call to go through succeeds.
Currently, `publish` calls and `channel_new` calls are run sequentially (to avoid the same race condition between concurrent `publish`/`channel_new` calls), but on a per-function basis. This fixes the race condition by using a common deferredSemaphore for all methods decorated with `@AuthJSONRPCServer.queued`
> Fix race condition between publish and channel_new

- CHANGELOG.md
- lbrynet/core/BlobManager.py
- lbrynet/tests/unit/core/test_BlobManager.py
Addresses #786. The blob hash should be removed from the `BlobManager.blobs` dictionary when the blob is deleted.
> Delete blob hash from list when blob is deleted

- CHANGELOG.md
- lbrynet/core/Session.py
- lbrynet/core/client/BlobRequester.py
- lbrynet/core/client/DHTPeerFinder.py
- lbrynet/core/server/DHTHashAnnouncer.py
- lbrynet/dht/node.py
- lbrynet/tests/mocks.py
- lbrynet/tests/unit/core/server/test_DHTHashAnnouncer.py
Continuing from https://github.com/lbryio/lbry/pull/968
Removed the "if" statement in dht.node.getPeersForBlob(), where it did some strange workaround for filtering localhosts from the results. 
I added argument "filter_self" to DHTPeerFinder.find_peers_for_blob() where it will filter itself from peer results if True, this option is needed when downloading blobs since you don't want to download blobs from yourself. In other use cases, such as API command peer_list, filter_self is defaulted to False so you will be able to find yourself. Before https://github.com/lbryio/lbry/pull/968, the filtering of itself was done in the DHT code and would actually affect availability. Now it is done purely outside of the DHT code so it has no impact on availability.
In order for DHTPeerFinder to know …
> Don't filter out local node ID when returning peer list (continued) 

- CHANGELOG.md
- lbrynet/daemon/Daemon.py
- lbrynet/file_manager/EncryptedFileDownloader.py
- lbrynet/reflector/client/client.py
- lbrynet/tests/mocks.py
This removes claim information attached to files, and implements the fix for https://github.com/lbryio/lbry/issues/981
9502b29 - remove the claim information from file related API daemon commands
4aa3cf7 - reflector would use lbry_file.name, for logging purposes, use lbry_file.file_name
1527304 - fix test for above change
d17d410 -when calling API command get, it would check to see if it had the file by looking up the claim_id. Instead, look up by the sd_hash, also fixes https://github.com/lbryio/lbry/issues/951
1bd620a - when calling API command get, it would check to see if there was an ongoing download by looking up the claim_id, also look up by sd_hash, also fixes https://github.com/lbryio/lbry/issues/951
I assigned @kauffj as a reviewer here, he does not have to review this but he …
> Remove claim information from files

- CHANGELOG.md
- lbrynet/core/server/DHTHashAnnouncer.py
This will prevent pile up in the announce queue temporarily while we work on https://github.com/lbryio/lbry/pull/961
> increase SINGLE_HASH_ANNONCE_DURATION from 1 to 5

- CHANGELOG.md
- lbrynet/daemon/auth/server.py
* Fixed sending error messages for failed api requests
* Don't set HTTP error codes for failed api requests, conform to http://www.jsonrpc.org/specification#error_object
> fix api error responses

- CHANGELOG.md
- lbrynet/core/Wallet.py
- lbrynet/daemon/Daemon.py
- lbrynet/tests/unit/core/test_Wallet.py
* Re-use addresses used for lbrycrd info exchange, this was a significant source of address bloat in the wallet
* Remove manual saving of the wallet in from lbrynet, let lbryum handle it
> prevent wallet bloat from lbrycrd info exchange

- CHANGELOG.md
- lbrynet/daemon/Daemon.py
- lbrynet/daemon/Publisher.py
- lbrynet/file_manager/EncryptedFileDownloader.py
- lbrynet/file_manager/EncryptedFileManager.py
- lbrynet/lbry_file/client/EncryptedFileDownloader.py
- lbrynet/reflector/server/server.py
- lbrynet/tests/functional/test_reflector.py
depends on https://github.com/lbryio/lbry/pull/983 . Reflector server now adds file to file manager. Needed to make a few structural changes to make this happen.
ManagedEncryptedFileDownloader had a function load_file_attribute() which is used to load claim information along with the sd_hash. Since #983 removes claim information from files, now all this function does is load the sd_hash. Move this task to the base class EncryptedFileDownloader in function set_stream_info() where it gets stream information (cleaner since we have less setup functions that needs to be run in order to load file information). 
EncryptedFileManager.add_lbry_file() has a mandatory payment_rate_manager argument which is annoying for users to specify (they need to have access to Session class, which …
> Add lbry file manager to reflector server

- lbrynet/daemon/Daemon.py
We removed this from the parameters, but the CLI docs still show it as an option.
> remove download_directory from options

- CHANGELOG.md
- lbrynet/conf.py
- lbrynet/daemon/Daemon.py
- lbrynet/file_manager/EncryptedFileManager.py
This allows easily specifying the `reflector_servers`, `lbryum_servers`, and `known_dht_nodes` in the config file
> Support lists of address:port in the config file

- CHANGELOG.md
- lbrynet/core/Session.py
- lbrynet/core/client/DHTPeerFinder.py
- lbrynet/dht/node.py
This PR addresses #1093 by periodically attempting to re-join the DHT if the node routing table is empty.
Check is performed every 60 seconds.
This fix required some refactoring, therefore I did split my work into several commits, hoping to make the review easier.
> Re-join the DHT if the node has no active peers

- CHANGELOG.md
- lbrynet/core/utils.py
- lbrynet/daemon/Daemon.py
- lbrynet/tests/unit/core/test_utils.py
This is a fix for Issue #895 :
The shape of the claim data appears to have changed, from `['stream']['source']['source']`
to `['claim']['value']['stream']['source']['source']`.  I changed the path, and also wrote a utility function to safely delve along the path and return None if it doesn't work.  If that
happens, I log a warning so that if the shape changes again we know exactly where to look
and can easily see what the problem is from the logs.
I also found that attempting to get the blob_list via URI of an item that hadn't been downloaded
resulted in an error:
```
lbrynet.core.Error.NoSuchSDHash: 92b8aae7a901c56901fd5602c1f1acc0e63fb5492ef2a3cd5b9c631d92cab2e060e2a908baa922c24dee6c5229a98136
```
Whereas attempting to search via the `sd_hash` param performed normally; I've added the …
> API call to blob_list with uri parameter now succeeds

- CHANGELOG.md
- lbrynet/conf.py
- lbrynet/daemon/DaemonCLI.py
When starting a daemon with a different configuration,
the same should also be used by the cli tool.
Add the --conf flag to the cli command to allow using a
custom config file.
Signed-off-by: Antonio Quartulli <antonio@mandelbit.com>
> fixes for the --conf flag

- CHANGELOG.md
- lbrynet/core/Wallet.py
- lbrynet/daemon/Daemon.py
- lbrynet/tests/unit/core/test_Wallet.py
Fixes updating a claim when update's bid amount is greater than wallet balance but it can use the claim's original amount to complete the transaction.
> Include existing claim amount in the max biddable amount for a publish

- lbrynet/txlbryum/client.py
- lbrynet/txlbryum/errors.py
- lbrynet/txlbryum/factory.py
This adds a client protocol factory for communicating directly with lbryum server without going through lbryum client. This can replace most of the `_run_cmd_as_defer_to_thread` calls in `Wallet`.
> add stratum client protocol

- CHANGELOG.md
- lbrynet/daemon/Daemon.py
Simple balance check before calling get_max_usable_balance_for_claim - matches what happens on the claim.
Also provide clearer error message about maximum amount
> update channel balance checking to match claim

- CHANGELOG.md
- lbrynet/conf.py
- lbrynet/daemon/Daemon.py
- lbrynet/database/migrator/dbmigrator.py
- lbrynet/database/migrator/migrate7to8.py
- lbrynet/database/storage.py
- lbrynet/file_manager/EncryptedFileManager.py
- lbrynet/reflector/client/client.py
-add `reflected_stream` table to the database to track reflector uploads so we don't check reflector server unnecessarily 
-increase the default `auto_re_reflect_interval` to a day
> track successful reflector uploads in sqlite

- CHANGELOG.md
- lbrynet/core/client/ClientProtocol.py
`cancel` call can trigger error handlers, which in turns makes the object None, which makes the next line fail. Reordering lines ensures we collect the deferred before the object attribute becomes None by error handlers.
Steps to reproduce:
Option 1:
1. Download with a very tight impossible timeout, like 4 or 5. (adjust at will, maybe my connection is _that_ bad)
Option 2 (easier):
1. Cancel (file_set_status stop) an ongoing download.
> Fix stop raising `NoneType' object has no attribute 'finished_deferred'

- CHANGELOG.md
- lbrynet/core/BlobManager.py
- lbrynet/core/Session.py
- lbrynet/database/storage.py
- lbrynet/dht/datastore.py
- lbrynet/dht/node.py
- lbrynet/dht/protocol.py
-accept invalid store tokens for the first expire-time after startup
> load all finished blobs into the node datastore

- CHANGELOG.md
- lbrynet/conf.py
- lbrynet/dht/iterativefind.py
- lbrynet/dht/peerfinder.py
It already stops when it finds a value, so the other stop conditions only makes sense when collecting nearest nodes around a value and not while navigating the network looking for values.
> Stop conditions on find value

- CHANGELOG.md
- lbrynet/dht/iterativefind.py
During iterative find a peer can go ignored. It will occupy the search querying something that will be discarded, so this PR removes it from the shortlist so its not even considered on probing.
> Dht shortlist without ignored

- CHANGELOG.md
- lbrynet/core/client/BlobRequester.py
If the connected peer doesnt have a blob we need we would trigger the same request in a loop, causing a high CPU usage for the time the download is stuck.
> Fix high cpu usage on incomplete streams

- CHANGELOG.md
- lbrynet/daemon/Daemon.py
Currently, when a bid is **pending**, you can not increase another bid unless you have the **total amount** in your **balance**. You have to **wait** for any **pending** claims to **resolve** before you can do this.
The current error message, in this case, can give the **impression** that the app is **broken**.
This new error message **amendment** will prevent **angry** users from launching vigilante attacks on the LBRY HQ and mass riots!
> A More Informative Error Message

- CHANGELOG.md
- lbrynet/blob/writer.py
- lbrynet/core/HTTPBlobDownloader.py
- lbrynet/tests/unit/core/test_HTTPBlobDownloader.py
While trying to solve a bug reported by @tzarebczan and @lyoshenka I saw it wasn't behaving properly with two layers of error handling and complexity was above desired, so I simplified error handling to one layer and used a semaphore instead of the looping call. This version downloads the next 2 blobs concurrently with peers, stops immediately when request and handle better cases where p2p wins (or some other part of our code asks writers to stop).
I allowed 2 concurrent downloads because that's what worked faster on my bad connection, but I'm happy to change back to 1 if necessary.
> refactor mirroring

- CHANGELOG.md
- lbrynet/file_manager/EncryptedFileDownloader.py
- lbrynet/tests/mocks.py
> unset mirror for tests, but let it be read on normal usage

- lbrynet/daemon/auth/server.py
It used to show a user friendly message, now it shows that the port is already bound, which is too technical. Added some more text to explain that's because it's either already running or another application is using that port.
> improve error message when daemon is already running

- lbrynet/wallet/manager.py
- lbrynet/wallet/resolve.py
- tests/integration/wallet/test_transactions.py
> Fixes for inexistent URIs error format and implementation of get_best_block_hash

- lbrynet/dht/node.py
- tests/functional/dht/test_contact_rpc.py
"peer_ping" for inexistent ids currently raises:
`builtins.TypeError: invalid type to compare with Contact: <class 'bytes'>`
Fixed and added a test for it.
> Fix peer_ping command

- lbrynet/dht/contact.py
- lbrynet/dht/node.py
- lbrynet/dht/routingtable.py
This PR filters out nodes that are already being contacted from replacement candidates list, giving them time to reply and avoid race conditions that can cause floods.
> reduce routing table ping flood

- lbrynet/__init__.py
- lbrynet/cli.py
- lbrynet/core/system_info.py
- setup.py
`lbrynet --version` should print 1-2 lines of version info, not a 20-line dict with extraneous stuff
> fix lbrynet --version

- lbrynet/conf.py
- tests/unit/test_conf.py
Fix for [#1302](https://github.com/lbryio/lbry/issues/1302)
Changes:
- if provided config file does not exist, throw descriptive error with absolute path of a file
- throw ValueError, not AssertionError if provided config file has unsupported extension
- simple test for loading file
> --conf option improvements

- lbrynet/wallet/transaction.py
@tzarebczan has a wallet with legacy JSON claims
part of, but not yet solves #1530 
It solves the case but something else must ensure decode errors doesn't stop the history sync.
> use smart_decode on transaction parsing to support legacy claims

- lbrynet/dht/protocol.py
this makes retry happens at the protocol level, so we don't disrupt higher level operations due packet loss, which is expected on UDP protocols anyway.
> [DHT] retry on protocol level

- lbrynet/dht/node.py
- lbrynet/dht/routingtable.py
- lbrynet/extras/daemon/Daemon.py
- routing table only populating one or two buckets on startup. This caused poorer connectivity before blob and peer searches fill out the buckets.
- `routing_table_get` not including empty buckets
- query ids in the middle of the bucket range instead of random ids in the range when populating buckets.
> Better initialization of routing table buckets

- setup.py
- tests/mocks.py
- tests/test_utils.py
- tests/unit/core/server/test_BlobRequestHandler.py
- tests/unit/core/test_HTTPBlobDownloader.py
- tests/unit/core/test_Strategy.py
- tests/unit/lbrynet_daemon/auth/test_server.py
- tests/unit/lbrynet_daemon/test_Daemon.py
- tests/unit/lbrynet_daemon/test_Downloader.py
- tests/unit/lbrynet_daemon/test_ExchangeRateManager.py
- tests/unit/test_customLogger.py
Not much to it other than what's asked in #1657; the module `mock` is refactored and replaced with `unittest.mock`; the builtin version. Additionally, `mock` is removed from `setup.py` since Python 3.7 already contains it. Some simple refactoring is done for compliance with `pylint` and some import stubs were whitespace delimited in order to separate the import sections into builtin, third-party and in-project modules. As a bonus, the function `resetTime` is renamed to `reset_time`.
> Removes third-party mock dependency

- lbrynet/extras/daemon/Daemon.py
- lbrynet/extras/daemon/Publisher.py
- lbrynet/extras/daemon/mime_types.py
… extension
when publishing a file whose media type is not known, use a generic media type that includes the filename extension
there's no way to know what kind of file is in a stream without downloading the manifest blob. 
> include file extension in media-type metadata for unknown media types

- lbrynet/extras/daemon/Daemon.py
If an uploaded file had a directory that was removed, or if the old download directory doesn't exist, use the default.
> fix unavailable download directory

- lbrynet/extras/daemon/Components.py
- lbrynet/extras/daemon/Daemon.py
- lbrynet/extras/daemon/DaemonConsole.py
- lbrynet/extras/daemon/analytics.py
- lbrynet/extras/daemon/storage.py
- tests/integration/cli/test_cli.py
- tests/integration/wallet/test_commands.py
This removes the use of `treq` and `twisted` modules from being used in `analytics.py`. It also removes the old `LoopingCall` mechanism and replaces its manager component with a `dict` that stores the looping Tasks as a `name -> Task` key value pair, which makes use of the `looping_call` function from `lbrynet.extras.daemon.storage.py`. Modification is also made to the `looping_call` function in order to catch the task cancellation error when being wrapped as a task coroutine. 
Instead of `treq`, the `aiohttp` library is used, although instead of creating a `ClientSession` object, I use the `aiohttp.request` ContextManager to set the `Api`'s cookies as that of the response's.
Why is this change …
> Removes twisted dependency from lbrynet.extras.daemon.analytics.py

- lbrynet/extras/daemon/Daemon.py
- lbrynet/extras/wallet/server/session.py
- lbrynet/schema/uri.py
- tests/unit/schema/test_lbryschema.py
added `claim_name`, `channel_name`, `contains_channel`
renamed `is_channel` to `contains_channel`
now `is_channel` returns true iff the uri contains just the channel and not a path
> added additional fields to uri parser to return consistent results

- lbrynet/extras/daemon/mime_types.py
It's a container type very similar to mp4. Someone recently added one in the community top bids section.
> add `.m4v` video format type

- lbrynet/extras/cli.py
- lbrynet/extras/daemon/Daemon.py
backwards-incompatible: `help` jsonrpc command has been dropped, use `lbrynet --help` instead.
backwards-incompatible: `resolve_name` command has been dropped, use `resolve` instead.
backwards-incompatible: `commands` jsonrpc command has been dropped, a better version could be added in the future, feedback and use cases greatly appreciated.
> dropped help, commands and resolve_name commands

- lbrynet/conf.py
- lbrynet/extras/cli.py
- lbrynet/extras/daemon/Daemon.py
- tests/unit/test_conf.py
backwards-incompatible: setting max key fee via command line now uses the following format (via yaml config is unchanged): `--max-key-fee 40.0 USD`
backwards-incompatible: `--disable-max-key-fee` is now replaced by `--no-max-key-fee` on command line and in yaml file just `max_key_fee: null`
> refactored --max-key-fee to be more ergonomic

- lbrynet/extras/daemon/Daemon.py
backwards-incompatible: `settings set` API has changed to `settings set <key> <value>`
> more flexible `settings set <key> <value>` command

- lbrynet/blob_exchange/client.py
- lbrynet/blob_exchange/downloader.py
- lbrynet/blob_exchange/server.py
- lbrynet/conf.py
- lbrynet/dht/node.py
- lbrynet/extras/cli.py
- lbrynet/extras/daemon/Components.py
- lbrynet/extras/daemon/Daemon.py
- lbrynet/extras/daemon/storage.py
- lbrynet/stream/assembler.py
- lbrynet/stream/downloader.py
- lbrynet/stream/managed_stream.py
- lbrynet/stream/stream_manager.py
- lbrynet/utils.py
- scripts/download_blob_from_peer.py
- scripts/repair_0_31_1_db.py
- scripts/time_to_first_byte.py
- tests/integration/wallet/test_commands.py
- tests/unit/blob_exchange/test_transfer_blob.py
- tests/unit/stream/test_assembler.py
- tests/unit/stream/test_downloader.py
- tests/unit/stream/test_reflector.py
- add `fixed_peer_delay` setting, defaulting to 2.0
- raise the default `max_connections_per_download` from 5 to 8
- refactor StreamDownloader
- refactor peer accumulation for a download to use `Node.accumulate_peers`, which searches for hashes added to a `Queue` and sends discovered peers into a result `Queue`.
- refactor `BlobDownloader` to be the only blob downloader class, used both for downloading single blobs and for downloading blobs for a stream.
- score peers based on if a blob download succeeds or not, prioritize connecting to higher scoring peers
- remove `asyncio.Lock`, use `Queue`s, fix download race conditions
- fix `file list` values set to `None` when they shouldn't be
- fix content claim updates for `file list`
- fix saving the file path and download directory during …
> Download and publish fixes

- lbrynet/extras/daemon/Daemon.py
- lbrynet/stream/stream_manager.py
backwards-incompatible: remove `sources` argument from `publish`
> Fix publishing an update where we don't have the previous stream

- lbrynet/stream/assembler.py
- lbrynet/stream/managed_stream.py
- lbrynet/stream/stream_manager.py
also fixes deleting previous streams (but not assembled/published files) for a claim being updated
> Fix deleting incomplete downloads when they are stopped

- lbrynet/blob/blob_file.py
- lbrynet/blob_exchange/client.py
- lbrynet/blob_exchange/downloader.py
- lbrynet/conf.py
- lbrynet/dht/node.py
- lbrynet/dht/protocol/protocol.py
- lbrynet/stream/assembler.py
- lbrynet/stream/downloader.py
- tests/unit/blob_exchange/test_transfer_blob.py
- bypass response parser during blob downloads
- peer score now accounts for rough speed (bytes transferred over time since the connection attempt)
- reuse connections on downloads when possible, skipping the time it takes to connect
- penalize peers who gets cancelled due not connecting fast enough to compete for the download
- check free connection slots during downloads, instead of just new peers, so peer slots are replaced as soon as possible, solving situations where the download used to get stuck waiting on new peers while having enough to work
- remove ping queue lock
- fix race condition where an open blob about to be written would be opened again, raising errors
- tune default configuration for slow connections: raised `blob_download_timeout` to match  `download_timeout` while …
> Refactor peer scoring and maintain connections to fix stuck downloads, remove locking from ping queue

- lbrynet/blob/blob_file.py
- lbrynet/blob/blob_manager.py
- lbrynet/blob_exchange/client.py
- lbrynet/extras/cli.py
- lbrynet/extras/daemon/storage.py
- lbrynet/stream/stream_manager.py
- scripts/time_to_first_byte.py
* populate the stream manager from a single batched db query, then get the channel names as separate queries (substantially faster)
* speed up blob manager startup
* speed up blob hash character validation
* fix `reflect_streams` setting not being followed
* turn on debugging with the event loop when in running verbose
* limit the number of blobs queried for announcement
> Improve startup time

- lbrynet/extras/daemon/Components.py
binds peer port to the external port - the redirects are set to the internal.
> listen on internal port instead of upnp redirect

- lbrynet/dht/constants.py
- lbrynet/dht/protocol/protocol.py
- lbrynet/dht/protocol/routing_table.py
- tests/unit/dht/protocol/test_protocol.py
- tests/unit/dht/routing/test_kbucket.py
-prevent duplicate ids in the same bucket
-prevent the same address/port from appearing under multiple ids in the routing table
-fix updating the contact triple in the peer manager and on the peer object
> Test and fix edge cases for adding peers to routing

- setup.py
I've frequently had this problem with multiple packages, but the current one causing issues is the `attrs` module, which gets automatically installed by `aiohttp`. However, `aiohttp` has a loose requirement of `attrs>=17.3.0`, whereas `torba` has a strict requirement of `attrs==18.2.0`. 
This fixes that issue by simply moving `torba` to the top in `setup.py`.
> Fixes issue causing packages incompatible with torba getting installed [attrs==18.2.0]

- lbrynet/conf.py
- lbrynet/extras/daemon/Daemon.py
- lbrynet/extras/daemon/comment_client.py
- tests/integration/test_comment_commands.py
Comments are now available in the LBRY-SDK. 
The following commands are available at the moment:
```
claim_metadata  -- Really useless at the moment
get_comments
make_comment
reply_to_comment
get_comment_thread
```
LBRY needs a way to integrate a comment system into the API, and this paves the way to that. This is a very primitive version and is far from complete. However it's ready enough to be placed into the SDK for use by all people. 
Just normal lbrynet behavior
Allows you to add and view comments on claims that are on the lbry network
Features like upvoting and downvoting exist in the serverside for our API, however there are limitations that …
> adds lbrynet commands `comment_list` and `comment_create` which talk to a comment server

- lbrynet/extras/daemon/json_response_encoder.py
backwards-incompatible: RPC output for txos/claims added a few new fields: `claim_op`, `value_type`, `protobuf` and changed a few were renamed: `signing_channel` and `is_channel_signature_valid`, see docs for explanation of these fields.
backwards-incompatible: Due to substantial protobuf changes, the `value` field in JSON responses has changed: `value['thumbnail_url']` is now a dictionary with `url` key: `value['thumbnail']['url']`, `sd_hash` is now in `value['source']['sd_hash']`.
> renamed txo sub_type to value_type in txo json encoder output

- scripts/Dockerfile.wallet_server
this was being done before, but got lost in between. uvloop needs to be installed on the container so it can be used by torba server
> install uvloop on wallet server docker image and default to it

- lbrynet/extras/daemon/Daemon.py
- lbrynet/wallet/manager.py
- lbrynet/wallet/network.py
- lbrynet/wallet/server/session.py
- scripts/generate_json_api.py
- tests/integration/test_claim_commands.py
backwards-incompatible: `block_show` command is no longer available in the API, users should run a full node if they need access to blocks
> removed `block_show` command from API

- lbrynet/extras/daemon/Daemon.py
> `account_list` defaults to 0 confirmations for balance

- lbrynet/blob_exchange/client.py
- lbrynet/extras/daemon/Components.py
- lbrynet/extras/daemon/migrator/dbmigrator.py
- lbrynet/extras/daemon/migrator/migrate10to11.py
- lbrynet/extras/daemon/storage.py
- lbrynet/schema/claim.py
- lbrynet/stream/managed_stream.py
- lbrynet/stream/stream_manager.py
- lbrynet/testcase.py
- tests/integration/test_file_commands.py
- tests/integration/test_streaming.py
Database changes:
- add `saved_file` and `content_fee` columns to `file` table
- drop not null constraints for `file_name` and `download_directory` in the `file` table
Fixes:
-  ``` BLOCKER - see a download path / written bytes even though I deleted the file. This used to update right away. This is important for the app since it would try to stream from the file which doesn't exist```
-  ```BLOCKER? incomplete files continue to retry (this is different from old behavior and probably should be handled in the connection manager). Had trouble shutting down the sdk. On restart, it would try to start/stop the file. Not sure if it actually tried to complete it, but it didn't look like it. Need to make sure that the file will retry on restart at least (old behavior)```
> add saved_file and content_fee columns to file table

- .pylintrc
- lbrynet/dht/constants.py
- lbrynet/dht/protocol/protocol.py
- lbrynet/dht/serialization/bencoding.py
- lbrynet/dht/serialization/datagram.py
- tests/unit/dht/protocol/test_protocol.py
- tests/unit/dht/serialization/test_datagram.py
- tests/unit/dht/test_blob_announcer.py
- fixes #2244
- reduce the max DHT datagram size to 1400 bytes
- truncate `contacts` field of find_value response datagrams to the k closest (8)
- truncate peers in find_node response datagrams to the 2k closest (16)
- remove `contacts` field from find_value responses beyond `page` 0 (the first/default)
- deterministically shuffle the peers for a blob in a find_value response
- add optional `page` argument to `find_value` and `p` field to find_value responses containing the number of pages of k peers for the blob
- test one blob being announced by 150 different peers to one peer
- speed up pylint and remove some disabled checks
> paginated deterministically shuffled find_value

- lbrynet/extras/daemon/Daemon.py
This PR puts the media server port binding into a separate try/except so when it fails to bind the port, the logs correctly say what happened.
> separate try/except for media server

- lbrynet/conf.py
Not sure where spv3 will be yet. We can probably repurpose lbryumx2/3/4 once we go live, so we'll make sure to add those before release.
Link to issue:
> update wallet servers

- lbry/tests/integration/test_wallet_server_sessions.py
- torba/torba/rpc/jsonrpc.py
- torba/torba/server/daemon.py
- torba/torba/server/env.py
- torba/torba/server/peer.py
- torba/torba/server/peers.py
- torba/torba/server/server.py
- torba/torba/server/session.py
- fix sockets not being torn down after socket timeout/no route to host errors
- fix lbrycrd rpc calls not being pooled
- fix uvloop setting being ignored
- fix local `getinfo` rpc
> Fix wallet server session bloat from unhandled socket errors

- lbry/lbry/conf.py
- lbry/lbry/extras/cli.py
- lbry/lbry/extras/daemon/Component.py
- lbry/lbry/extras/daemon/Components.py
- lbry/lbry/extras/daemon/Daemon.py
- torba/torba/client/basenetwork.py
There is more that can be improved here. Starting and stopping the daemon is still somewhat inconsistent. The daemon can shut down by raising SystemExit, or it shut down by raising GracefulExit. Is that right, or should there only be one way to do it?
fixes #2231
> let daemon be shut down before it has fully started

- lbry/lbry/blob_exchange/client.py
- lbry/lbry/blob_exchange/downloader.py
This is for the case where a blob has many peers but a large portion can't be connected to, which causes it to take a long time to get to a potentially fast (or at least connectable) peer.
> Probe if peers can be connected to during blob downloads to more quickly skip bad peers

- lbry/lbry/extras/daemon/Daemon.py
- lbry/lbry/extras/daemon/comment_client.py
- lbry/tests/integration/test_comment_commands.py
- lbry/tests/unit/comments/test_comment_signing.py
Adds the command `comment_abandon` with the following signature:
```python
def comment_abandon(comment_id: str) -> dict:
return {
comment_id: {
"deleted": bool
}
}
```
Accepts a `comment_id` and attempts to query the channel that the comment belongs to. 
If the user owns the channel, a signature is then made with the following encoding:
```
`comment_id` + `channel_claim_hash`
```
This signature is then validated by the comment server, returning the outcome of the request accordingly. 
- Add unit tests
> Adds `comment abandon` command

- lbry/lbry/extras/daemon/Daemon.py
- lbry/lbry/testcase.py
- lbry/lbry/wallet/account.py
- lbry/lbry/wallet/database.py
- lbry/tests/integration/test_chris45.py
- lbry/tests/integration/test_claim_commands.py
- lbry/tests/integration/test_transaction_commands.py
backwards-incompatible: `account balance` no longer returns an integer. It now returns a dictionary with granular balances. The integer it used to return is now under `available` key on that new dictionary format.
> add granular balances

- lbry/lbry/extras/daemon/Components.py
- lbry/lbry/extras/daemon/Daemon.py
- lbry/lbry/extras/daemon/analytics.py
- lbry/lbry/stream/stream_manager.py
- lbry/tests/unit/stream/test_stream_manager.py
- fixes https://github.com/lbryio/lbry-sdk/issues/2380
- fixes  https://github.com/lbryio/lbry-sdk/issues/2381
- add `wallet_server` and `error_message` to time to first bytes analytics event
> Add `connected_servers` field to wallet status and improve analytics for wallet related download errors

- lbry/lbry/stream/managed_stream.py
check blob hashes from completed_blob_hashes instead of heavier function calls
> Faster file list

- torba/torba/server/cli.py
this way you don't have to pass it when you call `docker run`, but you can still use another coin from `docker run` if you want to
> default wallet server to LBC coin

- lbry/lbry/extras/daemon/Daemon.py
- lbry/lbry/extras/daemon/json_response_encoder.py
- lbry/lbry/wallet/account.py
- lbry/lbry/wallet/constants.py
- lbry/lbry/wallet/database.py
- lbry/lbry/wallet/ledger.py
- lbry/tests/integration/test_claim_commands.py
- torba/tests/client_tests/unit/test_database.py
- torba/torba/client/basedatabase.py
- torba/torba/client/baseledger.py
release-text: This release includes changes to the client wallet database structure and will require a full re-sync of your transactions; this will happen automatically on startup.
> Channel claims and certificates no longer need to be in the same account to sign stream claims.

- lbry/lbry/schema/mime_types.py
We used to have support for flac, adding it back in: https://filext.com/file-extension/FLAC
> add Flac mime type

- torba/tests/client_tests/integration/test_network.py
- torba/torba/client/basenetwork.py
- torba/torba/server/env.py
- torba/torba/server/session.py
Adds the following new config variables (which currently are environment variables but are subject to change):
`DESCRIPTION` (str): simple server description
`DAILY_FEE` (int): daily fee in dewies
The fee is collected to the existing configuration for donation address, so other electrum protocol clients can understand it. Also, a 0/unset `DAILY_FEE` with a `DONATION_ADDRESS` keeps meaning what wallet operators are used to:
`DONATION_ADDRESS` (str): address for the daily fee/donations
We might reconsider `BANNER_FILE` but throwing up an entire file through `server.features` doesn't seem ok, `DESCRIPTION` should be a short description of the server (like a title, for server lists) and not a full shell-style banner.
> wallet server: add options to set server description, payment address and daily fee

- lbry/lbry/extras/daemon/Daemon.py
There seems to have been missing brackets for `channel_ids` and `not_channel_ids` arguments in `claim_search` docstring. Grouping them together using `[]` (as they are optional) seems to have fixed #2405.
> Fix docopt for `claim_search`

- lbry/lbry/stream/stream_manager.py
- lbry/tests/integration/test_file_commands.py
- lbry/tests/unit/stream/test_stream_manager.py
Addressing #2051. Added a unit test which fails before the fix, and passes after. Also, I verified that paid downloads fail before the fix, download successfully after, and the payment proceeds as expected.
> Fix failing key payment for null max key fee

- lbry/lbry/conf.py
- lbry/tests/unit/test_conf.py
This fix is meant to address #2050. Instead letting argparse check the number of arguments, the arguments are cast to a list whose length is checked in `_parse_list()`. It was tested via both CLI and yaml, and I extended some of the unit tests in `test_conf.py`.
> Enable to set max_key_fee to null via cli

- lbry/lbry/extras/cli.py
- lbry/tests/unit/test_cli.py
This is a simple change to address #1832. Currently, when claim name is a digit, e.g. '1234' (docopt automatically converts to string), it is normalized to integer. Since it has been published as a string, the comparison then fails and the claim is not retrievable via either `lbrynet file list --claim_name=1234` or `lbrynet file list --claim_name="1234"` (tested for both).
> Handle claim_name as a string

- torba/tests/client_tests/integration/test_network.py
- torba/torba/client/basenetwork.py
A previously unexpected state could occur where we are online but the sessions aren't available (connection is starting or was lost very recently and is about to be closed). During this state we would ask for a fastest connection but it would hit an empty list and throw an error, which isn't being logged. The logging issue will be handled separately.
This PR also adds a new `INFO` log message for when the wallet server switching task exits with `Wallet client switching task stopped.`. That may be removed in future versions but for now it helps knowing whenever we hit this scenario as this task should live until the daemon stops.
> handle intermediate state on wallet client sessions

- lbry/lbry/wallet/server/db/trending.py
@eukreign is this all I need to change, or does `TRENDING_DATA_POINTS` need to be changed as well. the comment on `TRENDING_DATA_POINTS` was not clear to me.
Does this change require a resync for the wallet server?
> change trending window to 6 hours

- lbry/lbry/dht/peer.py
- lbry/lbry/utils.py
This fixes downloading from fixed peers not working on certain mobile networks (Sprint, T-Mobile)
> fix resolving fixed peers from an ipv6 connection

- lbry/lbry/extras/cli.py
- lbry/tests/integration/test_cli.py
Addressing #1739, this PR makes the `--verbose` param behave as per documentation: when it is specified as flag, i.e.  `--verbose`,  debug level is set for `lbry` logger as default, and when a list of strings is passed, debug level is set to each as a logger. This does not check that the loggers are valid modules.
> Make `--verbose` param behave as per documentation

- torba/tests/client_tests/integration/test_network.py
- torba/tests/client_tests/integration/test_transactions.py
- torba/tests/client_tests/unit/test_account.py
- torba/tests/client_tests/unit/test_coinselection.py
- torba/tests/client_tests/unit/test_database.py
- torba/tests/client_tests/unit/test_hash.py
- torba/tests/client_tests/unit/test_headers.py
- torba/tests/client_tests/unit/test_ledger.py
- torba/tests/client_tests/unit/test_script.py
- torba/tests/client_tests/unit/test_stream_controller.py
- torba/tests/client_tests/unit/test_transaction.py
- torba/tests/client_tests/unit/test_wallet.py
Use `assertListEqual`/`assertTupleEqual`/`assertDictEqual` instead of `asserEqual`.
This PR doesn't conflict with #2498, in which `assertTrue`/`assertFalse` replaces `assertEqual`.
> use more specific asserts in torba tests

- lbry/lbry/schema/mime_types.py
https://gingertech.net/2008/09/05/new-ogg-mime-types-ratified/#targetText=The%20new%20Ogg%20MIME%20types,I%20files%20for%20backwards%20compatibility.
> add oga and ogv mime types

- lbry/lbry/extras/daemon/Components.py
- lbry/lbry/extras/daemon/Daemon.py
- lbry/lbry/wallet/manager.py
- lbry/tests/integration/test_sync.py
- torba/torba/client/wallet.py
backwards-incompatible: commands `account` `lock`/`unlock`/`encrypt`/`decrypt` have been replaced by `wallet` `lock`/`unlock`/`encrypt`/`decrypt`.
> added `wallet` `lock`/`unlock`/`encrypt`/`decrypt` and `status` APIs

- lbry/lbry/extras/daemon/Daemon.py
- lbry/lbry/stream/descriptor.py
- lbry/lbry/stream/managed_stream.py
- lbry/lbry/testcase.py
- lbry/tests/integration/test_file_commands.py
- lbry/tests/unit/stream/test_managed_stream.py
- lbry/tests/unit/stream/test_stream_descriptor.py
This PR is to address #2084. I added a setter to `StreamManager.file_name` property which sanitizes it the input value. Getter sanitizes `suggested_file_name` if necessary. The sanitization strips trailing whitespaces, replaces spaces with underscores and removes all non-alphanumeric characters except for dashes and dots. I added a unit test and will add an integration test if you agree with this approach.
> Sanitize file names before saving

- lbry/lbry/extras/cli.py
- lbry/lbry/extras/daemon/loggly_handler.py
- lbry/tests/unit/test_cli.py
makes setup_logging() params clearer. now you know which parts of `args` and `conf` are actually used and what they do
> refactored logging configuration and added more tests

- lbry/lbry/schema/attrs.py
- lbry/lbry/schema/base.py
- lbry/lbry/schema/claim.py
- lbry/lbry/schema/tags.py
- lbry/tests/integration/test_claim_commands.py
- lbry/tests/unit/schema/test_models.py
fixes #2399. Now, tags are normalized when read, and when claims are created / updated. Duplicate tags (after normalization) are not inserted. Added some unit and integration tests. Maybe `normalize_tag()` and `clean_tags` can be moved to `attrs.py`. (I will merge to rerun the build once the pylint fix is on master).
> normalize tag names (remove duplicates, blank spaces and illegal chars)

- lbry/lbry/schema/claim.py
- lbry/lbry/testcase.py
- lbry/tests/integration/test_claim_commands.py
- lbry/tests/integration/test_file_commands.py
This is a first attempt at approaching, fixes #2492. If the stream type of the source of the original claim is dimensional or playable, the appropriate field is cleared. Other metadata seem to be updating correctly. A simple integration test included.
> clear metadata when file type changes

- lbry/lbry/wallet/server/db/trending.py
- lbry/lbry/wallet/server/db/writer.py
This gets us back to ~7 days, which was originally requested as part of this change.
Will won't require a resync, we'll just start collecting 7 days from the time it's deployed.
> update trending period

- .travis.yml
- lbry/lbry/extras/daemon/Daemon.py
- lbry/lbry/wallet/server/db/full_text_search.py
- lbry/lbry/wallet/server/db/reader.py
- lbry/lbry/wallet/server/db/writer.py
- lbry/tests/integration/test_claim_commands.py
release-text: Wallet server now supports full text searching by using `claim_search` command and passing `--text` argument (note that `--order_by` is ignored when `--text` is passed because it will sort results based on text match ranking).
> full text search in wallet server using `claim_search` via argument `--text`

- lbry/lbry/wallet/network.py
- lbry/lbry/wallet/server/session.py
- torba/torba/client/basenetwork.py
backwards-incompatible: This release includes backwards incompatible APIs and will automatically disconnect clients with an older version when they try to connect.
> bump protocol version

- lbry/lbry/blob/blob_file.py
- lbry/lbry/blob_exchange/downloader.py
- lbry/lbry/blob_exchange/server.py
- lbry/lbry/stream/managed_stream.py
- lbry/tests/integration/test_file_commands.py
backwards-incompatible: This release changes the behavior of downloads that fail to complete. Previously they would be re-attempted automatically. As of this release, download attempts that stop due to all of the blobs not being available will go into a `stopped` state and must be resumed with `file_set_status`, `get`, or `file_save`, or by reading via partial content requests to complete the download (if possible).
> Fix blob request loop

- lbry/lbry/error/README.md
- lbry/lbry/error/__init__.py
- lbry/lbry/schema/claim.py
- lbry/tests/unit/schema/test_models.py
Addressing issue #2441 - I saw your Hacktoberfest post and thought I'd try and contribute. This issue wasn't specifically tagged with the Hacktoberfest label, but it seemed like one I could help with. I added null checking for the attributes with a clearer error message, and unit tests to verify.
> Improving error handling for null values

- lbry/lbry/extras/daemon/Daemon.py
backwards-incompatible: This release changes the error return data structure to be compliant with JSONRPC standard. The fields `name` and `traceback` where moved into the `data` dictionary.
> change returned error data structure to be JSONRPC standard compliant

- lbry/wallet/network.py
In https://github.com/lbryio/lbry-sdk/pull/2728 the client disconnects when it thinks the server is incompatible. This fixes the case where the server returns an error due to it believing the client is incompatible. In both cases the server version is rechecked hourly to see if it becomes compatible.
> disconnect from server that returns rpc error for server.version

- .gitignore
- .gitlab-ci.yml
- lbry/conf.py
- lbry/extras/cli.py
- lbry/extras/daemon/daemon.py
- lbry/file_analysis.py
- scripts/check_video.py
- setup.py
- tests/integration/blockchain/test_transcoding.py
- tests/integration/blockchain/test_wallet_commands.py
Please review and ask questions. Use the script to test files.
Fixes #1988
> added video file validation and optimization when publishing streams (using `--validate_file` and `--optimize_file` arguments)

- setup.py
This fixes some compilation issues for CPython 3.8+ that I was having while running `make install`
```
Running setup.py install for cffi ... error
ERROR: Command errored out with exit status 1:
command: /home/mk/.pyenv/versions/3.8.1/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b0snfbt_/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b0snfbt_/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sv6iwie5/install-record.txt --single-version-externally-managed --compile --install-headers /home/mk/.pyenv/versions/3.8.1/include/python3.8/cffi
cwd: /tmp/pip-install-b0snfbt_/cffi/
Complete …
```
> update cffi to v1.13.2

- lbry/wallet/server/db/trending/ar.py
* The `trending_ar.log` file is only created if `install` is called
* Skip trending calculations except for most recent 5*HALF_LIFE = 670 blocks to speed up initial sync (this was always the intent but was broken).
* Use claim_hash instead of claim_id to identify claims
* No claim_id index required.
The changes are quite simple but I am still testing them.
> fixed some issues with AR trending

- lbry/extras/daemon/daemon.py
- scripts/generate_json_api.py
- tests/integration/other/test_comment_commands.py
Changes the `channel_name`/`channel_id` parameters on the `comment_create` command from being optional to required.
Addresses #2799
> removes ability to comment anonymously

- lbry/wallet/ledger.py
- tests/integration/blockchain/test_claim_commands.py
> when using `--resolve` with local claim `*_list` commands, update resolved result with local metadata (such as `is_mine`)

- lbry/file_analysis.py
> use `os.path.join()` instead of string addition when searching for file analysis binaries

- lbry/conf.py
- lbry/extras/daemon/daemon.py
- lbry/file_analysis.py
- lbry/schema/mime_types.py
- lbry/testcase.py
- scripts/check_video.py
- tests/integration/other/test_transcoding.py
> don't validate and repair files that aren't videos; add maximum video bit rate setting

- lbry/extras/cli.py
- lbry/file_analysis.py
This is a band-aid until `asyncio.create_subprocess_exec` can be replaced with `subprocess` to avoid ProactorEventLoop breaking UDP protocols on windows.
> fix DHT setup and disable ffmpeg on windows temporarily

- lbry/file_analysis.py
- lbry/utils.py
- tests/integration/other/test_transcoding.py
PyInstaller modifies the LD_LIBRARY_PATH variable. This affects the execution of files external to the package. It was affecting the execution of ffmpeg but is handled here as suggested in the documentation at https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations
Fixes #2838
> revert LD_LIBRARY_PATH before calling ffmpeg

- lbry/wallet/server/db/trending/__init__.py
- lbry/wallet/server/db/trending/variable_decay.py
This is the one I've been working on in #tech-trending on Slack. It's similar to the AR algorithm, but with the following modifications, inspired by Tom's idea that in the future large supports should require time locking, but able to be implemented before that's a thing.
* Large, positive LBC changes take time before they affect the trending score. Specificially, the delay is equal to LBC^0.4 blocks, with a maximum delay of 200 blocks.
* Very high trending scores decay at a faster rate than lower scores.
The time delays look like this - people might wonder about it:
```
10 LBC:   2 blocks
100 LBC:  6 blocks
1000 LBC: 15 blocks
10000 LBC: 39 blocks
100000 LBC: 100 blocks
>= 565000 LBC: 200 blocks (edited) 
```
Jeremy and Tom are keen to A/B test this on lbry.tv.
Ultimately, the degree to …
> Trending algorithm with time delay and variable decay rate

- lbry/extras/daemon/daemon.py
- lbry/file_analysis.py
- lbry/schema/claim.py
- scripts/check_video.py
- tests/integration/other/test_transcoding.py
Fixes #2868
1. Verifies that MKV files are WebM compatible
2. Reuses the height/width/duration data from ffmpeg if possible.
> Handle MKV files

- lbry/wallet/header.py
- tests/integration/blockchain/test_wallet_server_sessions.py
> fix estimated timestamp to return integer instead of float

- lbry/extras/daemon/daemon.py
- lbry/testcase.py
- lbry/wallet/ledger.py
- tests/integration/blockchain/test_claim_commands.py
fixes #2847
fixes #2528
fixes #941
> added `txo_spend` command to support liquidating large number of txos (eg. tips) by batching them across several transactions

- lbry/extras/daemon/daemon.py
- lbry/file_analysis.py
- tests/integration/other/test_transcoding.py
-fixes ffmpeg installation being rechecked (reintroduced in https://github.com/lbryio/lbry-sdk/pull/2861)
-don't block `status` on the internet connection check if it was needed
> improve speed of `status`

- lbry/extras/daemon/daemon.py
- lbry/stream/stream_manager.py
- tests/integration/datanetwork/test_file_commands.py
fixes https://github.com/lbryio/lbry-sdk/issues/2873
> support `claim_id`, `channel_claim_id`, and `outpoint` args given as lists of values to match in `file_list`

- Makefile
- lbry/conf.py
Fixes  an error in detecting xdg config locations when XDG_DOWNLOAD_DIR is not present in `user-dirs.dirs`
Lemme know if I've done anything stupid, it seems to work but you never know.
Fixes #2913
> use home directory if xdg directory not found (Linux)

- lbry/extras/daemon/daemon.py
delete line 3616 (duplicate line 3618)
tested on Linux with pycharm venv 
- api.json  with duplicate line:
- fixed api.json doc test result:
> fix duplicate line on api doc

- lbry/conf.py
- tests/unit/test_conf.py
make sure tcp and udp port for dht are int type
Reason for fix (Ubuntu 20.04 and desktop app):
1. Without fix users specify env vars, LBRY_TCP_PORT=34562 and LBRY_UDP_PORT=34562, but then when you run the daemon it complains about string comparisons.
2. With this fix people can download the desktop application, set the above environment variables and have their seeding working with VPN! PIA VPN gives you a randomly assigned port forward port, with this fix a user can now use a VPN (with ENV vars).
> properly handle integer environment values, fixes issue with specifying ports via environment vars

- lbry/conf.py
- lbry/dht/protocol/protocol.py
- lbry/wallet/ledger.py
- lbry/wallet/manager.py
- lbry/wallet/rpc/session.py
- lbry/wallet/server/block_processor.py
- lbry/wallet/server/session.py
- tests/unit/components/test_component_manager.py
-allows raising the transaction cache size, which fixes one way of producing an out-of-sync wallet that erroneously has transactions as unspent
> add `transaction_cache_size` to config

- lbry/conf.py
Have noticed the defaults aren't aggressive enough to stream smoothly (yet). Downgrade max rate to 5500K, higher crf = smaller file size for now.
> more aggressive video transcoding to reduce file sizes

- lbry/conf.py
- lbry/extras/daemon/daemon.py
- lbry/extras/daemon/security.py
- tests/unit/lbrynet_daemon/test_allowed_origin.py
backwards-incompatible: This release requires that no Origin value is passed in HTTP API requests. Electron based apps accessing the SDK will need to make sure that for `POST` requests that they remove the `Origin` from the header, see: https://github.com/electron/electron/issues/7931 . When you want to use the API from web browser the SDK needs to have `allowed_origin` configuration value set to the host from which you want to access the API.
> add `allowed_origin` to config, by default no longer allow any requests which pass Origin in header

- lbry/wallet/rpc/session.py
- lbry/wallet/server/block_processor.py
- lbry/wallet/server/session.py
Minimizes but does not entirely solve https://github.com/lbryio/lbry-sdk/issues/2945 as the cache is invalidated each block and the first slow request can back up further notifications during the same block.
> Improve wallet server address history cache and the rate of sent notifications

- .gitignore
- lbry/conf.py
- lbry/file_analysis.py
New pull request with same commit as this one https://github.com/lbryio/lbry-sdk/pull/2933
Just had to clean up some git stuff.
Issue https://github.com/lbryio/lbry-sdk/issues/2906
> check sample rate and lower if too high

- lbry/schema/mime_types.py
> Web Video Text Tracks Format (WebVTT) is a format for displaying timed text tracks (such as subtitles or captions) using the <track> element.
> The MIME type of WebVTT is text/vtt.
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
> Add webvtt mime type ( subtitles, captions )

- lbry/extras/daemon/daemon.py
- lbry/schema/result.py
- lbry/wallet/server/db/reader.py
- tests/integration/blockchain/test_claim_commands.py
> added `--limit_claims_per_channel` argument to `claim_search` to only return up to the specified number of claims per channel

- docker/docker-compose-wallet-server.yml
Curently new containers do not get provide snapshots from LBRYinc (Wallet and CRD) that causes containers to get into restart loop.
> Fixed docker-compose - no snapshot error

- lbry/schema/url.py
- tests/integration/blockchain/test_resolve_command.py
- tests/unit/schema/test_url.py
> drop the ability to refer to claims by number from the LBRY URL scheme

- lbry/wallet/ledger.py
- lbry/wallet/server/block_processor.py
- lbry/wallet/server/leveldb.py
- lbry/wallet/server/merkle.py
- lbry/wallet/server/session.py
- lbry/wallet/server/storage.py
improves performance of `blockchain.transaction.get_batch` and `blockchain.transaction.get_info`
> store transactions for wallet server in leveldb instead of requesting from lbrycrd

- lbry/wallet/ledger.py
- lbry/wallet/network.py
- lbry/wallet/server/session.py
- revert [single connections to the spv server](https://github.com/lbryio/lbry-sdk/pull/3058/commits/76946c447ffc0abca76a233c353fb410abdc32e8) (use the session pool)
- keep batched transaction fetching for the `inflate_outputs` stage of resolve/claim search
> fix flooding with resolve/claim search

- lbry/wallet/database.py
- lbry/wallet/ledger.py
- bump blockchain.db schema version to cause a one-time resync
> Increase default `tx_cache_size` 

- lbry/extras/daemon/daemon.py
- lbry/wallet/database.py
- lbry/wallet/ledger.py
- lbry/wallet/transaction.py
> significant performance improvement when creating transactions, especially `txo spend`

- docs/api.json
- lbry/extras/daemon/daemon.py
A small correction in API documentation for commonly misspelled words.
> spelling fixes in cli docs

- lbry/extras/daemon/daemon.py
- lbry/wallet/transaction.py
- tests/integration/blockchain/test_claim_commands.py
> fixes transaction signing bug when tx had no change outputs

- lbry/extras/daemon/daemon.py
- lbry/utils.py
- tests/integration/other/test_cli.py
backwards-incompatible: removes `connection_status` field from `status` API call. see PR link for details.
how to differentiate the states of lbrynet `status` wallet connection
- if `wallet.connected` has a value, then it's connected.
- otherwise:
- if `startup_status.wallet` is false, then sdk is still connecting to wallet servers. it will never stop trying till it connects.
- if `startup_status.wallet` is true, then the sdk used to have a wallet server connection but that dropped and it's still trying to reconnect
fixes #3196 
related to #3158
> removed `connection_status` field from the `status` command, use `wallet.connected` instead to determine if SDK is connected to a wallet server

- lbry/extras/daemon/daemon.py
> only return unspent txos if `is_spent` flag is not used

- lbry/extras/daemon/components.py
- lbry/stream/descriptor.py
- lbry/wallet/ledger.py
- lbry/wallet/rpc/jsonrpc.py
- lbry/wallet/server/block_processor.py
- lbry/wallet/server/db/writer.py
- lbry/wallet/server/leveldb.py
- lbry/wallet/server/mempool.py
- scripts/checktrie.py
Hi :wave: I work at [DeepSource](https://deepsource.io), I ran DeepSource analysis on the forked copy of this repo and found some interesting [code quality issues](https://deepsource.io/gh/withshubh/lbry-sdk/issues/?category=recommended) in the codebase, opening this PR so you can assess if our platform is right and helpful for you.
- Remove unnecessary comprehension
- Remove unnecessary use of comprehension
- Remove methods with unnecessary super delegation.
- Iterate dictionary directly
- Refactor the comparison involving `not`
- Remove unnecessary generator
- Add .deepsource.toml
> improve code quality

- lbry/wallet/server/db/canonical.py
- lbry/wallet/server/db/writer.py
- lbry/wallet/transaction.py
- tests/integration/blockchain/test_claim_commands.py
- tests/integration/blockchain/test_resolve_command.py
- tests/unit/wallet/server/test_sqldb.py
> finished switch from using hash `#` in URLs to a colon `:` when delineating claim name from claim id

- lbry/dht/peer.py
- lbry/utils.py
- lbry/wallet/server/cli.py
- lbry/wallet/server/env.py
- lbry/wallet/server/server.py
- lbry/wallet/server/udp.py
- tests/unit/dht/test_peer.py
- drop DHT and hub ping requests from a source port of under 1024, normal clients shouldn't be able to send these
- add a sanity check for bogon and reserved source ips to the hub ping server
- add `ALLOW_LAN_UDP` hub setting to allow hub clients from lan ips
> Restrict udp sources, add `ALLOW_LAN_UDP` hub setting

- lbry/file/source_manager.py
L135: If `getattr()` returns `None`, use `""` instead to avoid error in issue #3240
> Minor fix suggestion for issue #3240

- lbry/stream/managed_stream.py
- lbry/stream/reflector/client.py
- lbry/stream/reflector/server.py
- lbry/stream/stream_manager.py
- tests/unit/stream/test_reflector.py
> Don't set stream as reflected until reflector says it doesn't need any blob

- lbry/dht/peer.py
- lbry/utils.py
> use LRU caches for DHT metrics instead of unbound dicts

- scripts/checktrie.py
This is nothing special, it just allows the script to run without throwing an error on import.
> script/checktrie: fix the import to `SQLDB`

- lbry/wallet/rpc/session.py
- lbry/wallet/server/history.py
- tests/integration/blockchain/test_wallet_server_sessions.py
- tests/unit/wallet/server/test_migration.py
> [resync required] Avoid flush counter overflows on long running hubs by increasing it to 32 bits

- lbry/extras/daemon/exchange_rate_manager.py
If the error is not handled, the running daemon will continuously print the following error message:
```
Traceback (most recent call last):
File "lbry/extras/daemon/exchange_rate_manager.py", line 77, in get_rate
File "lbry/extras/daemon/exchange_rate_manager.py", line 189, in get_rate_from_response
KeyError: 0
```
This started happening when the UPBit exchange decided to delist the LBC coin.
Normally `json_response` should be a dictionary, not a list, so `json_response[0]` causes an error.
By checking for the `'error'` key, we can raise the proper exception.
Once this is done, the message will be a warning, not a traceback.
```
WARNING  lbry.extras.daemon.exchange_rate_manager:92: Failed to get exchange rate from UPbit: result not found
```
This addresses the second error in #3287.
> improved error handling when fetching exchange rate from UPbit

- lbry/wallet/account.py
- tests/unit/wallet/test_account.py
> make get_or_create_usable_address respect the generator lock, avoiding race conditions when getting an unused address while generating them

- scripts/download_blob_from_peer.py
Currently `lbrynet blob get <hash>` does not work to download single blobs which are not already present in the system.
The function locks up and never returns.
It only works for blobs that are in the `blobfiles` directory already.
This bug is reported in lbryio/lbry-sdk, issue #2070.
Since this script does in fact allow downloading an arbitrary blob, we may decide to copy parts of it and add them to `lbry.extras.daemon.daemon.jsonrpc_blob_get` in order to solve the previous issue.
> scripts: note to further investigate in `download_blob_from_peer`

- INSTALL.md
Because of issue #2769 at the moment the `lbrynet` daemon will only work correctly with Python 3.7.
The `deadsnakes` personal package archive (PPA) provides Python 3.7 for Ubuntu distributions that no longer have it in their official repositories like 18.04 and 20.04.
If Python 3.8+ is used, the daemon will start but the RPC server may not accept messages, returning the following:
```
Could not connect to daemon. Are you sure it's running?
```
----
Add more information regarding virtual environments.
Enter the environment with
```
source lbry-venv/bin/activate
```
And leave with `deactivate`.
When developing, we can start the server interactively.
```
python lbry/extras/cli.py start
```
> Improve the instructions in `INSTALL.md`

- lbry/extras/daemon/daemon.py
For some reason, when using `claim_search` with `--claim_id`, the arguments dictionary will also contain `claim_ids` with an empty list, even if we didn't specify it.
```
lbrynet claim search --claim_id=8945573bcfcb7f8276187dfbb93545eac4ebf71a
```
```
{
...
"name": "ValueError",
"traceback": [
"Traceback (most recent call last):",
"  File \"lbry/extras/daemon/daemon.py\", line 693, in _process_rpc_call",
"  File \"lbry/extras/daemon/daemon.py\", line 2483, in jsonrpc_claim_search",
"ValueError: Only 'claim_id' or 'claim_ids' is allowed, not both.",
""
]
},
"message": "Only 'claim_id' or 'claim_ids' is allowed, not both."
}
```
Using both `claim_id` and `claim_ids` will raise a `ValueError` exception so the daemon won't return a valid result even if the claim ID is in fact valid.
So if …
> fix error when using `--claim_id` with `lbrynet claim search`

- tests/integration/datanetwork/test_file_commands.py
> make libtorrent optional and skip test which depends on it

- lbry/wallet/server/env.py
this fixes compat with lbry vault and some electrum clients that aren't expecting `['']` on peer list, which is expected when federation is completely disabled.
> avoid [''] on peers list

- docs/api.json
- lbry/extras/daemon/daemon.py
This is necessary to produce the `docs/api.json` with correct information, and to be able to parse this file later on by other tools.
From
```
--blobs_in_stream<blobs_in_stream>
```
To
```
--blobs_in_stream=<blobs_in_stream> 
```
> fix typo in `file list` arguments list

- docker/Dockerfile.dht_node
- lbry/conf.py
- lbry/dht/node.py
- lbry/dht/peer.py
- lbry/dht/protocol/data_store.py
- lbry/dht/protocol/iterative_find.py
- lbry/dht/protocol/protocol.py
- scripts/dht_node.py
guide on https://github.com/lbryio/lbry.tech/pull/364/
closes #3174 
also adds Madiator as a known dht node as an example
> Add dht seed node script and dockerfile

- lbry/blob_exchange/downloader.py
- lbry/dht/node.py
- lbry/stream/downloader.py
- tests/unit/blob_exchange/test_transfer_blob.py
Tentative fixing. The node is primed with some fixed peers before triggering the blob download.
Please check comments on issue #2070
> Fix blob_get() would timeout. Issue #2070

- lbry/conf.py
- tests/integration/takeovers/test_resolve_command.py
Updates the default `tcp_port` setting (used for hosting blobs) to be the same as the default `udp_port` (used for the dht). Both now default to 4444.
> update default `tcp_port` to be the same as the default `udp_port`

- lbry/extras/daemon/daemon.py
- tests/integration/claims/test_claim_commands.py
Converts `hexdata` to a string before it is signed in `jsonrpc_channel_sign()`.
Fixes #3533
> convert hexdata argument to a string before signing in `channel_sign` command

- lbry/dht/node.py
- lbry/dht/peer.py
- lbry/dht/protocol/protocol.py
- lbry/dht/protocol/routing_table.py
- lbry/extras/daemon/daemon.py
- scripts/dht_node.py
The SDK already supports exporting metrics over Prometheus if the user wishes to do so. This PR adds the following metrics under the `dht_node` namespace:
- `stored_blobs_x_bytes_colliding`: Number of blobs with at least X bytes colliding with this node id prefix
- This is used to measure the ratio of content on network vs on blockchain. Check #3521 and [the dashboard repo](https://github.com/lbryio/dashboard), but it also needs #3511 merged.
- `stored_blobs`: Number of blobs announced by other peers
- `storing_peers`: Number of peers storing blobs announced to this node
- `peer_manager_keys`: Number of keys tracked by PeerManager dicts (sum)
- If that grows too large, we can get memory leaks
- `request_sent`: Number of requests send from DHT RPC protocol
- `request_success`: Number of …
> Add Prometheus metrics for DHT internals

- lbry/wallet/bip32.py
- lbry/wallet/transaction.py
> drop dependency on cryptography library in wallet module

- lbry/dht/blob_announcer.py
- `announcements_sent`:  `Number of announcements sent and their respective status.`
- labels:
- `peers`: number of peers we were able to announce
- `error`: if the announcement was a complete failure
- `announcement_queue_size`: `Number of hashes waiting to be announced.`
> Add optional Prometheus metrics for DHT announcements

- lbry/dht/peer.py
Theoretical impact from raw measurements on `memory_profiler` was 6mb of memory worst case.
Practical impact of a running node with 500 streams was a reduction (probably because 6mb is irrelevant if compared to overall usage pattern).
This is expected to close #3550 but other PR will follow with iterative find fixes that were discovered in the process.
> Increase DHT peer manager cache size to 16384

- lbry/extras/daemon/daemon.py
- tests/integration/claims/test_claim_commands.py
> let stream_update work on non-stream claims

- lbry/blob_exchange/downloader.py
`re_add` doesn't seem to do anything. I was debugging and we lose a lot of peers there. Running with that so far is way better, but I'm not sure why we had that code. I think that got lost during a refactor or rebase.
> fix handling re-adding lost peers during download

- lbry/dht/blob_announcer.py
Makes the hash announcer consume from a queue instead of just gathering batches (we were pausing for each gather, instead this gather consumers for a queue)
> DHT: make hash announcer use consumers instead of gathering batches

- lbry/extras/daemon/migrator/dbmigrator.py
- lbry/extras/daemon/migrator/migrate15to16.py
- lbry/extras/daemon/storage.py
- lbry/stream/downloader.py
- tests/integration/datanetwork/test_file_commands.py
- tests/unit/stream/test_reflector.py
backwards-incompatible: includes a migration, increasing the database version. This usually means you can't downgrade without a database backup.
This should make 1 announcement per stream instead of 2.
- stop announcing the head blob
- stop searching for it
- migration script to set all head blobs to should_announce=false
part of #3527 but probably doesn't close it (faster hash announcer and tracker to go)
> DHT: stop announcing the head blob

- lbry/blob/blob_file.py
- lbry/blob/blob_info.py
- lbry/blob/blob_manager.py
- lbry/extras/daemon/migrator/migrate8to9.py
- lbry/extras/daemon/storage.py
- lbry/stream/descriptor.py
- lbry/stream/stream_manager.py
- tests/integration/datanetwork/test_file_commands.py
- tests/unit/database/test_SQLiteStorage.py
- tests/unit/stream/test_stream_manager.py
- fixes bug where `blob_clean` (disk space management) would clean sd blobs from a SQL bad query
- fix bug where `added_on` is 0 for all blobs except sd blob
- change disk space management order to delete sd blobs last on both cases (seeding and normal space)
- fix bug where stream recovery would set sd blob as 'pending' and recover again every startup while also losing status for all other blobs in a stream
- on startup, if a blob is present but pending on db, check length and fix status
> Fixes bugs on disk space management and stream recovery

- lbry/schema/Makefile
- lbry/schema/types/v2/wallet.json
- setup.py
- tests/unit/wallet/test_wallet.py
A replacement for the would-be protobuf pull request. Depends on this PR: https://github.com/lbryio/types/pull/48/files
The idea is to add the wallet file format to the list of our known formats. This PR will confirm that `Wallet.to_dict` generates a wallet that conforms to the spec. This way we'll at least have some assurance that the spec is up to date.
I sort of made a guess as to what directory wallet.json would be best to go into.
BTW I added this to `Makefile` to try to match the `protoc` stuff, but running `make` doesn't seem to generate all of the python files that are there. There ends up being files removed from the repository.
> Add wallet json-schema, validate in one test.

- lbry/dht/node.py
- lbry/dht/protocol/iterative_find.py
- lbry/utils.py
See: https://github.com/lbryio/lbry-sdk/issues/3504
Script:
[scratch.py.txt](https://github.com/lbryio/lbry-sdk/files/8476728/scratch.py.txt)
Script output:
[scratch_1.txt](https://github.com/lbryio/lbry-sdk/files/8476723/scratch_1.txt)
Initially there is a lot of background activity from IterativeNodeFinder during what I presume is startup.
In steady state there is little activity after each "PAUSE---". Usually just stuff related to cancellation, if anything.
Eventually, I hope the "async with aclosing(...)" feature can be used:
https://docs.python.org/3.10/library/contextlib.html?highlight=aclosing#contextlib.aclosing
> Tighten up IterativeFinder async close behavior (DHT iterator continues after consumer breaks out of it)

- tests/integration/claims/test_claim_commands.py
- tests/integration/other/test_exchange_rate_manager.py
Unbundled from: https://github.com/lbryio/lbry-sdk/pull/3623
Getting these out of the way to improve reliability.
Beware that integration tests are STILL likely to fail due to test_es_sync_utility() chronic failures:
https://github.com/lbryio/hub/issues/55
> Fixes for intermittent test failures: test_exchange_rate_manager(), test_basic_claim_search()

- lbry/extras/daemon/daemon.py
Unbundled from https://github.com/lbryio/lbry-sdk/pull/3605
Using ```txo.amount``` (actual transaction amount) instead of the input arg ```amount``` facilitates ```amount=everything``` handling in future.
> Refactor _old_get_temp_claim_info(), eliminating "bid" arg.

- tests/integration/datanetwork/test_streaming.py
Unbundled from https://github.com/lbryio/lbry-sdk/pull/3623
Parent of "data_dir" seems to be "/tmp" and contents are always changing which disturbs test.
Apparently it's not causing a problem due to OS version and behavior of that OS version? It's causing major problems on upgrade to 20.04 for testing.
> Stabilize test_streaming.py by scanning the data_dir, not the parent of data_dir

- lbry/extras/daemon/exchange_rate_manager.py
- tests/integration/other/test_exchange_rate_manager.py
UPBit delisted LBC in 2021
Hotbit shutdown
> disable Hotbit and UPBit exchange rate feeds

- lbry/conf.py
- lbry/dht/node.py
- lbry/dht/protocol/iterative_find.py
- lbry/dht/protocol/protocol.py
- lbry/dht/protocol/routing_table.py
- lbry/extras/daemon/components.py
- scripts/dht_node.py
- tests/unit/dht/test_node.py
> Add all peers when running as a bootstrap node

- lbry/testcase.py
- tests/integration/takeovers/test_resolve_command.py
Fixes #3653 
Though generate() was written in a way that appears to wait for herald `db_height` to reach the expected value, it is not waiting for the correct terminal height (i.e. current + blocks_to_generate). Instead, generate() could return early anytime `_es_height` and `db_height` match.
I believe this was causing several integration tests to fail. Herald and Elastic Search were not in fact at the expected height when claims were fetched.
> Correct the terminal height we wait for in generate()

- tests/integration/blockchain/test_network.py
Fixes #3655
Looking to submit this after #3654... (or I could incorporate it into that.)
> Wait for hub to update with all 100 new blocks before proceeding with initial_headers_sync().

- lbry/wallet/ledger.py
- lbry/wallet/manager.py
- lbry/wallet/usage_payment.py
- tests/integration/blockchain/test_wallet_server_sessions.py
Fixes #3663
The WalletServerPayer was receiving `asyncio.CancelledError` from `retriable_call()` because `jsonrpc_wallet_reconnect()` creates a situation where the connection is totally gone.
I reworked how it handles exceptions so it tolerates ConnectionError, InsufficientFundsError without exiting prematurely.
Plan to revert https://github.com/lbryio/lbry-sdk/pull/3668/commits/44228961e688c2513a2ac9d2ba127c9009b54577 which is for push button testing.
> usage payment service more resilient, will continue running until funds available to pay usage fee

- .github/workflows/main.yml
- lbry/wallet/orchstr8/node.py
- lbry/wallet/wallet.py
- setup.py
- tests/integration/takeovers/test_resolve_command.py
- tests/integration/transactions/test_transaction_commands.py
- tests/unit/wallet/test_database.py
This completes pretty much all the work I planned to do on lbry-sdk test reliability. It should unblock more python3.9 work.
Fixes #3665
Fixes #3671 
Bumping hub gets us the benefit of these fixes:
https://github.com/lbryio/hub/issues/98
https://github.com/lbryio/hub/issues/101
https://github.com/lbryio/hub/issues/104
I also revisited #3658 because I encountered a new zlib.error "invalid window size".
I've started seeing failures like this when running tests. Something changed in the environment I think.
https://github.com/moodyjon/lbry-sdk/actions/runs/3447835647/jobs/5754426649
Successful run from 2mo ago with python 3.7.14 (failure was with 3.7.15):
https://github.com/moodyjon/lbry-sdk/actions/runs/3108575245/jobs/5038289310
Upgrade to pyinstaller==4.6 was suggested here: …
> Miscellaneous fixes for intermittent test failures 2

- .github/workflows/main.yml
Fixes #3721
I discovered that the:
echo "var=value" >> $GITHUB_OUTPUT
needs to be (on windows only):
echo "var=value" >> $env:GITHUB_OUTPUT
That's the main reason I switched to using $GITHUB_ENV instead of $GITHUB_OUTPUT. At least reading from the variable looks the same on windows & linux/Mac.
> Handle workflow deprecations

- .github/workflows/main.yml
- lbry/wallet/network.py
- tests/integration/other/test_exchange_rate_manager.py
This pull request fixes issue #3738.
> Fix checking protocol version
